### ISSUE TITLE
All screenshots on this page seem to be incorrect.

### ISSUE THREAD

**Issue by earl-d-moore** [AdobeDocs/experience-manager-65.en#1]
Issue in help/sites-administering/campaignstandard.md

**Comment by bohnertchris** [comment]
Thanks for reporting this, @earl-d-moore. This appears to be an issue resulting from our content migration to the new platform. We will address this shortly.

SSECD-632

**Comment by bohnertchris** [comment]
This has been fixed and the updated pages are now published.
