### ISSUE TITLE
Typo in the CUG configuration docs

### ISSUE THREAD

**Issue by jbrarAdobe** [AdobeDocs/experience-manager-65.en#10]
Issue in help/sites-administering/cug.md

There is a typo in step 5 at [1] it should be "configuration" instead of "comnfiguration"

[1] https://docs.adobe.com/content/help/en/experience-manager-65/administering/security/cug.html#applying-your-closed-user-group-to-content-pages

**Comment by aheim0** [comment]
Thank you for highlighting this issue and suggesting a solution. This has been addressed in commit 29328ff, and the changes are now live.

**Comment by aheim0** [comment]
Note: I will also make the change to the 6.4 repo.
