### ISSUE TITLE
Missing details on how the Property Picker dialogue works to pull custom metadata

### ISSUE THREAD

**Issue by lha-adobe** [AdobeDocs/experience-manager-65.en#100]
Issue in help/assets/metadata-import-export.md

Document in question: https://docs.adobe.com/content/help/en/experience-manager-65/assets/administer/metadata-import-export.html#best-practices-limitations-tips

Please include documentation limitation detail about the Property Picker:
Property Picker doesn't pick metadata properties from assets. It only shows properties which are used by the customer in schema editors and search forms.

Reference :   CQ-4236118

Ticket @ E-000156992

Feel free to change a different page if you do not believe this page is the proper one to change and add this detail

 {{Logged by support}}

**Comment by bohnertchris** [comment]
Thanks for the suggestion, @lha-adobe. We will review.

CQDOC-16238

**Comment by ashishguptaiitb** [comment]
Thanks for sharing. I've updated the limitations in the said article.
