### ISSUE TITLE
Section: AEM Communities Email Configuration needs review

### ISSUE THREAD

**Issue by aaksinghAdobe** [AdobeDocs/experience-manager-65.en#101]
Issue in help/communities/email.md

The OSGi configuration  - "AEM Communities Email Reply Configuration"  shows incorrect screenshots.
The "From" address is not available. This Label was renamed in new Social Bundles as per JIRA- CQ-88833. The details can be found in JIRA.

The value and this description is obsolete:
**Email "From" address** : (required) Address that notification email would be delivered from. Likely the same SMTP user specified for the default mail service . Default is no-reply@example.com .

![image](https://user-images.githubusercontent.com/62261083/84438357-6904f280-ac04-11ea-82f1-e560fb01c283.png)

**Comment by bohnertchris** [comment]
Thank you for the issue, @aaksinghAdobe. We will review.

CQDOC-16237

**Comment by vishabhguptaadobe** [comment]
Updated the screenshots and references in the content.
https://docs.adobe.com/help/en/experience-manager-65/communities/administer/email.html
