### ISSUE TITLE
Add information about different statuses for the language copies section in the references panel

### ISSUE THREAD

**Issue by sqdang** [AdobeDocs/experience-manager-65.en#102]
Issue in help/sites-administering/tc-manage.md

The language copies section in the references panel has multiple statuses that are not documented. Please review CQ-4292904 for information on that statuses and what they means.

[Logged By Support]

**Comment by bohnertchris** [comment]
Thank you for the suggestion, @sqdang. We will review.

CQDOC-16239

**Comment by aheim0** [comment]
Thanks for highlighting this. It looks as if the document has been updated since this issue was raised.
Closing this issue now - please feel free to open a new issue if further updates are required.
