### ISSUE TITLE
Update the "Create rollout configuration" documentation

### ISSUE THREAD

**Issue by clatimier** [AdobeDocs/experience-manager-65.en#103]
Issue in help/sites-developing/extending-msm.md

In the documentation https://docs.adobe.com/content/help/en/experience-manager-65/developing/extending-aem/extending-msm.html#create-the-rollout-configuration we mention:
"
Step 1: Open the Tools console in the classic UI; for example, https://localhost:4502/miscadmin#/etc
Step 2: In the folder tree, select the Tools , MSM , Rollout Configurations folder."
On the latest 6.5.5 the folder "MSM" in "Tools" doesn't exist. This needs to be reviewed and adjusted

[Logged By Support]

**Comment by bohnertchris** [comment]
Thank you for creating this issue, @clatimier. We will review.

CQDOC-16250

**Comment by aheim0** [comment]
This procedure been updated, and the changes are now live (for both 6.4 and 6.5).
