### ISSUE TITLE
Update the "Add Synchronization Actions to the Rollout Configuration" documentation

### ISSUE THREAD

**Issue by clatimier** [AdobeDocs/experience-manager-65.en#104]
Issue in help/sites-developing/extending-msm.md

In the documentation https://docs.adobe.com/content/help/en/experience-manager-65/developing/extending-aem/extending-msm.html#create-the-rollout-configuration we mention:
"Rollout configurations are stored below the /etc/msm/rolloutconfigs node"

Since 6.5, this is not the path where the configuration are stored anymore. 
OOTB they are stored in /libs/msm/wcm/rolloutconfigs nodes 
And the custom ones should go to /apps/msm/wcm/rolloutconfigs

See https://docs.adobe.com/content/help/en/experience-manager-64/deploying/restructuring/sites-repository-restructuring-in-aem-6-4.html#multi-site-manager-rollout-configurations

[Logged By Support]

**Comment by bohnertchris** [comment]
Thank you for creating this issue, @clatimier. We will review.

CQDOC-16253

**Comment by aheim0** [comment]
This procedure been updated, and the changes are now live (for both 6.4 and 6.5).
