### ISSUE TITLE
Remove the "Caution" note referencing 5.5

### ISSUE THREAD

**Issue by clatimier** [AdobeDocs/experience-manager-65.en#105]
Issue in help/sites-administering/msm-sync.md

In the section "CQ MSM Content Update Action - Exclusions" of https://docs.adobe.com/content/help/en/experience-manager-65/administering/introduction/msm-sync.html#creating-a-rollout-configuration, the "Caution" note refers to 5.5 configuration
This should be removed 

[Logged By Support]

**Comment by bohnertchris** [comment]
Thank you for creating this issue, @clatimier. We will review.

CQDOC-16255

**Comment by guillaumecarlino** [comment]
I fixed it.
