### ISSUE TITLE
Email notification template path is incorret

### ISSUE THREAD

**Issue by leoberliant** [AdobeDocs/experience-manager-65.en#107]
Issue in help/sites-administering/notification.md
The path to workflow notification is obsolete. It ha to be updated. Instead of been pointed to /etc, it has to be:
/libs/settings/workflow/notification/email/default/es.txt

**Comment by bohnertchris** [comment]
Thank you for creating this issue, @leoberliant. We will review.

CQDOC-16252

**Comment by aheim0** [comment]
Thanks for highlighting this.
The path mentioned has been updated, together with others:

- /etc/notification/email/default/com.day.cq.wcm.core.page
  - /libs/settings/notification-templates/com.day.cq.wcm.core.page
- /etc/notification/email/default/com.day.cq.wcm.core.page/en.txt
  - /libs/settings/notification-templates/com.day.cq.wcm.core.page/en.txt
- /etc/workflow/notification/email/default/en.txt
  - /libs/settings/workflow/notification/email/default/en.txt
- /etc/notification/email/default/com.day.cq.wcm.core.page
  - /libs/settings/notification-templates/com.day.cq.wcm.core.page
- /etc/workflow/notification/email/default
  - /libs/settings/workflow/notification/email/default

Closing this issue now.
