### ISSUE TITLE
Default value for transcoding in AEM 6.5

### ISSUE THREAD

**Issue by BharathValse** [AdobeDocs/experience-manager-65.en#108]
Issue in help/communities/ffmpeg.md

Default values for transocding is profile:format_ogg,profile:format_aac,profile:format_flv,profile:format_aac_ie.

But documents reports:
Default values: profile:firefoxhq,profile:hq,profile:flv,profile:iehq

**Comment by bohnertchris** [comment]
Thank you for creating the issue, @BharathValse. We will review.

CQDOC-16254

**Comment by vishabhguptaadobe** [comment]
Updated the default profiles, content will be live soon.

**Comment by vishabhguptaadobe** [comment]
Published article with updated Default values: 
https://docs.adobe.com/content/help/en/experience-manager-65/communities/administer/ffmpeg.html
