### ISSUE TITLE
Updated Trust store details in 6.4 and above

### ISSUE THREAD

**Issue by jbrarAdobe** [AdobeDocs/experience-manager-65.en#11]
Issue in help/sites-administering/saml-2-0-authenticationhandler.md

Section "Add the IdP Certificate to the AEM TrustStore": In 6.4+ the location of the trust store it found via Tools > Security > Global Trust Store, not by clicking on Trust Store for any user.

Update first 3 steps at [1]  from

**- Go to: [http://localhost:4502/libs/granite/security/content/useradmin.html
- Click on any of the users in the list.
- Go under Account Settings, and press the Create TrustStore link.**

 
 
To 

**- Go to: [http://localhost:4502/libs/granite/security/content/truststore.html
- press the Create TrustStore link
-** 

[1] https://docs.adobe.com/content/help/en/experience-manager-65/administering/security/saml-2-0-authenticationhandler.html#add-the-idp-certificate-to-the-aem-truststore

**Comment by bohnertchris** [comment]
Thanks for reporting this, @jbrarAdobe. @sarchiz, would you please have a look at this?

**Comment by sarchiz** [comment]
Closing this issue as it has been resolved.
