### ISSUE TITLE
Wrong entry name under "Enabling the Encapsulated Token"

### ISSUE THREAD

**Issue by EshanKumar** [AdobeDocs/experience-manager-65.en#110]
Issue in help/sites-administering/encapsulated-token.md

Under "Enabling the Encapsulated Token" section, point 2 mentions:
 _Look for an entry called Day CRX Token Authentication Handler_

There is no config with this name in AEM 6.5 and the name should be "Adobe Granite Token Authentication Handler"

**Comment by bohnertchris** [comment]
Thank you for creating this issue, @EshanKumar. We will review.

CQDOC-16258

**Comment by aheim0** [comment]
Thanks for highlighting this - the name has been updated.
Closing this issue now.
