### ISSUE TITLE
Missing information about enabling Day CQ DAM Event Recorder configuration in the docs

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-65.en#112]
Issue in help/assets/asset-reports.md

The doc contain information about enabling Asset Download service to generate an Asset Downloaded report, but it doesn't mention about enabling the _Day CQ DAM Event Recorder_ service.
![image](https://user-images.githubusercontent.com/59624839/84681221-d0bb8600-af01-11ea-8c95-e10f6b86d755.png)

We can add the Note section as follows:
Before you can generate an Asset Downloaded report, ensure that _Day CQ DAM Event Recorder_ service and _Asset Download_ event type are enabled. From the web console ( https://[aem_server]:[port]/system/console/configMgr ), open the Day CQ DAM Event Recorder configuration, and select  _Enables this service_ and _Asset Downloaded (DOWNLOADED)_ option in Event Types, if not already selected.
![image](https://user-images.githubusercontent.com/59624839/84680928-6dc9ef00-af01-11ea-85fc-05d3343244dc.png)

[Logged by AEM Support]

**Comment by ashishguptaiitb** [comment]
Thanks @sukohli .  This information is good to know. I shall cover it in the docs.

**Comment by bohnertchris** [comment]
CQDOC-16318

**Comment by ashishguptaiitb** [comment]
@sukohli  the article is now updated with the prerequisite. Thanks again for sharing this information.
