### ISSUE TITLE
Clarify you can use web console or cURL option but not interchangably

### ISSUE THREAD

**Issue by lha-adobe** [AdobeDocs/experience-manager-65.en#113]
Issue in help/sites-administering/enabling-crxde-lite.md

Clarify you can use web console or cURL option but not interchangably

Using the web console will create a org.apache.sling.jcr.davex.impl.servlets.SlingDavExServlet.config node while the cURL command creates org.apache.sling.jcr.davex.impl.servlets.SlingDavExServlet (sling:OsgiConfig -- no .config extension) node 

These 2 options are not meant to be used interchangably because AEM will only apply changes based on the SlingDavExServlet in INSTALLED state in the /system/console/osgi-installer UI

Reference E-000153206

{{Logged by Support}}

**Comment by bohnertchris** [comment]
Thank you for the suggestion, @lha-adobe. We will review.

CQDOC-16331

**Comment by aheim0** [comment]
Thanks for raising this - changes have been made and will be published soon.
Closing this issue now.
