### ISSUE TITLE
Missing information about Asset Download report related to folder containing assets

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-65.en#115]
Issue in help/assets/asset-reports.md

There's some missing information about Asset Download report related to folder containing assets.
Please include the following as a Note to this page:
_Assets that are selected individually and downloaded are visible in the assets downloaded report. However, if a folder or a collection containing assets is downloaded, those assets are not displayed in the assets downloaded report._
Verified in JIRA# CQ-101995

The similar information is provided in Step 3 of the doc here: _https://chl-author-preview.corp.adobe.com/content/help/en/experience-manager/brand-portal/using/brand-portal-download-users.html_
![image](https://user-images.githubusercontent.com/59624839/85179854-f32a0800-b24f-11ea-9851-e85d9312a586.png)

[Logged by AEM Support]

**Comment by bohnertchris** [comment]
Thank you for the suggestion, @sukohli. We will review.

CQDOC-16346

**Comment by mgulati1** [comment]
Thanks @sukohli. A note has been added and the issue has been fixed through the commit https://git.corp.adobe.com/AdobeDocs/experience-manager-65.en/pull/698/commits/0c41666353a8ee8d39285c99327680ab12377d61.

Changes are live at https://docs.adobe.com/content/help/en/experience-manager-65/assets/administer/asset-reports.html.
