### ISSUE TITLE
XML examples should include smart quote marks

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-65.en#116]
Issue in help/sites-administering/tc-rules.md

XML examples should not include smart quote marks.
XML only allows regular double quote marks.
The example XML content is not valid XML, for example:
<node path=“/content/mysite/en”>
should be
<node path="/content/mysite/en">

If customers copied and pasted in these examples, their XML parsing will fail and it will not obvious as to why.

**Comment by bohnertchris** [comment]
Thank you for pointing this out, @johnb4. We will review.

CQDOC-16344

**Comment by guillaumecarlino** [comment]
I fixed that already a couple of months ago.
