### ISSUE TITLE
Page Exporter feature documentation is deprecated and not completely usable

### ISSUE THREAD

**Issue by abangroo** [AdobeDocs/experience-manager-65.en#117]
Issue in help/sites-administering/page-exporter.md

The documentation of the  “Page Exporter” [1] feature is  outdated.
Other than documented, the exporter template can not be configured with a “site name”. The configuration has to be linked with a cq:exportTemplate attribute. This information is missing which makes it completely impossible for customers to do the configuration without any help from consulting/support.
The mentioned Geometrix examples obviously doesn’t exist anymore.
A reference to a “Content Sync” help site doesn’t contain a link. A search for such a page doesn’t bring up any suitable documents.

[1] https://docs.adobe.com/content/help/en/experience-manager-65/administering/contentmanagement/page-exporter.html

**Comment by bohnertchris** [comment]
Thank you for bringing this to our attention, @abangroo. We will review this content.

CQDOC-16354

**Comment by aheim0** [comment]
The page has now been reviewed, tested and updated.
Will close this issue now.
