### ISSUE TITLE
Improper spelling of "observation" and "length"

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-65.en#118]
Issue in help/sites-administering/operations-dashboard.md

"Oservation Queue Lenght" should be "Observation Queue Length".

**Comment by bohnertchris** [comment]
Good catch, @johnb4. Thanks for pointing that out. We will get it fixed.

CQDOC-16355

**Comment by aheim0** [comment]
Thank you for highlighting this. We have updated and published the page.
Will close this issue now.
