### ISSUE TITLE
Include description of how to control how often the Health Checks run

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-65.en#119]
Issue in help/sites-administering/operations-dashboard.md

There is no description of how the user controls how often the Health checks run. By default (OOTB) they run every 60 seconds.
See GRANITE-30380.
The OSGi configuration "com.adobe.granite.queries.impl.hc.QueryHealthCheckMetrics" (AKA "Query Health Check Configuration") has a single value "Period (getPeriod)", measured in seconds.
This is the value which controls how often the Heath Checks run.
Apparently applies only to AEM 6.5 and later versions.

**Comment by bohnertchris** [comment]
Good call-out, @johnb4. Thanks. We will look into it.

CQDOC-16382

**Comment by aheim0** [comment]
Thanks for highlighting this - a new subsection has been added, and will be published soon.
Closing this issue.
