### ISSUE TITLE
Spelling of word "sections" incorrect under Adobe I/O Runtime

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-65.en#12]
Issue in help/sites-developing/spa-ssr.md

The spelling of word "sections" is incorrect under the **Adobe I/O Runtime** section (https://docs.adobe.com/content/help/en/experience-manager-65/developing/headless/spas/spa-ssr.html#adobe-i-o-runtime) of the page.
It's written as **secitons** instead of **sections** .

[Logged by Support]

**Comment by aheim0** [comment]
Thank you for highlighting this issue and suggesting a solution. This has been addressed in commit 29328ff, and the changes are now live.

**Comment by aheim0** [comment]
Note: I will also make the change to the 6.4 repo.
