### ISSUE TITLE
The document refrencing old paths

### ISSUE THREAD

**Issue by hamid-k50** [AdobeDocs/experience-manager-65.en#120]
Issue in help/sites-developing/ht-projects-maven.md

The following document is referencing the old paths under "How-To Add Paths to the content Module"
https://docs.adobe.com/content/help/en/experience-manager-65/developing/devtools/ht-projects-maven.html#how-to-add-paths-to-the-content-module

support-initiated

**Comment by guillaumecarlino** [comment]
This was fixed.
