### ISSUE TITLE
AEM SPA SSR IO Runtime Recommendation Reasons Not Known

### ISSUE THREAD

**Issue by nagkulkarni** [AdobeDocs/experience-manager-65.en#121]
Issue in help/sites-developing/spa-ssr.md:

URL : https://docs.adobe.com/content/help/en/experience-manager-65/developing/headless/spas/spa-ssr.html

The documentation says "Adobe recommends a separate Adobe I/O Runtime instance for every AEM environment (author, publish, stage, etc.)" without specifying any reasons. Please add why separate IO Runtime instance is recommended for each author, publisher, and stage etc? The customer is asking why this recommendation? If this is not the case, please remove the sentence or update it with a proper recommendation.

Sentence mentioned is as below:

![image](https://user-images.githubusercontent.com/19787308/85974879-3c1e5100-b9f4-11ea-8e41-ac76de241f64.png)

**Comment by aheim0** [comment]
Thank you for raising this @nagkulkarni , we will investigate.

**Comment by bohnertchris** [comment]
This was updated via the following commits:

87f48e2 in the 6.4 repo
5908c6b in the 6.5 repo
6ceb1b0 in the AEMaaCS repo
