### ISSUE TITLE
Push latest version of page

### ISSUE THREAD

**Issue by thedoc31** [AdobeDocs/experience-manager-65.en#124]
There's a typo "predifined" in the copy of help/sites-developing/tough-day.md in Production. It appears this has been fixed in the git code but not pushed to Production. Please push the latest version.

**Comment by anujkapo** [comment]
@thedoc31, Thanks for reporting the issue. We will fix it.

**Comment by anujkapo** [comment]
Tracked via CQDOC-16423.

**Comment by thedoc31** [comment]
Great, thanks!

**Comment by bohnertchris** [comment]
This has been corrected in commit fc09607 to the 6.4 repo and in commit 8be4e41 to the 6.5 repo.
