### ISSUE TITLE
path needs update to reflect new structure

### ISSUE THREAD

**Issue by hamid-k50** [AdobeDocs/experience-manager-65.en#125]
Issue in help/sites-developing/designer.md

The referenced doc [1] state to use the /etc/designs for CSS etc. The documentation for 6.5 and 6.4 should be changed to add the project related css etc to /apps/<your project>

[1]https://docs.adobe.com/content/help/en/experience-manager-65/developing/introduction/designer.html

[support submitted]

**Comment by anujkapo** [comment]
@hamid-k50, Thanks for reporting the issue. We will fix it.

**Comment by anujkapo** [comment]
Tracked via CQDOC-16437.

**Comment by bohnertchris** [comment]
This was fixed by commit 5507350 in the 6.4 repo and commit 158e35a in the 6.5 repo.
