### ISSUE TITLE
Duplicate MBean URLs in Security Health Check section of this doc.

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-65.en#126]
Issue in help/sites-administering/operations-dashboard.md

There's a duplicate value of the MBean for Security Health Check in the document here: 
_https://docs.adobe.com/content/help/en/experience-manager-65/administering/operations/operations-dashboard.html#health-checks-provided-with-aem_
![image](https://user-images.githubusercontent.com/59624839/87073167-f4b17500-c1ea-11ea-8bbb-63af8e4cba30.png)

There should be just one URL for that Health Check's MBean. It can be found here on AEM: /system/console/jmx/org.apache.sling.healthcheck%3Aname%3Dsecuritychecks%2Ctype%3DHealthCheck
![image](https://user-images.githubusercontent.com/59624839/87073597-a650a600-c1eb-11ea-88b8-db10e64560d8.png)

[Logged by AEM Support]

**Comment by anujkapo** [comment]
Thanks, @sukohli. We will fix it.

**Comment by anujkapo** [comment]
Tracked via CQDOC-16438.

**Comment by raimanS** [comment]
Link fixed [1].
[1] - https://experienceleague.adobe.com/docs/experience-manager-65/administering/operations/operations-dashboard.html?lang=en#health-checks-provided-with-aem
