### ISSUE TITLE
The documentation for 6.5 and 6.4 should be changed to add the project related css etc to /apps/

### ISSUE THREAD

**Issue by jasmeet2dhiman** [AdobeDocs/experience-manager-65.en#127]
Issue in help/sites-developing/designer.md

The documentation for 6.5 and 6.4 should be changed to add the project related css etc to /apps/<your project> and not /etc/designs

**Comment by anujkapo** [comment]
Thanks for reporting, @jasmeet2dhiman. We are already tracking this fix using:
https://github.com/AdobeDocs/experience-manager-65.en/issues/125

**Comment by anujkapo** [comment]
Marking this one as a duplicate and closing it. Thanks!
