### ISSUE TITLE
Ends up in error 404 "  The webpage cannot be found "

### ISSUE THREAD

**Issue by prokopiu** [AdobeDocs/experience-manager-65.en#128]
Issue in help/forms/using/generic-steps-html-workspace-customization.md

The instructions are not working for me - repeating the procedure 3 times by the letter always ended with 404 for http://localhost:8080/lc/apps/ws/index.html. 

It seems that the **index** node with the **sling:resourceType** is missing and it cannot execute on the html.jsp.

The Note in the middle: **Place the entry of the user-defined CSS file after the entry of newStyle.css, as shown above**. Makes no sense. Should have probably been **Place the entry of the user-defined CSS file after the entry of style.css, as shown above.** 

Why I need to copy the Japanese date picker only - I do not need it and don`t want to change it (Copy /libs/ws/js/libs/jqueryui/jquery.ui.datepicker-ja.js)

This is frustrating - please help. 

Addendum: Create folder ws should be create a sling:Folder - a normal nt:folder seems not to work with overlays. After I created ws as sling:Folder and set up an index node with sling:resourceType = ws it worked.

**Comment by aheim0** [comment]
@prokopiu Thank you for highlighting this. We will investigate.

**Comment by anujkapo** [comment]
The updated version of the article is now available at:
https://experienceleague.adobe.com/docs/experience-manager-65/forms/use-aem-forms-workspace/generic-steps-html-workspace-customization.html?lang=en#use-aem-forms-workspace

Please let us know in case of any issues. Thanks!
