### ISSUE TITLE
https://console.adobe.io/integrations redirects to /home

### ISSUE THREAD

**Issue by somarc** [AdobeDocs/experience-manager-65.en#129]
Issue in help/sites-administering/integration-ims-adobe-io.md

Does this URL exist any more?
https://console.adobe.io/integrations 

It seems that the documentation on this page does not reflect reality in the Adobe Developer Console. 

Integrations seems to be Projects now.

**Comment by aheim0** [comment]
@somarc Thank you for highlighting this. We will investigate.

**Comment by aheim0** [comment]
This link has indeed changed. The page has been updated accordingly.
Closing this issue now.
