### ISSUE TITLE
Suggestion to include the word "AEM" after the word "allows"

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-65.en#13]
Issue in help/sites-administering/encapsulated-token.md

"The Encapsulated Token is a piece of cryptography that allows to securely create and validate authentication information offline" is missing a subject for the word "allows". My suggestion is to add "AEM" after "allows".
--
It should be like: 
"The Encapsulated Token is a piece of cryptography that allows AEM to securely create and validate authentication information offline"

https://docs.adobe.com/content/help/en/experience-manager-65/administering/security/encapsulated-token.html#stateless-authentication-with-the-encapsulated-token

[Logged by Support]

**Comment by aheim0** [comment]
Thank you for highlighting this issue and suggesting a solution. This has been addressed in commit 29328ff, and the changes are now live.

**Comment by aheim0** [comment]
Note: I will also make the change to the 6.4 repo.
