### ISSUE TITLE
Link to pattern detector package is outdated

### ISSUE THREAD

**Issue by thedoc31** [AdobeDocs/experience-manager-65.en#130]
Issue in help/sites-deploying/pattern-detector.md

Link to pattern detector is pointing to old Package Share location, which does not redirect the user to a friendly place to download the needed tool. The updated link is:

[1]
https://experience.adobe.com/#/downloads/content/software-distribution/en/aem.html?package=/content/software-distribution/en/details.html/content/dam/aem/public/adobe/packages/cq650/compatpack/pd-all-aem65

**Comment by anujkapo** [comment]
Thanks @thedoc31 for reporting the issue. We will fix it.

**Comment by anujkapo** [comment]
Tracking with CQDOC-16496

**Comment by sarchiz** [comment]
This issue has been resolved, thanks.
