### ISSUE TITLE
Broken Link to "AEM Forms FSI Reference Site Package" blocking customer demo

### ISSUE THREAD

**Issue by smehner** [AdobeDocs/experience-manager-65.en#132]
Issue in help/forms/using/setup-reference-sites.md

"AEM Forms FSI Reference Site Package" link on the page is broken to download the required assets needed.

The link takes you to the new portal, but the asset can not be found there....
https://downloads.experiencecloud.adobe.com/content/software-distribution/en/pswelcome.html?packagePath=/content/companies/public/adobe/packages/cq650/fd/AEM-FORMS-6.5-FSI-REF-SITE

Can you please help here?

**Comment by anujkapo** [comment]
Thanks, @smehner for reporting the issue. We will fix it.

**Comment by anujkapo** [comment]
Tracked with CQDOC-16508.

**Comment by smehner** [comment]
many thanks 👍

**Comment by anujkapo** [comment]
The links are fixed. The updated version of the article is available at:
https://docs.adobe.com/content/help/en/experience-manager-65/forms/getting-started/aem-forms-reference-collaterals/setup-reference-sites.html

**Comment by anujkapo** [comment]
Closing this one. Please let us know in case of any issues.
