### ISSUE TITLE
Tenant ID for IMS is not as clear as it could be. 

### ISSUE THREAD

**Issue by somarc** [AdobeDocs/experience-manager-65.en#134]
Issue in help/sites-administering/integration-ims-adobe-io.md]

The section around : 

Client Code : the Adobe IMS Tenant ID
The Adobe IMS Tenant ID must be entered in the field labelled Client Code.
![image](https://user-images.githubusercontent.com/8710267/88391968-331d6700-cd89-11ea-99ff-6586f10d6756.png)

Is as clear as mud. If you put any incorrect value you will get an exception thrown from here : 
https://git.corp.adobe.com/CQ/integration-target/blob/10bc102f35dc8114264dfbb01126d362d641370c/bundles/cq-target-integration/src/main/java/com/day/cq/analytics/testandtarget/impl/RestApiAdapter.java#L580

![image](https://user-images.githubusercontent.com/8710267/88392069-6233d880-cd89-11ea-95e0-40f12a192dc5.png)

and it's not at all clear what the value needs to be.

We should explicitly say that for IMS this value needs to come from Target itself.
So log into Target and pull the Tenant ID from the URL
![image](https://user-images.githubusercontent.com/8710267/88391304-ebe2a680-cd87-11ea-95f7-3617b43d3cf9.png)

EG as in the screenshot it would be "aemsupport" 

Customers fumble around in the Admin Console and Developer Console looking for this Tenant ID value and often put in the Org Id or ClientCode from the integration in frustration.

**Comment by anujkapo** [comment]
Thanks @somarc for reporting the issue. We will fix it.

**Comment by anujkapo** [comment]
Tracked with CQDOC-16539.

**Comment by aheim0** [comment]
Updates have been made and submitted for publishing (this might take a while).
Closing ticket now.
