### ISSUE TITLE
Add AEM Access to crx/de change 

### ISSUE THREAD

**Issue by ycastane** [AdobeDocs/experience-manager-65.en#135]
Issue in help/release-notes/sp-release-notes.md

In AEM6.5.5 you can no longer access crx/de easily and you are redirected to login screen.  If SAML implementation is present then users are not able to use an aem user to login.  Users have to login via http://author/libs/granite/core/content/login.html

The Release Notes should state this behavior clearly in the release notes.  Please include.  

[Logged by Support]

**Comment by anujkapo** [comment]
Thanks, @ycastane for pointing this out. We will investigate.

**Comment by anujkapo** [comment]
Tracked with CQDOC-16557.

**Comment by anujkapo** [comment]
The updates are available in the list of fixes:
https://docs.adobe.com/content/help/en/experience-manager-65/release-notes/service-pack/sp-release-notes.html
In addition, the updates are also available at:
https://docs.adobe.com/content/help/en/experience-manager-64/developing/devtools/developing-with-crxde-lite.html
