### ISSUE TITLE
miscadmin no longer contains /etc/msm/rolloutconfigs path

### ISSUE THREAD

**Issue by lha-adobe** [AdobeDocs/experience-manager-65.en#136]
Issue in help/sites-developing/extending-msm.md

The "Create the Rollout Configuration" section is detailing old steps.  There is no more /miscadmin path of /etc/msm/rolloutconfigs due to the 6.5 repository restructuring [1].

This document needs to be reviewed by engineering and updated based on their input on how customers can create custom rollout configurations via the UI now.

[1] https://docs.adobe.com/content/help/en/experience-manager-65/deploying/restructuring/sites-repository-restructuring-in-aem-6-5.html#multi-site-manager-rollout-configurations

**Comment by anujkapo** [comment]
Thanks, @lha-adobe. We will look into it.

**Comment by anujkapo** [comment]
Tracked with CQDOC-16544.

**Comment by bohnertchris** [comment]
This was corrected in commit 3a1d02f amongst others.
