### ISSUE TITLE
Update version of S3 Connector 

### ISSUE THREAD

**Issue by ycastane** [AdobeDocs/experience-manager-65.en#137]
Issue in help/sites-deploying/data-store-config.md

Older versions of S3 connector didn't work with Adobe Asset Link and AEM 6.5.5. Upgrade to 1.22 and Asset Link worked.  

[Logged by Support]

**Comment by anujkapo** [comment]
Thanks, @ycastane. We will take a look.

**Comment by anujkapo** [comment]
Tracked with CQDOC-16558.

**Comment by guillaumecarlino** [comment]
This was fixed
