### ISSUE TITLE
Include sample cURL call for reference of the Move/rename

### ISSUE THREAD

**Issue by lha-adobe** [AdobeDocs/experience-manager-65.en#139]
Issue in help/assets/mac-api-assets.md

Sample move cURL command with overwrite : 
`curl -u admin:admin -X MOVE https://<host>:<port>/api/assets/testfolder/test.png -H "X-Destination: http://localhost:6550/api/assets/destination/test.png" -H "X-Overwrite: T" `

Reference https://jira.corp.adobe.com/browse/GRANITE-30973

This is to demonstrate that the path should not contain /content/dam which is usually included for URI.  Including /content/dam would cause the command to fail and not work as expected with vague error message returned

{{Logged by Support}}

**Comment by anujkapo** [comment]
Thanks, @lha-adobe. We will look into it.

**Comment by anujkapo** [comment]
Tracked with CQDOC-16561.

**Comment by ashishguptaiitb** [comment]
Thanks @lha-adobe . The article is updated with the information.
