### ISSUE TITLE
Missing information for "Problems Using the Automatically Generated Replication Agents"

### ISSUE THREAD

**Issue by brigham57** [AdobeDocs/experience-manager-65.en#142]
Issue in help/sites-deploying/offloading.md

The Creating Replication Agents For Offloading section [1] states the following:
"_A known issue with the automatically-generated replication agents requires you to manually create new replication agents. Follow the procedure in Problems Using the Automatically Generated Replication Agents before you create the agents for Offloading."_

The link to "Problems Using the Automatically Generated Replication Agents" [2] is not accessible.
Can this be corrected so that the required information is available?

Thanks

[1] - https://docs.adobe.com/content/help/en/experience-manager-65/deploying/configuring/offloading.html#creating-replication-agents-for-offloading
[2] - https://docs.adobe.com/content/help/en/experience-manager-65/deploying/configuring/offloading.html#problems-using-the-automatically-generated-replication-agents

**Comment by brigham57** [comment]
On further review, the information looks to be present below the "caution" area, but there is no heading and the anchor link does not work.

**Comment by bohnertchris** [comment]
Thank you for pointing this out, @brigham57. We will look into it.

CQDOC-16660

**Comment by bohnertchris** [comment]
This was addressed with commit 08a6777.
