### ISSUE TITLE
DTM Content should be Deprecated in favor of Launch

### ISSUE THREAD

**Issue by shamlow** [AdobeDocs/experience-manager-65.en#143]
Issue in help/assets/touch-ui-using-dtm-for-asset-insights.md

Why is this page still in the docs without a major disclaimer that DTM is being sunsetted and they should use Launch?

https://docs.adobe.com/content/help/en/experience-manager-65/assets/managing/touch-ui-using-dtm-for-asset-insights.html.

Here is the page for the sunset plans for DTM. https://experienceleaguecommunities.adobe.com/t5/adobe-experience-platform-launch/dtm-plans-for-a-sunset/ba-p/331077

**Comment by bohnertchris** [comment]
Thank you for the information, @shamlow. We will look into it.

CQDOC-16661

**Comment by ashishguptaiitb** [comment]
Hi @shamlow , at the above link, I've made added a link to DTM's sunset announcement and a link to instructions to integrate and use Launch. It is highlighted at the beginning of the article.

Hope this helps. I'm closing this ticket.
