### ISSUE TITLE
Steps 5 & 6 have improper values show

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-65.en#144]
Issue in help/assets/managing-video-assets.md

Steps 5 and 6 have improper values shown:

5 is currently:
Refresh the browser. The overlay node /jcr_root/apps/dam/gui/content/assets/jcr:content/actions/secondary/create/items/fileupload is selected.

The path is "/apps/dam/gui/content/assets/jcr:content/actions/secondary/create/items/fileupload". It should not start with "/jcr_root".

6 is currently:
In the Properties tab, enter the appropriate value in bytes to increase the size limit to the desired size. For example, to increase the size limit to 30 GB, enter {sizeLimit : "32212254720"} value.

The "sizeLimit" property is a String property. Not sure why it's shown here in JSON notation since it's a simple String. The value should be "32212254720".

**Comment by anujkapo** [comment]
Thanks, @johnb4. We will take a look.

**Comment by anujkapo** [comment]
Tracked using CQDOC-16678.

**Comment by ashishguptaiitb** [comment]
Thanks again @johnb4. The article is updated with correct info. I am closing this issue.

Between, I've also updated the same in 6.4 docs (changes will reflect in a few hours).
