### ISSUE TITLE
-XX:MaxPermSize option has been removed from Java since version 8

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-65.en#145]
Issue in help/sites-deploying/in-place-upgrade.md

All references to the Java command option "-XX:MaxPermSize" should be removed. It's not been a valid option since Java 8 was released some years ago. The last version of Java which supported it was Java 7. All 6.3+ versions of AEM require Java 8, so this option needs to removed from our sample Java commands.

**Comment by anujkapo** [comment]
Thanks, @johnb4. We will fix it.

**Comment by anujkapo** [comment]
Tracked with CQDOC-16679.

**Comment by aheim0** [comment]
Thanks for highlighting this. A subsection has been added, and will be published soon.
Closing this issue.
