### ISSUE TITLE
Update the documentation page for Sling Health Checks

### ISSUE THREAD

**Issue by abangroo** [AdobeDocs/experience-manager-65.en#146]
According to the documentation[1] all Health Checks have a cache validity for only 2 seconds per default! With this every call from outside to get the information about the mbean, e.g. from QueryHealthCheckMetrics or New Relic, the result of the last run of the Health Checks is outdated and Health Checks need to be executed again. This is being controlled by the resultCacheTtlInMs property[1]. Because of this Custom Health Checks get executed  every minute which is being tracked in GRANITE-31173.

If for the custom Health Checks we configure the resultCacheTtlInMs now according to the asynchronous scheduler information. 

E.g. execution every 6 hours asyncCronExpression = "0 0 0/6 * * ? *", resultCacheTtlInMs = 21600000 or
execution every hour at minute 58 asyncCronExpression = "0 58 * * * ? *", resultCacheTtlInMs = 3600000

The result is, that all custom Health Checks are executed only at the scheduled times and in the meantime the cached result is delivered! For all calls of the mbean status, e.g. from healthreportlist.html the cached value is delivered and the Health Check is not executed again! 

[1]https://sling.apache.org/documentation/bundles/sling-health-check-tool-deprecated.html#configuring-the-health-check-executor-1

**Comment by anujkapo** [comment]
Thanks, @abangroo for reporting the issue. Can you also confirm the article (.md file), which requires updates? 
I navigated through the docs and could find the article at [1] the closest to fix this issue. Please let us know.
[1]: https://git.corp.adobe.com/AdobeDocs/experience-manager-65.en/blob/master/help/sites-administering/operations-dashboard.md

**Comment by abangroo** [comment]
@anujkapo  Yes, we need to update the Sling Health Check section in our documentation at [1] and include a note about this behavior when creating a custom health check

[1] https://docs.adobe.com/content/help/en/experience-manager-65/administering/operations/operations-dashboard.html

**Comment by anujkapo** [comment]
Thanks, @abangroo for the confirmation.

**Comment by anujkapo** [comment]
Tracked with CQDOC-16692.

**Comment by raimanS** [comment]
See comments from GRANITE-31173.
