### ISSUE TITLE
Add note about Java Version

### ISSUE THREAD

**Issue by bstopp** [AdobeDocs/experience-manager-65.en#147]
ToughDay2 doesn't work with Java11.

Please add a note to the docs indicating that Java8 is a requirement.

**Comment by anujkapo** [comment]
Thanks, @bstopp. We will include this information at [1].
[1]: https://git.corp.adobe.com/AdobeDocs/experience-manager-65.en/blob/master/help/sites-developing/tough-day.md

**Comment by anujkapo** [comment]
Tracked with CQDOC-16691.

**Comment by aheim0** [comment]
Thanks for highlighting this - a Caution has been added.
Closing issue.
