### ISSUE TITLE
Consistent reference to "each publish instance"

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-65.en#148]
Issue in help/sites-administering/sync.md

In section "4. Apache Sling Distribution Agent - Queue Agents Factory" it should state "on each publish instance" instead of "on publish" to be consistent with the rest of the document (particularly the setup instructions).

Also, they are "publish instances" not "publishers".  The standard nomenclature is "publish instance". We don't call them "publishers".

**Comment by aheim0** [comment]
Thanks for highlighting this, we will investigate.

**Comment by aheim0** [comment]
Being tracked with CQDOC-16738.

**Comment by aheim0** [comment]
Thanks for raising this, and apologies for the delay. The changes have been applied and will be published soon.
Closing this issue.
