### ISSUE TITLE
Missing steps, document needs cleaning

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-65.en#15]
Issue in help/sites-administering/cug.md

The section "Applying Your Closed User Group To Content Pages" is a mess. It is missing steps and tells you to save when you should not. It refers to items on different tabs without telling you to go to that tab first. It refers to 'Realms'. What Realms? There are none on the properties page.
--

**Comment by bohnertchris** [comment]
Thank you for reporting this, @johnb4. @sarchiz, would you please have a look at this?

**Comment by aheim0** [comment]
Thanks for highlighting this - the procedure has been updated.
Closing this issue.
