### ISSUE TITLE
Supported JREs need update

### ISSUE THREAD

**Issue by thedoc31** [AdobeDocs/experience-manager-65.en#151]
Issue in help/sites-deploying/technical-requirements.md

In the Java Virtual Machines table, please make it clear whether or not AEM Engineering will support AEM running on OpenJDK 8, OpenJDK 11, and Azul Zulu. These are currently missing from the table.

**Comment by thedoc31** [comment]
They are, however, covered in the PDF attached under [1], but I should not have to download a PDF to get more information about our support.

Also, please include the https://experience.adobe.com/downloads link directly on the page, again instead of having to open the PDF to find the download link for the Adobe-supported versions of Java 8 and Java 11.

**Comment by aheim0** [comment]
Thank you for raising this issue, we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-16750.

**Comment by thedoc31** [comment]
Closing as this request no longer applies. The values are updated on the technical requirements pages now, and there are download links directly next to the JVM versions.
