### ISSUE TITLE
Assets insights through Adobe Launch

### ISSUE THREAD

**Issue by danzhang-pm** [AdobeDocs/experience-manager-65.en#153]
Issue in help/assets/touch-ui-using-dtm-for-asset-insights.md

hi, As we are going to sunset Adobe DTM soon, could you update this documentation to introduce how to setup Asset Insights through Adobe Launch?

**Comment by aheim0** [comment]
Thank you for raising this, we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-16762.

**Comment by ashishguptaiitb** [comment]
@danzhang-pm , the Assets-Launch integration how-to is available at https://docs.adobe.com/content/help/en/experience-manager-learn/assets/advanced/asset-insights-launch-tutorial.html
Hope it helps. I'm closing this ticket. Let me know if anything more is required.
