### ISSUE TITLE
Should be marked deprecated

### ISSUE THREAD

**Issue by himanshu-pathak** [AdobeDocs/experience-manager-65.en#154]
Issue in help/sites-developing/extending-campaign-custom-template.md

The documentation suggests

"Make sure the page-component inherits from mcm/campaign/components/profile" 

However, with AEM 6.5 the component at /libs/mcm/campaign/components/profile is marked deprecated. I believe this means this integration approach is deprecated.

The documentation should call out the same.

**Comment by aheim0** [comment]
Thank you for highlighting this, we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-16771

**Comment by guillaumecarlino** [comment]
I added a caution at the top of the page.
