### ISSUE TITLE
In the "Locating the script" section, HTL is not mentioned as a script engine along with JSP

### ISSUE THREAD

**Issue by andreearadac** [AdobeDocs/experience-manager-65.en#155]
Issue in help/sites-developing/the-basics.md

Improvement suggestion.
https://docs.adobe.com/content/help/en/experience-manager-65/developing/introduction/the-basics.html#locating-the-script - why isn't HTL mentioned as a script engine?
It is confusing, as HTL is recommended by Adobe as an alternative for JSP.

**Comment by aheim0** [comment]
Thank you for suggesting this, we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-16772

**Comment by aheim0** [comment]
The changes have been made and submitted for publishing. They should be available soon.
Closing this.
