### ISSUE TITLE
Outdated doc regarding the Adobe I/O UI

### ISSUE THREAD

**Issue by twoznica90** [AdobeDocs/experience-manager-65.en#156]
Issue in help/sites-administering/integration-ims-adobe-io.md

The UI for Adobe.io has changed recently and is not reflected in this article.
Therefore, the steps performed in the Adobe.io console need to be updated. For example, integrations in Adobe I/O are now called projects.

**Comment by anujkapo** [comment]
Thanks, @twoznica90 for reporting the issue. We will fix it.

**Comment by anujkapo** [comment]
Tracked with CQDOC-16804.

**Comment by aheim0** [comment]
The changes have been made (though they might take a while to appear on the published pages).
Closing issue.
