### ISSUE TITLE
Upload Asset fails due to oak session timeout

### ISSUE THREAD

**Issue by jbrarAdobe** [AdobeDocs/experience-manager-65.en#157]
Issue in help/assets/managing-assets-touch-ui.md

Related to "CQ-4304997"

Need to add a note under the Upload Assets(#uploading-assets) section:

The default value when chunk upload is triggered is 500MB and the chunk size is 50MB. If you are modifying the "Apache Jackrabbit Oak TokenConfiguration" to set timeout configuration to be less than the time it takes for an asset to get uploaded, you might run into a timeout situation while the upload asset process is going on.

In that case, you need to change the "chunkUploadMinFileSize" and "chunksize", So, that each chunk request is refreshing the session.

Given the credential-expiry-timeout, latency, bandwidth, and expected concurrent uploads, the highest value(s) that allow you to ensure the following two should be picked:

- To ensure that chunk-upload gets enabled for files with sizes likely to cause credential-expiry mid-upload.
- To ensure that each chunk finishes before the credential is expired.

**Comment by anujkapo** [comment]
Thanks, @jbrarAdobe. We will take a look.

**Comment by anujkapo** [comment]
Tracked with CQDOC-16823.

**Comment by mgulati1** [comment]
@jbrarAdobe Added the Caution through https://jira.corp.adobe.com/browse/CQDOC-16823.
