### ISSUE TITLE
List of the allowed protocols in RTE

### ISSUE THREAD

**Issue by Daniil-Stelmakh** [AdobeDocs/experience-manager-65.en#158]
### Issue in help/sites-administering/configure-rich-text-editor-plug-ins.md

As per this documentation page, in order to customize the list of allowed protocols we should add `htmlRules` listing allowed protocols. Besides custom ones, we should explicitely list all which are allowed by default. The RTE implementation specifies the following list: `http://`, `https://`, `ftp://`, `mailto:`. This list doesn't match the one mentioned in the documentation.

**Comment by ashishguptaiitb** [comment]
Thanks @Daniil-Stelmakh . 
The protocols are mentioned at https://docs.adobe.com/content/help/en/experience-manager-65/administering/operations/configure-rich-text-editor-plug-ins.html#linkstyles
Search for "including https:// , https:// , file:// , and mailto: amongst others". Is this what you are looking for or something else? Are you suggesting that ALL supported protocols be listed?

**Comment by Daniil-Stelmakh** [comment]
@ashishguptaiitb I mean that  the documentation has an invalid list of protocols.
 It states:
`Array of valid protocols (including https:// , https:// , file:// , and mailto: amongst others)`
However, in my understanding the list  of actual default protocols supported by the RTE implementation should have been mentioned there. Which is:
`http://`, `https://`, `ftp://`, `mailto:`

**Comment by anujkapo** [comment]
Thanks, @Daniil-Stelmakh. We will take a look at it.

**Comment by anujkapo** [comment]
Tracked with CQDOC-16832.

**Comment by ashishguptaiitb** [comment]
Hi @Daniil-Stelmakh , I've updated the article to specifically mention the 4 supported protocols. It is a complete list now.
I'm closing this ticket. Let me know if more info is required.

**Comment by Daniil-Stelmakh** [comment]
Looks great! Thanks a lot.
