### ISSUE TITLE
/url examples incorrectly include request method "GET"

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-65.en#16]
Issue in help/communities/dispatcher.md

/url examples incorrectly include the request method "GET" in the value - see /0175 thru /0178. This is not correct syntax. See [https://docs.adobe.com/content/help/en/experience-manager-dispatcher/using/configuring/dispatcher-configuration.html](https://docs.adobe.com/content/help/en/experience-manager-dispatcher/using/configuring/dispatcher-configuration.html) 
Also /glob is deprecated and should not be shown as a valid example.
--

**Comment by ashishguptaiitb** [comment]
@vishabhguptaadobe , have a look at this issue.

**Comment by vishabhguptaadobe** [comment]
Tracked in CQDOC-16081 and fixed.
