### ISSUE TITLE
Externalized domains only apply to the content and not to the metadata such as view offer content

### ISSUE THREAD

**Issue by jbrarAdobe** [AdobeDocs/experience-manager-65.en#160]
Issue in help/sites-administering/experience-fragments-target.md

For the first caution section, where its mentioned "Externalizer Domains can now be selected"

Need to add the following info right below that line as per CQ-4306139:

Externalizer Domains section refers only to the content of the Experience Fragment that is sent to Target and not metadata such as View Offer Content.

**Comment by TylerRush** [comment]
CQDOC-16874

**Comment by aheim0** [comment]
The page has been updated - both the specified Caution, and also a second Caution under "Add the Cloud Configuration". 

The changes may take a while to be published. Closing this issue now.
