### ISSUE TITLE
Embedded SOLR integration with AEM 6.5 

### ISSUE THREAD

**Issue by aaksinghAdobe** [AdobeDocs/experience-manager-65.en#161]
Issue in help/sites-deploying/queries-and-indexing.md

For: Embedded SOLR  integration with AEM 6.5

GRANITE-30005

As per  Engineering they decide to not support anymore the Embedded Solr server. 
The solution would be to use a standalone Solr server for this. 
Would like to request a documentation bug for the same.

**Comment by bohnertchris** [comment]
Thank you @aaksinghAdobe , we will review.

**Comment by bohnertchris** [comment]
CQDOC-16892

**Comment by bohnertchris** [comment]
This was corrected in commit b27a7a1.
