### ISSUE TITLE
Details about using S3 with Async upload

### ISSUE THREAD

**Issue by aaksinghAdobe** [AdobeDocs/experience-manager-65.en#163]
Issue in help/sites-deploying/data-store-config.md

Seems there is little details about using S3 with Async upload.
Could not locate the steps. 
Please look to add the same so customers can choose to use Async of Synchronized uploads based on the use case.

**Comment by bohnertchris** [comment]
Thank you for the suggestion, @aaksinghAdobe. We will review.

**Comment by bohnertchris** [comment]
CQDOC-16930
