### ISSUE TITLE
Adobe I/O Steps and Screen captures are incorrect

### ISSUE THREAD

**Issue by ycastane** [AdobeDocs/experience-manager-65.en#168]
Issue in help/sites-administering/integration-ims-adobe-io.md

Adobe I/O Steps and Screen captures are incorrect.  Integrations are now Projects.  

[Logged by Support]

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-17012

**Comment by aheim0** [comment]
The changes have been made (though they might take a while to appear on the published pages).
Closing issue.
