### ISSUE TITLE
The config screenshot is missing the "SMTP use StartTLS" option. 

### ISSUE THREAD

**Issue by vdhaliwa** [AdobeDocs/experience-manager-65.en#17]
Issue in: https://docs.adobe.com/content/help/en/experience-manager-65/administering/operations/notification.html

The screenshot of com.day.cq.mailer.DefaultMailService config is taken from the old AEM version.

The updated config:

![Screen Shot 2020-01-17 at 3 16 58 PM](https://user-images.githubusercontent.com/60016809/72643400-993db300-393c-11ea-9aab-e05133bd1c80.png)

**Comment by ashishguptaiitb** [comment]
Hi @vdhaliwa , the screenshot is now updated. I'm closing the issue. 
Thanks for sharing this update with us.
