### ISSUE TITLE
[AEM6.5.6.0][DynamicMedia][Cache Invalidation] New feature not in Release-Notes

### ISSUE THREAD

**Issue by rwunsch** [AdobeDocs/experience-manager-65.en#170]
Issue in help/release-notes/sp-release-notes.md

we had an issue with "Cache Invalidation" with DynamicMedia in Onehub [0].

Here we learned of a new functionality rolled out in AEMaaCS and AEM6.5.6.0 -> "DynamicMedia Cache Invalidation" [1][2].

I however was not able to find anything about this on the release notes [3]. Also the documentation available for AEMaaCS claims:

The following steps apply only to Dynamic Media on AEM as a Cloud Service.

Could you please have the Documentation updated (both for the release notes [3], and the AEMaaCS-documentation [4]?

Thanks and cheers Robert

[0] https://adobe.ly/3n01fOr
[1] KT: https://adobe.ly/2JIWZox
[2] JIRA: https://adobe.ly/364wKjS
[3] https://docs.adobe.com/content/help/en/experience-manager-65/release-notes/service-pack/sp-release-notes.html
[4] Docs: https://docs.adobe.com/content/help/en/experience-manager-cloud-service/assets/dynamicmedia/invalidate-cdn-cache-dynamic-media.html

**Comment by rickbrough** [comment]
Always check both the release notes and the **What's New** notes where [Cache Invalidation in Dynamic Media](https://docs.adobe.com/content/help/en/experience-manager-65/release-notes/service-pack/new-features-latest-service-pack.html) is found. The sentence "The following steps..." was removed. It may take a day or two for the change to appear.
