### ISSUE TITLE
Remove the blue border from Page Diff when changing a Link Button Component.

### ISSUE THREAD

**Issue by gerardopw** [AdobeDocs/experience-manager-65.en#171]
Issue in ./help/sites-authoring/page-diff.md

Description of the Issue:
According to JIRA: CQBETA-1955, Engineering decided that starting with 6.5 computed styles are not taken into account anymore. They were producing too much noise. So images has no blue border anymore. This is per design. 
However this is not reflected in our Documentation. 
Please amend the Documentation to reflect how the Product is now behaving (eg: Please remove the blue border and text).

Thank you.
Gerard

**Comment by anujkapo** [comment]
Thanks, @gerardopw. We will take a look.

**Comment by anujkapo** [comment]
Tracked using CQDOC-17089.

**Comment by bohnertchris** [comment]
This has been corrected in commit fcf629e.
