### ISSUE TITLE
"AEM Pattern-detector page" shows raw-markdown-text, after move from "doc" to "experience league

### ISSUE THREAD

**Issue by rwunsch** [AdobeDocs/experience-manager-65.en#172]
Issue in ./help/sites-deploying/pattern-detector.md

Link: https://experienceleague.adobe.com/docs/experience-manager-65/deploying/upgrading/pattern-detector.html?lang=en#upgrading

![image](https://user-images.githubusercontent.com/662448/98690639-70742780-236d-11eb-8525-972540c7c142.png)

**Comment by anujkapo** [comment]
Thanks, @rwunsch for reporting the issue. We will fix it.

**Comment by anujkapo** [comment]
Tracked using CQDOC-17092.

**Comment by TylerRush** [comment]
This issue has been fixed. The page is now rendering correctly. Thanks for reporting this error to us!

https://experienceleague.adobe.com/docs/experience-manager-65/deploying/upgrading/pattern-detector.html?lang=en#upgrading
