### ISSUE TITLE
Poor Usability of the document - Instructions extremely difficult to follow

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-65.en#174]
Issue in ./help/sites-deploying/tarmk-cold-standby.md

In the new design of the documents, there's very poor usability, especially on this document. It's extremely difficult to follow the instructions on the doc, on how to use TarMK Cold Standby.

Readable Document: https://helpx.adobe.com/experience-manager/6-3/sites/deploying/using/tarmk-cold-standby.html
![image](https://user-images.githubusercontent.com/59624839/99442781-da4d7d80-28e7-11eb-8f15-273c696e03d4.png)

Non-readable Document: https://experienceleague.adobe.com/docs/experience-manager-65/deploying/deploying/tarmk-cold-standby.html?lang=en#deploying
![image](https://user-images.githubusercontent.com/59624839/99442882-ff41f080-28e7-11eb-9300-59e3ad29b333.png)

It's difficult to follow the instructions. Moreover, all the points start with 1. and don't have any proper spacing/line breaks in them.

[Logged by AEM Support]

**Comment by ashishguptaiitb** [comment]
@sukohli thanks for sharing this issue. It crept in recently because of some bug in the publishing system. I've fixed it for now and the page should be updated in some time.

**Comment by aheim0** [comment]
Tracked with CQDOC-17132.

**Comment by ashishguptaiitb** [comment]
Hi @sukohli , the published article is in good shape now. I'm closing this issue. Let us know if anything more is required.
