### ISSUE TITLE
AEM 6.5.5+ (meaning SP5 and SP6 as of Nov 2020) require v1.10.12 of S3 connector for Platform API

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-65.en#175]
Issue in ./help/sites-deploying/data-store-config.md

This page needs to document that 6.5 SP5 and SP6 (the current available Service Packs as of Nov 2020) require S3 connector 1.10.12 in order for the Platform API to function. See Jira CQ-4309565. The repo also need to have connector version 1.10.12 added to it (hopefully soon). Why only SP5 and SP6? Because these are using OAK 1.22 and prior SPs were using OAK 1.10. OAK 1.22 requires newer S3 connector version.
The Platform API is used by Adobe Asset Link (AAL). If the Platform API fails then AAL will fail to connect.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-17134.

**Comment by guillaumecarlino** [comment]
Looks like it was done with CQDOC-16998.
