### ISSUE TITLE
Title of the page is incorrect

### ISSUE THREAD

**Issue by rockstarlearner** [AdobeDocs/experience-manager-65.en#176]
Issue in ./help/sites-administering/generic.md

https://experienceleague.adobe.com/docs/experience-manager-65/administering/ecommerce/generic.html?lang=en#products-and-product-variations

  <title>ttitle</title>

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
The title field has been corrected, and submitted for publishing (might take a while to appear on publish.
Closing issue.

**Comment by aheim0** [comment]
Tracked with CQDOC-17135
