### ISSUE TITLE
The link to Privilege manager is broken

### ISSUE THREAD

**Issue by vdhaliwa** [AdobeDocs/experience-manager-65.en#18]
Issue in help/sites-administering/security.md

In the section "Extending Privileges on a Project Level" the link provided in the text "Jackrabbit API" is broken. The correct link should be : https://jackrabbit.apache.org/api/2.8/org/apache/jackrabbit/api/security/authorization/PrivilegeManager.html

**Comment by bohnertchris** [comment]
Thank you for reporting this broken link, @vdhaliwa. We will fix.

**Comment by bohnertchris** [comment]
Fixed in commits:

2c907e9 in experience-manager-65.en
6483ef1 in experience-manager-64.en
