### ISSUE TITLE
Dead link in article 

### ISSUE THREAD

**Issue by riosmart** [AdobeDocs/experience-manager-65.en#180]
In [configure assets CC integration ](https://experienceleague.adobe.com/docs/experience-manager-65/administering/integration/configure-assets-cc-integration.html#create-an-application) article the link to https://legacy-oauth.cloud.adobe.io. is a dead link.

My customer is having issues syncing assets as he cannot get past this point on the page.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-17146.

**Comment by riosmart** [comment]
Thanks for investigating. If possible would appreciate a temporary workaround to setup asset sync between AEM/Experience Cloud if possible.

**Comment by ashishguptaiitb** [comment]
Thanks @riosmart for the confirmation. I am closing this GitHub issue as well.
