### ISSUE TITLE
Configuring the Connection to Adobe Analytics details missing

### ISSUE THREAD

**Issue by josephrignanese** [AdobeDocs/experience-manager-65.en#181]
Issue in ./help/sites-administering/adobeanalytics-connect.md

Url: https://experienceleague.adobe.com/docs/experience-manager-65/administering/integration/adobeanalytics-connect.html

Currently this section displays a warning message referring to analytics map. But this seems incorrectly duplicated from the below section.

![Screen Shot 2020-11-25 at 3 05 46 pm](https://user-images.githubusercontent.com/17347917/100182027-bca79600-2f2f-11eb-98e3-d5cc64106df5.png)

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-17147.

**Comment by aheim0** [comment]
This change was explicitly requested. All details are on CQDOC-17147.
Closing this issue now.
