### ISSUE TITLE
Remove helpx links under the "Additional Resources" link

### ISSUE THREAD

**Issue by jbrarAdobe** [AdobeDocs/experience-manager-65.en#183]
Issue in ./help/sites-deploying/replication.md

Remove help links under the Additional Resources link. They are not applicable anymore and most of them redirect to 404

**Comment by bohnertchris** [comment]
Thanks for pointing this out, @jbrarAdobe. We'll look into it.

CQDOC-17161

**Comment by sarchiz** [comment]
Thanks for reporting this @jbrarAdobe. This issue has been fixed.
