### ISSUE TITLE
Need to add a Caution for Disk Usage Report

### ISSUE THREAD

**Issue by jbrarAdobe** [AdobeDocs/experience-manager-65.en#184]
Issue in ./help/assets/asset-reports.md

The Disk Usage Report will fail to generate if you are using Dynamic Media and some of the assets are not proceed properly. To resolve the issue, Reprocess the assets and try to re-run the report.

Internal Reference Ticket: E-000224856

**Comment by bohnertchris** [comment]
Thanks for the suggestion, @jbrarAdobe. We'll have a look.

CQDOC-17170

**Comment by ashishguptaiitb** [comment]
Thanks @jbrarAdobe , in 65 and also in CS articles, I've added a troubleshooting step to call out this issue.

I'm closing this issue. Let me know if I can help further.
