### ISSUE TITLE
syncexternalusers with JMX

### ISSUE THREAD

**Issue by motoyamakai** [AdobeDocs/experience-manager-65.en#185]
Issue in ./help/sites-administering/jmx-console.md

A customer was trying to sync users from LDAP with JMX using the syncexternalusers query. There is currently limited documentation on syncexternalusers specifically and only tutorials on syncallusers. The customer was using the same query as she was on AEM 6.2 as follows: ['CN=Banu B Arslan,OU=Users,OU=Troy,DC=CORP,DC=FSROOT,DC=FLAGSTAR,DC=COM'] . However, the proper query was as follows: ['CN=Banu B Arslan,OU=Users,OU=Troy,DC=CORP,DC=FSROOT,DC=FLAGSTAR,DC=COM;corp'] . This would be useful information to have somewhere in the documentation for people trying to utilize the syncexternalusers command. Thanks!

**Comment by TylerRush** [comment]
CQDOC-17230

**Comment by sarchiz** [comment]
Closing as "Doesn't Qualify". See CQDOC-17230 for more details.
