### ISSUE TITLE
Warning Note for Tag GC

### ISSUE THREAD

**Issue by BharathValse** [AdobeDocs/experience-manager-65.en#186]
Issue in ./help/sites-developing/building.md

Tag garbage collection also deletes tags outside of cq:tags property like custom tag properties. Please refer to internal issue CQ-4312045 for more information on the use case. 

Request to add this warning for the benefit of customers trying to use custom properties to associate tags.

**Comment by TylerRush** [comment]
CQDOC-17231

**Comment by bohnertchris** [comment]
Closing this due to lack for feedback on CQDOC-17231.
