### ISSUE TITLE
Old Images need to be updated

### ISSUE THREAD

**Issue by jbrarAdobe** [AdobeDocs/experience-manager-65.en#189]
Issue in ./help/sites-authoring/touch-ui-managing-projects.md

AEM console has changed a lot in the last few years and is completely different compared to what is shown in the screenshots. Can you please update the screenshots/images?

**Comment by TylerRush** [comment]
CQDOC-17236

**Comment by bohnertchris** [comment]
Thank you for reporting this, @jbrarAdobe. It was fixed in the AEMaaCS documentation set.

https://git.corp.adobe.com/AdobeDocs/experience-manager-cloud-service.en/pull/2359

However then it went overlooked for 6.5 and we apologize for this delay. It has been corrected with commit 8810e25.
