### ISSUE TITLE
Correct the path where the configuration is stored

### ISSUE THREAD

**Issue by clatimier** [AdobeDocs/experience-manager-65.en#192]
Issue in ./help/communities/asrp.md

There is still the old path "/etc/socialconfig/srpc" referenced in the page where the correct path is "/conf/global/settings/communities/srpc"

[Logged By Support]

**Comment by TylerRush** [comment]
CQDOC-17244

**Comment by vishabhguptaadobe** [comment]
Thanks @TylerRush, 
This will be fixed in the coming week.

**Comment by vishabhguptaadobe** [comment]
@TylerRush
The content is live at: https://experienceleague.adobe.com/docs/experience-manager-65/communities/administer/asrp.html?lang=en#troubleshooting
