### ISSUE TITLE
Wrong information about page move being synchronous (NPR-33875)

### ISSUE THREAD

**Issue by clatimier** [AdobeDocs/experience-manager-65.en#195]
Issue in ./help/release-notes/previous-hotfixes-featurepacks.md

NPR-33875 mentions in the release notes "Page move operations are restricted to **synchronous** move only"
Based on the JIRA, this is the opposite, the page move operations are now only **asynchronous**
See the JIRA title "All page move operations should be asynchronous"

[Logged By Support]

**Comment by anujkapo** [comment]
Thanks, @clatimier. We will fix it.

**Comment by anujkapo** [comment]
Tracked using CQDOC-17276.
