### ISSUE TITLE
Outdated reporting document

### ISSUE THREAD

**Issue by himanshu-pathak** [AdobeDocs/experience-manager-65.en#196]
Issue in ./help/sites-administering/reporting.md

This documentation is outdated as there is no way to access these reports in 6.5 touch UI.
https://experienceleague.adobe.com/docs/experience-manager-65/administering/operations/reporting.html?lang=en#the-basics-of-report-customization

**Comment by anujkapo** [comment]
Thanks, @himanshu-pathak. We will look into it.

**Comment by anujkapo** [comment]
Tracked using CQDOC-17281.

**Comment by bohnertchris** [comment]
The Classic UI limitation is now called out in a note on this page. Fixed in commit b16cf41 to 6.4 and commit 04b872d to 6.5.
