### ISSUE TITLE
The spelling of PDF is incorrect

### ISSUE THREAD

**Issue by manish112** [AdobeDocs/experience-manager-65.en#198]
Issue in ./help/sites-administering/content-disposition-filter.md

Please correct the spelling of pdf.

Original line:  For example, you could not view a pfd online.

**Comment by TylerRush** [comment]
The spelling error has been corrected:

https://experienceleague.adobe.com/docs/experience-manager-65/administering/security/content-disposition-filter.html

Thanks for reporting this issue!
