### ISSUE TITLE
Configuration are mentioned on author instance instead of publish instance

### ISSUE THREAD

**Issue by clatimier** [AdobeDocs/experience-manager-65.en#200]
Issue in ./help/communities/sync.md

For the section "Queue Agents Factory" and "Diff Observer Factory", it mentions that these configuration have to be done on the author instance
Although, based on (1) the same configuration need to be done on the publish instance(s) instead

Could you please review and amend if necessary?

(1) https://experienceleague.adobe.com/docs/experience-manager-65/administering/security/sync.html?lang=en

[Logged By Support]

**Comment by TylerRush** [comment]
CQDOC-17316

**Comment by vishabhguptaadobe** [comment]
Updated the docs: https://experienceleague.adobe.com/docs/experience-manager-65/administering/security/sync.html?lang=en#apache-sling-distribution-agent-queue-agents-factory
