### ISSUE TITLE
Default AEM favicon is not visible after upgrade to AEM 6.5.6 #AuthoringExperience

### ISSUE THREAD

**Issue by anubajaj23** [AdobeDocs/experience-manager-65.en#206]
After upgrade, not able to see default favicon under 'http://localhost:4502/sites.html.

**Issue:**
<img width="422" alt="Screenshot 2021-01-15 at 11 03 53 AM" src="https://user-images.githubusercontent.com/51432815/104685557-5e25b980-5721-11eb-8f44-6d0a2b386ccc.png">

**Findings**: 
The path of favicon does not exists and gives 404

<img width="1180" alt="Screenshot 2021-01-15 at 11 05 58 AM" src="https://user-images.githubusercontent.com/51432815/104685748-c6749b00-5721-11eb-9a6b-5e01eb3bce57.png">

Can anyone please help me out on this?

**Comment by TylerRush** [comment]
CQDOC-17326

**Comment by aheim0** [comment]
Profound apologies for the delay in responding to this. As it does not seem to be a problem with the documentation we can only suggest that you contact Support (and hope you have already).
Closing this issue now.
