### ISSUE TITLE
Missing slash between jcr:content and jcr:data

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-65.en#207]
Issue in ./help/sites-administering/content-disposition-filter.md

There is a missing slash near the end of this sentence. It could also use a comma to make it more readable. It looks like this right now:

> Independent of the configuration only resource paths are covered which contain a property named ‘jcr:data’ or ‘jcr:content jcr:data’.

It should look like this:

> Independent of the configuration, only resource paths are covered which contain a property named ‘jcr:data’ or ‘jcr:content/jcr:data’.

**Comment by aheim0** [comment]
Thank you for raising this - we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-17329.

**Comment by aheim0** [comment]
The changes have been made and published. Thanks for the contribution.
Closing issue now.
