### ISSUE TITLE
Information regarding restructuring of workflow models states the deployment the modified Workflow Models into a local AEM 6.4 development instance. It should mention 6.5 instead of 6.4 for 6.5 doc.

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-65.en#209]
Issue in ./help/sites-deploying/all-repository-restructuring-in-aem-6-5.md

Information regarding restructuring of workflow models states the deployment the modified Workflow Models into a local AEM 6.4 development instance. It should mention 6.5 instead of 6.4 for 6.5 doc.
![image](https://user-images.githubusercontent.com/59624839/105514976-23cc9700-5ca2-11eb-88c3-5d9f98cafe0c.png)

[Logged by AEM Support]

**Comment by aheim0** [comment]
Thanks for highlighting this - we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-17376.

**Comment by aheim0** [comment]
The change has been made and published.
Closing issue.
