### ISSUE TITLE
Add prerequisites

### ISSUE THREAD

**Issue by himanshu-pathak** [AdobeDocs/experience-manager-65.en#21]
Issue in help/sites-administering/integration-ims-adobe-io.md

Please add a prerequisites section to call out what privileges are required for I/O console and Admin console.

**Comment by aheim0** [comment]
Thank you for raising this issue. The requirements were already addressed in a Caution at the top of the page, in this circumstance Support must be contacted. 
However, we have converted this Caution to a Prerequisites section as requested. This has been addressed in commit 519c273, and the changes are now live.
