### ISSUE TITLE
UI style broken for Workflow Models section on this doc - Text coming out of the table on Google Chrome

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-65.en#210]
Issue in ./help/sites-deploying/all-repository-restructuring-in-aem-6-5.md

Text is coming out of the table on the following section(Workflow Models) in Google Chrome:
https://experienceleague.adobe.com/docs/experience-manager-65/deploying/restructuring/all-repository-restructuring-in-aem-6-5.html?lang=en#prior-to-upgrade

![image](https://user-images.githubusercontent.com/59624839/106058435-3cccb200-60bf-11eb-9a9a-ab7206f0c34a.png)

[Logged by AEM Support]

**Comment by bohnertchris** [comment]
Thanks for pointing this out, @sukohli. We'll take it up with the doc platform team.

CQDOC-17388

**Comment by bohnertchris** [comment]
This issue was addressed by the documentation platform team. Verified in Safari and Chromium browsers that the issue no longer occurs.
