### ISSUE TITLE
Page "json-exporter-components" not available in Experience League

### ISSUE THREAD

**Issue by rwunsch** [AdobeDocs/experience-manager-65.en#219]
Hi,

I found that the following page in not available in Experience League: https://github.com/AdobeDocs/experience-manager-65.en/blob/master/help/sites-developing/json-exporter-components.md

It could have  been in either of these locations - as follows - but it is not present.
* https://experienceleague.adobe.com/docs/experience-manager-64/developing/components/json-exporter-components.html?lang=en
* https://experienceleague.adobe.com/docs/experience-manager-65/developing/components/json-exporter-components.html

Could you please help making it avialable?

**Comment by aheim0** [comment]
Thanks for highlighting this - we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-17497.

**Comment by aheim0** [comment]
I've checked and can access the 6.5 page:
- https://experienceleague.adobe.com/docs/experience-manager-65/developing/components/json-exporter-components.html?lang=en#components

But the 6.4 page seems to be missing and redirects to ExL Home page. Though it is visible in the left navigation.

Will investigate further.

**Comment by aheim0** [comment]
The ToC has now been updated for 6.4 and the page is available at:
- https://experienceleague.adobe.com/docs/experience-manager-64/developing/components/json-exporter-components.html?lang=en#components

Hope that all works for you. Closing issue.

**Comment by rwunsch** [comment]
Thanks a ton, this works now.
Have a good week-end!

**Comment by aheim0** [comment]
@rwunsch 
Thanks for the confirmation - and wishing you a good weekend too!
