### ISSUE TITLE
Translation updates in 6.4 and above

### ISSUE THREAD

**Issue by jbrarAdobe** [AdobeDocs/experience-manager-65.en#22]
Issue in help/sites-administering/tc-tic.md

The screenshot under the "Creating a Translation Integration Configuration" is outdated and no longer supported.

Also, we need to add the following note:

To align with Context-Aware Configuration [1], we have switched to context selection for Translation Configuration and Translation Credential configuration. This would mean that a user would not select these configurations directly and instead select appropriate contexts. As an example, the same available in sites/XF/screens in Properties page via Advanced Tab > Cloud Configuration.

A translation user would be able to create only one config of each type in a context. In the case of context, the selection is currently not available he/she would be able to create config in fallback path(/conf/global). This means, he would be able to create only one TIF (used for translation settings), for example, one Microsoft config, one lingotek config etc. In case users need multiple configs, one would have to add the configuration browser.

This change was done in 6.4 as part of the repository restructuring.

[1] https://sling.apache.org/documentation/bundles/context-aware-configuration/context-aware-configuration.html

**Comment by guillaumecarlino** [comment]
Closing this old issue as the jira is fixed. Please  create a new one if this was a mistake.
