### ISSUE TITLE
at.js 2.x is not supported with AEM > It is now

### ISSUE THREAD

**Issue by paran-k** [AdobeDocs/experience-manager-65.en#220]
Caution comment: "at.js 2.x is not supported with AEM at the point of the AEM 6.5 release. Please use latest version of at.js 1.x" is outdated. From my understanding at.js 2.x is supported by Target-AEM 6.5 integration. Please remove or update accordingly.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-17510.

**Comment by paran-k** [comment]
HI team,

If It helps you can refer to the thread here, where I reach out to ask the product team about this topic: https://wiki.corp.adobe.com/x/5dmlVw. They updated me today stating that there is some functionality loss, in fact:

After talking with other Target PMs it seems like the flow when users are creating Target activities inside AEM (using the Targeting flow) it is not supported for at.js 2.x right now. So if the customer is using this flow - instead of creating activities directly into Target, it is NOT yet supported with at.js 2.x.
If all they want is the export XFs from AEM to Target, then this flow is supported for at.js 2.x.



Kind Regards,
Paran

Paran Karunaharan  |  Senior Business Consultant  |  Adobe  |  T +44 (0) 746 498 1514  |  karunaha@adobe.com<mailto:karunaha@adobe.com>

Upcoming time off:

  *   Monday, 8th March – International Women’s Day
  *   Monday, 29th March – Tuesday, 6th April

**Comment by aheim0** [comment]
The amendments have been made and published.
Closing issue.
