### ISSUE TITLE
AEM forms captcha not validating the string entered 

### ISSUE THREAD

**Issue by aeisha** [AdobeDocs/experience-manager-65.en#223]
Hi,

I have created an aem adpative form that captures user-entered data and submits it in the end. Before the submission, I am using the **built-in AEM CAPTCHA** service provided in the out-of-box captcha component, to distinguish between humans and bots.

Captcha only verifies if there is a value entered but doesn't check if the value entered is a correct string.

It seems to behave similarly on all the systems. I am using **AEM v6.5.7.**

Thanks in advance

**Comment by anujkapo** [comment]
Hi @aeisha. This seems to be a product functionality bug instead of a doc issue. Please let us know if there are any improvements required in the documentation.
