### ISSUE TITLE
Unable to connect to Assets Instance

### ISSUE THREAD

**Issue by b-887** [AdobeDocs/experience-manager-65.en#224]
Issue in ./help/assets/use-assets-across-connected-assets-instances.md

Hello, I am following the instructions https://experienceleague.adobe.com/docs/experience-manager-65/assets/using/use-assets-across-connected-assets-instances.html?lang=en#setup-licensing

Everything works fine up to point when I need to login in to Assets instance from the sites instance.  I am able to successfully log in to the asset instance after clicking _Log in to Connected Assets_.  But I still can not see the assets from the remote DAM. Once I am logged in I see that the  GET request for `http://ASSETS_AUTHOR_IP:4502/libs/dam/remoteassets/content/query.json` returns a 302 response with redirect to `/libs/dam/remoteassets/content/loginerror.html`

Request details:
```
Request URL: http://ASSETS_AUTHOR_IP:4502/libs/dam/remoteassets/content/query.json?_dc=1614793872210&fullText=&limit=0..20&_charset_=utf-8&jcr%3Acontent%2Fmetadata%2Fdc%3Aformat=image%25&_=1614793587360
Request Method: GET
Status Code: 302 Found
Remote Address: ASSETS_AUTHOR_IP:4502
Referrer Policy: strict-origin-when-cross-origin
```

Response:
```
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://ASSETS_SITES_IP:4502
Content-Length: 0
Date: Wed, 03 Mar 2021 17:51:19 GMT
Location: http://ASSETS_AUTHOR_IP:4502/libs/dam/remoteassets/content/loginerror.html
```
The following response GET http://ASSETS_AUTHOR_IP:4502/libs/dam/remoteassets/content/loginerror.html result returns a 401 response. 

I see that login-token cookie created for assets author is not passed along with this request. When I open the URL in the new browser tab I can see the JSON with assets from Assets Author (cookie is present there) so there is definitely issue with credentials.

I was trying to set this up in Chrome cookies settings as suggested in the documentation so I set the General Setting to `Allow all cookies` and in the `Sites that can always us cookies` I added rules for the IP of assets author and sites author with `Including third-party cookies on this site` but still no luck here. 

Could you please advise how to approach this issue ?

AEM: **6.5.7**
Browser: Chrome 89.0.4389.72 (same for Firefox latest)
Assets Share Commons: 1.9.4

**Comment by b-887** [comment]
This might be connected to recent Chrome updates around Cross-Origin Resource Sharing Policy https://blog.heroku.com/chrome-changes-samesite-cookie

When `SameSite by default cookies` and `Cookies without SameSite must be secure` are disabled in `chrome://flags/` and when I changed the `SameSite` attr for `login-token` cookie (manual change in dev tools from `Lax` to empty value) for Assets Author I was able to connect to the assets. 

As far as I understand this will not be the issue when I will have a dispatcher in front of both instances with an https - I will check that in near future. If this is actually the issue maybe it would be worth adding this to the `Troubleshoot issues` section as `how to enable third-party cookies` is not enough.

**Comment by anujkapo** [comment]
Thanks, @b-887 for pointing this out. Please open a similar issue if a documentation update to the Troubleshooting section is required. Closing this one for now.

**Comment by b-887** [comment]
HI @anujkapo 
I would suggest to update the Troubleshooting section. Can't we do this in scope of this ticket ? :)

**Comment by aheim0** [comment]
@b-887 
Thanks for the follow-up. We will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-17569.

**Comment by ashishguptaiitb** [comment]
For cross-site access login-token cookie needs to have SameSite=None. It is added as a step in Connected Assets configuration. More details are documented at https://experienceleague.adobe.com/docs/experience-manager-65/administering/security/same-site-cookie-support.html

This should help with the issue @b-887 . I'm closing the ticket.
