### ISSUE TITLE
RTE #paraFormat is getting disabled after using List or pressing Enter

### ISSUE THREAD

**Issue by anubajaj23** [AdobeDocs/experience-manager-65.en#225]
After AEM upgrade to 6.5 Service pack 6.5.6, #paraFormat is getting disabled in text components. 

**Steps to reproduce:**
- Open any page in author
- Drag Text component (It can be RTE or core text component )
- Edit RTE
- Type any text in the dialog, currently paraFormat is enabled
- Now Type n number of List items and press enter
- After List end Paraformat icon is disabled
- This is happening also with Heading tags.

**Current behaviour :**
After pressing enter, disabled attribute is appending to the paraformat icon
<img width="1411" alt="Root Cause" src="https://user-images.githubusercontent.com/51432815/110072371-abc6b600-7da3-11eb-800f-99190d83c294.png">

**Expected behaviour**
Paraformat should be enabled in all cases except list

**Environment**
AEM 6.5.6
Core Components version 2.13

**Impacted Area:**
Same thing is happening in Table, RTE and Text & Image components

![rte](https://user-images.githubusercontent.com/51432815/110072031-23e0ac00-7da3-11eb-957b-ccbd21f26bf3.jpeg)

**Comment by anujkapo** [comment]
Thanks, @anubajaj23 for reporting the issue. Do we need a documentation update or is it a product bug? We would request you to contact customer care for product issues.

**Comment by anubajaj23** [comment]
Hi, Thanks for pointing it out, yes it is a product bug and can you please take me on the product Issues portal/repo ?  It will be helpful.

Thanks

**Comment by anujkapo** [comment]
Thanks, @anubajaj23. Closing this one.
