### ISSUE TITLE
Service package instructions contain broken link to HTTP API from Package Manager page

### ISSUE THREAD

**Issue by acollign** [AdobeDocs/experience-manager-65.en#229]
Issue in ./help/release-notes/sp-release-notes.md

In this procedure entry, the HTTP API link is broken

> B. Use the HTTP API from Package Manager. Use cmd=install&recursive=true so that the nested packages are installed.

This may be a good candidate  to point to

https://experienceleague.adobe.com/docs/experience-manager-65/administering/contentmanagement/package-manager.html?lang=en#package-share

**Comment by aheim0** [comment]
Thank you for raising this - we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-17601.

**Comment by aheim0** [comment]
The link has been updated - thanks for your input.
Closing issue.
