### ISSUE TITLE
Repository Restructuring link is broken

### ISSUE THREAD

**Issue by vdhaliwa** [AdobeDocs/experience-manager-65.en#23]
Issue in help/sites-deploying/backward-compatibility.md

The link to "Repository Restructuring in AEM" in the first blue note is broken.  It redirects to page https://docs.adobe.com/content/help/en/experience-manager-65/deploying/upgrading/repository-restructuring-in-aem65.md which does not exist.

The redirection should happen to page "https://docs.adobe.com/content/help/en/experience-manager-65/deploying/restructuring/repository-restructuring.html"

**Comment by bohnertchris** [comment]
Thank you for reporting this, @vdhaliwa. We will address this broken link.

**Comment by bohnertchris** [comment]
Fixed in commit 2c907e9 in experience-manager-65.en
