### ISSUE TITLE
This page should come down - the feature has been removed from AEM

### ISSUE THREAD

**Issue by sschnoor** [AdobeDocs/experience-manager-65.en#230]
Issue in ./help/sites-administering/configure-assets-cc-integration.md

This has been deprecated.  The APIs don't exist any longer.

https://experienceleague.adobe.com/docs/experience-manager-cloud-service/release-notes/deprecated-removed-features.html?lang=en#deprecated-features 

![image](https://user-images.githubusercontent.com/12835879/112355833-491e5700-8c8b-11eb-877c-b0a038e0ebfb.png)

**Comment by bohnertchris** [comment]
Thank you for reporting this, @sschnoor 

CQDOC-17661

**Comment by ashishguptaiitb** [comment]
The integration articles are removed. RNs are updated with the relevant info. Redirects will be established soon. 
Closing this ticket.
