### ISSUE TITLE
Correct information about the page to select to rollout a blueprint from the References panel

### ISSUE THREAD

**Issue by clatimier** [AdobeDocs/experience-manager-65.en#235]
Issue in ./help/sites-administering/msm-livecopy.md

In the section "Roll Out a Blueprint from the Reference Rail", step 1. we mention
"In the Sites console, select the page in the blueprint and open the References panel (from the toolbar)."
This is incorrect as the page to select should be the one in the livecopy to have access to the blueprint option in the references panel

https://experienceleague.adobe.com/docs/experience-manager-65/administering/introduction/msm-livecopy.html?lang=en#rolling-out-a-blueprint 

[Logged by Support]

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-17763.

**Comment by aheim0** [comment]
The update has been made in both the 6.5 and Cloud Service pages.
Closing this issue.
