### ISSUE TITLE
404: Link to Headless and Hybrid with AEM

### ISSUE THREAD

**Issue by synox** [AdobeDocs/experience-manager-65.en#237]
Issue in ./help/sites-developing/json-exporter-components.md

Link in the left sidebar to "Headless and Hybrid with AEM" to https://www.adobe.com/content/dam/www/us/en/marketing/experience-manager-sites/headless-content-management-system/pdfs/aem-hybrid-architecture-wp-1-18-19.pdf leads to a 404

**Comment by anujkapo** [comment]
Thanks, @synox for reporting the issue. We will fix it.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thank you for highlighting this.

The navigation item now points to:

- https://business.adobe.com/content/dam/dx/us/en/products/experience-manager/sites/headless-content-management-system/pdfs/aem-hybrid-architecture-wp-1-18-19.pdf

Which is accessible.

Closing this issue.
