### ISSUE TITLE
known issues missing for previous service pack documentation

### ISSUE THREAD

**Issue by himanshu-pathak** [AdobeDocs/experience-manager-65.en#239]
Issue in ./help/release-notes/previous-hotfixes-featurepacks.md

https://experienceleague.adobe.com/docs/experience-manager-65/release-notes/service-pack/previous-hotfixes-featurepacks.html

There should be a dedicated page for each service pack like we have for the latest one. Not all customer can be on latest service pack always. The one thing which is missing in previous service pack release notes is the known issues for each service pack which is a huge documentation gap.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by anujkapo** [comment]
That's a great point, @himanshu-pathak. We will start implementing it starting this SP, which will have known issues for SP8 and SP9. I will discuss with @ukgaurav on what can be done for the previous 6.5 SPs.

**Comment by anujkapo** [comment]
We have implemented the change by segregating the Known Issues for each SP starting SP8 and will continue this in the future.

SP9 Known Issues: https://experienceleague.adobe.com/docs/experience-manager-65/release-notes/service-pack/sp-release-notes.html?lang=en#known-issues

SP8 Known Issues: https://experienceleague.adobe.com/docs/experience-manager-65/release-notes/service-pack/previous-hotfixes-featurepacks.html?lang=en

Closing this one. Please let me know in case of any issues.
