### ISSUE TITLE
Content overlapping -- difficulty reading

### ISSUE THREAD

**Issue by lha-adobe** [AdobeDocs/experience-manager-65.en#24]
Issue in help/release-notes/wcm-platform.md

The Search section is overlapped by the Security and User Interface sections making the content difficult to read

Also, the Search right hand menu option is not working

Not certain if he Search section should be a literal search bar -- however, that is the content displaying in the document body (suspecting this is not correct content to be displayed)

{Logged by Support}

**Comment by bohnertchris** [comment]
Thank you for reporting this, @lha-adobe. This unfortunately is an issue with how the new platform treats anchors with certain keywords. We will address.

**Comment by bohnertchris** [comment]
Screenshot for reference. See also SSECD-424

![screen-shot 2020-02-05 at 14 23 22](https://user-images.githubusercontent.com/38424477/73845499-15803380-4823-11ea-8e94-f92340fdd5a6.png)

**Comment by bohnertchris** [comment]
This was fixed with commits:
a63883c in experience-manager-65.en
4fd4276 in experience-manager-64.en
255d6af in experience-manager-cloud-service.en
