### ISSUE TITLE
Page extraction section references old Geometrixx pages from AEM 6.2

### ISSUE THREAD

**Issue by ycastane** [AdobeDocs/experience-manager-65.en#242]
Issue in [./help/assets/indesign.md](https://experienceleague.adobe.com/docs/experience-manager-65/assets/administer/indesign.html)

Page extraction section references old Geometrixx pages from AEM 6.2.

Please update to proper paths and WKND example

<Logged by Support>

**Comment by anujkapo** [comment]
Thanks, @ycastane. We will fix it.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by ashishguptaiitb** [comment]
I've updated the article with a generic screenshot that does not include Geometrixx in the file path. Closing this issue.
