### ISSUE TITLE
Scripts path is wrong

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-65.en#243]
Issue in ./help/sites-developing/workflows-customizing-extending.md

The scripts path  is not "/apps/myapp/workflow/scripts".

The proper scripts path is "/apps/workflow/scripts", or any path under there.
For verification see
https://git.corp.adobe.com/Granite/com.adobe.granite.workflow.console/blob/master/src/main/java/com/adobe/granite/workflow/console/servlet/ProcessListServlet.java 
and search for "/apps/workflow/scripts" or APPS_SCRIPT_ROOT.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This was fixed in commit 13f15be.
