### ISSUE TITLE
Support for Mongo DB 4.2

### ISSUE THREAD

**Issue by BharathValse** [AdobeDocs/experience-manager-65.en#246]
Issue in ./help/sites-deploying/technical-requirements.md

Support for Mongo DB 4.2 not updated in technical requirement doc.
Refer Internal jiras GRANITE-27054 and NPR-36373

**Comment by anujkapo** [comment]
Thanks, @BharathValse. We will fix it.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
The page has been updated and republished. Thanks for highlighting this.
Closing issue.
