### ISSUE TITLE
Angular sample app links to react-app

### ISSUE THREAD

**Issue by jjohnson-wooliesX** [AdobeDocs/experience-manager-65.en#249]
Issue in ./help/sites-developing/spa-ssr.md

The link to the Angular sample app that demonstrates SSR links to the react-app repository.

![image](https://user-images.githubusercontent.com/79879243/120587324-7bf97e00-c478-11eb-818d-03327670a2e3.png)

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This was fixed with commit 31e6bd6.
