### ISSUE TITLE
Example code/XML should never include smart quotes

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-65.en#251]
Issue in ./help/sites-administering/tc-rules.md

Smart quotes, such as the characters “ and ” should never be in code nor in XML content since they are not valid delimiters.
The only double quote mark allowed is the character " (which is both for a start and end delimiter).
If customers copy and paste the sample code with smart quotes it will cause errors and will be very confusing to customers as it's not obvious to them why it's failing with odd syntax or parsing errors.

Examples from this page are:

```
<nodelist>
     <node path="/content”>
           <property name="text" />
     </node>
     <node path=“/content/mysite/en”>
          <property name=“text” translate=“false" />
     </node>
<nodelist>
```

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
thanks for reporting @johnb4, will be fixed shortly
