### ISSUE TITLE
Incomplete documentation for previous service pack releases

### ISSUE THREAD

**Issue by himanshu-pathak** [AdobeDocs/experience-manager-65.en#255]
Issue in ./help/release-notes/previous-hotfixes-featurepacks.md

This is in continuation to https://github.com/AdobeDocs/experience-manager-65.en/issues/239

As i said earlier, every service pack should have its own dedicated page which i can bookmark. The current approach doesn't help much. For instance the UberJar section is missing now for the previous release page. A single page for multiple service pack is a really bad idea with the right rail showing multiple duplicates.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate and evaluate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
@himanshu-pathak, we changed it to have one page per each service pack. See https://experienceleague.adobe.com/docs/experience-manager-65/release-notes/service-pack/6.5.6.html for example.

**Comment by himanshu-pathak** [comment]
Thanks. This looks good. However, 2 quick things.

1. The uber jar info is still not there for all the earlier service packs.
2. Something hss changed and now when i search for "aem service pack release notes" google gives https://experienceleague.adobe.com/docs/experience-manager-65/release-notes/service-pack/sp-release-notes.html as a first result and this points to a 404.

**Comment by guillaumecarlino** [comment]
@himanshu-pathak, you're right, I added a uberjar section in all the individual pages. 
That page you get from google does not exist anymore as I split it into individual pages. I requested redirects for the old pages and it should redirect soon. However in the meantime, you can easily navigate to the specific SP you want using the left navigation

**Comment by himanshu-pathak** [comment]
Thanks @guillaumecarlino. Looks good now.
