### ISSUE TITLE
Rendering of the page is off and links do not display properly

### ISSUE THREAD

**Issue by ichirital** [AdobeDocs/experience-manager-65.en#256]
Issue in  https://experienceleague.adobe.com/docs/experience-manager-65/developing/platform/dev-reports.html?lang=en

![image](https://user-images.githubusercontent.com/15053333/124380968-e4c25900-dcb7-11eb-9a6c-e74ed0f5fc4c.png)

**Comment by aheim0** [comment]
Thanks for highlighting this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
@ichirital This seems to be a platform issue. We are in contact with the relevant team (but it might take a while). Thanks for your understanding.

**Comment by aheim0** [comment]
The rendering issue has been fixed by the platform team.

https://experienceleague.adobe.com/docs/experience-manager-65/developing/platform/dev-reports.html?lang=en is now looking as it should.

Thanks for raising this - will close this issue now.
