### ISSUE TITLE
[Request] Update The RemotePage Component page to include Angular steps

### ISSUE THREAD

**Issue by iameduardod** [AdobeDocs/experience-manager-65.en#258]
Issue in ./help/sites-developing/spa-remote-page.md

Update The RemotePage Component page to include Angular steps: https://experienceleague.adobe.com/docs/experience-manager-65/developing/headless/spas/spa-remote-page.html?lang=en

**Comment by iameduardod** [comment]
@aheim0

**Comment by iameduardod** [comment]
reopen

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
The remote-page component has only be tested to work with the React framework and therefore doesn't support remotely  loading applications from other frameworks. Commit a664d07 to this repository and c53b50e to AEMaaCS.
