### ISSUE TITLE
Page formatting messed up

### ISSUE THREAD

**Issue by shunnaradobe** [AdobeDocs/experience-manager-65.en#259]
Issue in [./help/sites-administering/configure-rich-text-editor-plug-ins.md](https://experienceleague.adobe.com/docs/experience-manager-65/administering/operations/configure-rich-text-editor-plug-ins.html)

Check the page formatting, it's messy all around

**Comment by shunnaradobe** [comment]
https://experienceleague.adobe.com/docs/experience-manager-65/administering/operations/configure-rich-text-editor-plug-ins.html?lang=en

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
This seems to be a platform issue. We are in contact with the relevant team (but it might take a while). Thanks for your understanding.

**Comment by ashishguptaiitb** [comment]
Hi @shunnaradobe , the page rendering issue is resolved now. Thanks again for pointing it out. 
I am closing this issue.
