### ISSUE TITLE
404 link at the CSRF page

### ISSUE THREAD

**Issue by jbrarAdobe** [AdobeDocs/experience-manager-65.en#26]
Issue in help/sites-developing/csrf-protection.md

The "Cross-Site Request Forgery OWASP page ." link at the end of the page is going to 404

[1] https://owasp.org/www-community/crsf

**Comment by bohnertchris** [comment]
This was reported in the 6.4 repo already and 6.5 was fixed there as well.

https://github.com/AdobeDocs/experience-manager-64.en/issues/52

Closing this as a duplicate, but thanks for being thorough, @jbrarAdobe!
