### ISSUE TITLE
admin console steps update

### ISSUE THREAD

**Issue by ryrob30** [AdobeDocs/experience-manager-65.en#264]
Issue in ./help/sites-administering/integration-ims-adobe-io.md

Under assign privileges (https://experienceleague.adobe.com/docs/experience-manager-65/administering/integration/integration-ims-adobe-io.html?lang=en)
If refers to "integrations" in the admin console. That no longer exists it appears to be under API now.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thank you for raising this - it looks as if the page has been updated in the meantime.
Closing this issue.
