### ISSUE TITLE
"AEM-Stock Integration" only works with "Enterprise Stock" and "Service Account in AdobeIO" (NOT with Oauth in AdobeIO)

### ISSUE THREAD

**Issue by rwunsch** [AdobeDocs/experience-manager-65.en#266]
Issue in ./help/assets/aem-assets-adobe-stock.md

Hello Adobe Documentation Team,

According to a Slack conversation, the "AEM-Stock-Integration" only supports (works with) a "Enterprise Stock"-entitlement, which then provides the option to create an AdobeIO-Integration for Stock with a "Service Account":

Slack: https://adobe-acs.slack.com/archives/C453R58B1/p1614620498143900?thread_ts=1614612724.140800&cid=C453R58B1

> You cannot use OAuth 2.0 for AEM. You must use a JWT service account. These are two different integration types.
> You must belong to an Enterprise Stock entitlement and be a System Admin to see the JWT option. 

The website above ( ./help/assets/aem-assets-adobe-stock.md) explains that "Oauth2.0" can be used with the AEM-Stock Integration, which is wrong, according to my knowledge.

> 5. Click Create new project and click Add API. Select Adobe Stock from the list of APIs that are available to you. Select OAUTH 2.0 Web.

The correct approach is documented here (but unfortunately not in a high detail level, and without screenshots:
https://experienceleague.adobe.com/docs/experience-manager-learn/assets/creative-workflows/adobe-stock.html?lang=en

> **Set up Adobe IMS Configuration using Adobe I/O Console**
> 1. Create an Adobe IMS Technical Account Configuration under Tools > Security
> 2. Select the Cloud Solution as Adobe Stock and create a new certificate or re-use an existing certificate for the configuration.
> 3. Navigate to Adobe I/O Console and **create a new Service Account integration for Adobe Stock.**
> 4. Upload the certificate from Step2 to your Adobe Stock Service Account integration.
> 5. Choose the required Adobe Stock profile configuration and complete the service integration.
> 6. Use the integration details to complete the Adobe IMS Technical Account configuration
> 7. Make sure you can receive the access token using the Adobe IMS Technical Account.

**Comment by rwunsch** [comment]
also tracked in CQDOC-18322.

**Comment by bohnertchris** [comment]
Thank you, @rwunsch for the detailed issue. We will review.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by vishabhguptaadobe** [comment]
Updated the doc: https://experienceleague.adobe.com/docs/experience-manager-65/assets/using/aem-assets-adobe-stock.html
