### ISSUE TITLE
Issue in Automated test case

### ISSUE THREAD

**Issue by prihr** [AdobeDocs/experience-manager-65.en#267]
Issue in ./help/sites-developing/hobbes.md

The test case hover and click is showing failure while running. Kindly help

**Comment by bohnertchris** [comment]
Hello, @prihr. Thank you for your issue.

This repository is for issues with AEM documentation. If you could please be more specific about what is wrong with the documentation, we will gladly correct or improve it.

If you require assistance using AEM, please reach out to our Customer Care team.

https://helpx.adobe.com/contact/enterprise-support.ec.html

Also please note that Hoobes testing is deprecated from 6.5 onwards. We recommend using Selenium for your UI testing.

**Comment by bohnertchris** [comment]
Closing due to lack of feedback. If you still feel that the documentation needs updating, please create a new issue.
