### ISSUE TITLE
The last bullet point needs clarification

### ISSUE THREAD

**Issue by ksherwoo** [AdobeDocs/experience-manager-65.en#269]
Issue in [./help/release-notes/known-issues.md](https://experienceleague.adobe.com/docs/experience-manager-65/release-notes/known-issues.html#forms)

The last bullet point needs clarification. It appears to be an unfinished statement. 

It states the following:
"When you open a PDF protected with AEM Forms Document Security on an Apple iOS or iPadOS running Adobe Acrobat Reader version 20.10.00."

So, what happens in that case? I think chances are that is does not work, but it is not really clear what is meant here.

**Comment by bohnertchris** [comment]
Thank you for reporting this, @ksherwoo. We will review.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
associated jira issue was closed
