### ISSUE TITLE
The path to slinescripting.txt file location is incorrect

### ISSUE THREAD

**Issue by vdhaliwa** [AdobeDocs/experience-manager-65.en#27]
Issue in help/sites-developing/the-basics.md

It is mentioned in this document that the list of script engines supported are listed on the Felix Management Console ( http://localhost:4502/system/console/config/slingscripting.txt )

But in 6.4 and 6.5, the above-mentioned URL shows the thread dumps.

**Comment by bohnertchris** [comment]
Thank you for pointing this out, @vdhaliwa. We will correct it.

**Comment by vdhaliwa** [comment]
The correct URL is localhost:port/system/console/slingscripting

**Comment by bohnertchris** [comment]
This was fixed with commit 31c362e.
