### ISSUE TITLE
Wrong Uber jar version for 6.5.10

### ISSUE THREAD

**Issue by muzaffarhm** [AdobeDocs/experience-manager-65.en#271]
Issue in ./help/release-notes/sp-release-notes.md

Please update the uber jar version for 6.5. SP10 to 6.5.10 as 6.5.10.0 is not available as mentioned in release notes.

**Comment by anujkapo** [comment]
I have updated the UberJar version to 6.5.10. The changes are available live now. Thanks!

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC
