### ISSUE TITLE
Salesforce Force API integration package link not working

### ISSUE THREAD

**Issue by nehmalho** [AdobeDocs/experience-manager-65.en#272]
Issue in ./help/sites-administering/salesforce.md

https://experienceleague.adobe.com/docs/experience-manager-65/administering/integration/salesforce.html?lang=en --. . Kindly ere Salesforce Force API integration package link not working. Kindly check

**Comment by aheim0** [comment]
Thanks for highlighting this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This was corrected with commit c7958efb.
