### ISSUE TITLE
Unable to download Tough Day 2

### ISSUE THREAD

**Issue by bryanledford** [AdobeDocs/experience-manager-65.en#273]
Issue in ./help/sites-developing/tough-day.md

**Comment by bohnertchris** [comment]
Thanks for reporting this, @bryanledford. We will update the link in the docs.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This has been corrected with commit fe402de to the 6.5 docs (this repo) and commit a1e1df5 to the 6.4 docs.
