### ISSUE TITLE
AEM Assets HTTP API Folder Creation via Postman

### ISSUE THREAD

**Issue by kishore94kumar** [AdobeDocs/experience-manager-65.en#274]
I have created a assets folder using HTTP API but title is not getting updated if i use a title property like mentioned in the document.

POST /api/assets/* -F"name=myfolder" -F"title=My Folder"

Instead i have to use **jcr:title**

POST /api/assets/* -F"name=myfolder" -F"**jcr:title**=My Folder"

https://github.com/AdobeDocs/experience-manager-65.en/blob/master/help/assets/mac-api-assets.md
https://experienceleague.adobe.com/docs/experience-manager-65/assets/extending/mac-api-assets.html?lang=en#create-a-folder

This issue was raised in AEM forum.

https://experienceleaguecommunities.adobe.com/t5/adobe-experience-manager/rest-api-to-create-folder-in-dam-is-not-working-as-documented/td-p/426841
 
Can anyone please validate it.

**Comment by anujkapo** [comment]
Thanks, @kishore94kumar. We will take a look.

**Comment by vishabhguptaadobe** [comment]
Updated: https://experienceleague.adobe.com/docs/experience-manager-65/assets/extending/mac-api-assets.html?lang=en#create-a-folder
