### ISSUE TITLE
Invalid link to feature pack

### ISSUE THREAD

**Issue by chclarkadobe** [AdobeDocs/experience-manager-65.en#275]
Issue in ./help/sites-deploying/data-store-config.md

Page has invalid link to Adobe Repository.  It is not clear where to get this feature pack from as it is not in Adobe Software Distribution. 

See text:- 

Download the latest version of the 1.8.x feature pack from the Adobe Repository.

**Comment by anujkapo** [comment]
Thanks, @chclarkadobe. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by raimanS** [comment]
See issue comments.
