### ISSUE TITLE
"The key meeds to be in PKCS#8 format with DER encoding." needs more information

### ISSUE THREAD

**Issue by jrickards-deloitte** [AdobeDocs/experience-manager-65.en#278]
Issue in ./help/sites-administering/saml-2-0-authenticationhandler.md

"The key meeds to be in PKCS#8 format with DER encoding."
IT would be useful if you included steps to generate the certificate with this encoding using openssl for experimenting with self signed certificates.

**Comment by sarchiz** [comment]
@jrickards-deloitte , this issue has been addressed. The new version of the docs are at: https://experienceleague.adobe.com/docs/experience-manager-65/administering/security/saml-2-0-authenticationhandler.html

Thanks again for reporting this.
