### ISSUE TITLE
Web console link is broken

### ISSUE THREAD

**Issue by vdhaliwa** [AdobeDocs/experience-manager-65.en#28]
Issue in help/sites-developing/the-basics.md

Issue in help/sites-developing/the-basics.md

The link to "Web console" redirects to https://docs.adobe.com/content/help/en/experience-manager-64/developing/sites-deploying/configuring-web-console.md which throws 404.

The correct link is https://docs.adobe.com/content/help/en/experience-manager-65/deploying/configuring/web-console.html

**Comment by bohnertchris** [comment]
Thank you for suggesting this correction, @vdhaliwa. We will get this fixed in 6.4 and 6.5.

**Comment by bohnertchris** [comment]
This was fixed with commit 31c362e.
