### ISSUE TITLE
Anyone follow these tuts? spa-walkthrough

### ISSUE THREAD

**Issue by theboman** [AdobeDocs/experience-manager-65.en#281]
Issue in ./help/sites-developing/spa-walkthrough.md
[tut page here](https://experienceleague.adobe.com/docs/experience-manager-65/developing/headless/spas/spa-walkthrough.html?lang=en)

K I am a newbie, following along already step 1 - 
I don't have this installed into AEM I have just downloaded this from github. and your article is already assuming I have this installed in my AEM. Can we write documentation assuming nothing.

I have tried running:
mvn clean install - per the readme.md file with the download, to get this error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4:enforce (enforce-maven) on project we-retail-journal: Execution enforce-maven of goal org.apache.maven.plugins:maven-enforcer-plugin:1.4:enforce failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-enforcer-plugin:1.4:enforce: java.lang.ExceptionInInitializerError: null

**Comment by bohnertchris** [comment]
Thanks for the suggestion and apologies for the delay in responding to this. The instructions should have said that the app should be installed as a package (no Maven build is needed). You are very correct that we shouldn't make and assumptions about the reader when getting started with SPA, and the docs have been updated to clearly direct the user to install the package. In addition, the WKND SPA Project is now the standard example, with We.Retail having been retired. The docs also reflect this change. Changes merged in commit baf81a6 for 6.5 and 8aae57f in AEMaaCS.
