### ISSUE TITLE
Download assets permissions

### ISSUE THREAD

**Issue by bartoszWesolowski** [AdobeDocs/experience-manager-65.en#282]
Issue in ./help/assets/download-assets-from-aem.md

I could not find any documentation around permissions that needs to be granted to a user to allow him to use Download asset feature.  I can see that the user should be a member of `dam-users` group but this group has very vide permissions (at least for our requirements) which make it hard to use in our project.  This feature works when user has read access to `/var/dam/jobs/download` - it might be helpful to put this info into the documentation

Cheers :)

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Thanks for the suggestion, @bartoszWesolowski. We will have a look.

**Comment by vishabhguptaadobe** [comment]
Updated the doc: https://experienceleague.adobe.com/docs/experience-manager-65/assets/managing/download-assets-from-aem.html
