### ISSUE TITLE
S3/Azure connector not available for download

### ISSUE THREAD

**Issue by wimsymons** [AdobeDocs/experience-manager-65.en#283]
Issue in ./help/sites-deploying/data-store-config.md

The link to both the [S3](https://repo.adobe.com/nexus/content/groups/public/com/adobe/granite/com.adobe.granite.oak.s3connector/) and the [Azure](https://repo.adobe.com/nexus/content/groups/public/com/adobe/granite/com.adobe.granite.oak.azureblobconnector/) data store connectors seems to be broken.

Both links result in the following (similar) message:

```
<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:492d93fe-001e-0029-3536-e57c48000000 Time:2021-11-29T15:31:09.8241003Z
</Message>
</Error>
```

Where can we find these? I checked the [Software Distribution](https://experience.adobe.com/#/downloads/content/software-distribution/en/aem.html) site, but only old versions are available.

See also #175, #167, #163 and #137.

**Comment by bohnertchris** [comment]
Thank you for reporting this, @wimsymons. We are investigating how to get these artifacts republished. CQDOC-18526

**Comment by wimsymons** [comment]
It's been 2 months. Any progress on this issue?

**Comment by guillaumecarlino** [comment]
The artifacts were published to the maven repo. I updated the links (will be live shortly).
