### ISSUE TITLE
Update "GraphQL API for Content Fragments" section with a NOTE for updating the naming convention in the CFM property names

### ISSUE THREAD

**Issue by jbrarAdobe** [AdobeDocs/experience-manager-65.en#285]
Issue in ./help/release-notes/previous-hotfixes-featurepacks.md

As per https://jira.corp.adobe.com/browse/CQ-4305802?focusedCommentId=23108011&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-23108011 , Hyphen is no longer allowed in the Content Fragment Model Property Field as seen in the screenshot below

Need to update "GraphQL API for Content Fragments" section with the following NOTE:

To support GraphQL API, hyphens are no longer allowed in the Content Fragment Model Property Field and it is recommended to not use hyphens in the CFM property fields going forward. GraphQL queries might return unwanted results if hyphen is present in any of the CFM property names.

Only the following characters are allowed for property name: `A-Za-z0-9_`. Digit can't be in the first position.

![Screen Shot 2021-12-02 at 1 42 07 PM](https://user-images.githubusercontent.com/54867395/144483326-6d99aa35-d47e-42b5-9d17-877fb8d7386a.png)

**Comment by jbrarAdobe** [comment]
GraphQL Docs: https://github.com/graphql/graphql-spec/blob/main/spec/Section%202%20--%20Language.md

**Comment by bohnertchris** [comment]
Thank you for reporting, @jbrarAdobe. We will investigate.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
A note has been added to the Release Notes - there was already a warning in the docu about CFModels.
Closing issue.
