### ISSUE TITLE
Export to CSV

### ISSUE THREAD

**Issue by aleroy79** [AdobeDocs/experience-manager-65.en#286]
Issue in ./help/sites-authoring/csv-export.md

Additional levels of children:
Why is this functionality limited to three levels. It offers no solution to export your full site structure.

**Comment by aheim0** [comment]
Thank you for contacting us, but unfortunately we (documentation) cannot answer questions like this, that are related to the reasonings behind the design and operation of the product. This is outside our scope.

I can ask why you are interested in exporting your full site structure. If it is for sitemap generation, then you might be interested in the new auto-generation of sitemap for SEO purposes. See:
- https://experienceleague.adobe.com/docs/experience-manager-65/release-notes/service-pack/new-features-latest-service-pack.html?lang=en
- https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/overview/seo-and-url-management.html?lang=en#building-an-xml-sitemap-on-aem

I hope this helps.

Closing this issue.
