### ISSUE TITLE
Dead link "Salesforce Force API"

### ISSUE THREAD

**Issue by etiennelyaet** [AdobeDocs/experience-manager-65.en#287]
Issue in ./help/sites-administering/salesforce.md
Hello,
The link [Salesforce Force API](https://www.adobeaemcloud.com/content/marketplace/marketplaceProxy.html?packagePath=/content/companies/public/adobe/packages/cq650/featurepack/com.adobe.cq.mcm.salesforce.content#) is dead.
Where can we find this package ?
Is this documentation applicable for AEM As A Cloud Service ?
Regards,
Étienne

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for highlighting this - the link has been updated.
Closing issue.

**Comment by etiennelyaet** [comment]
Hi @aheim0,
Thanks for looking at this issue.
I can see the link has been updated, but it now reach a 404 on the Software Distribution platform.
Moreover, when i search for this package in the Software Distribution platform, it cannot be found.
Can you have a look to it ?
Thanks,
Étienne

**Comment by aheim0** [comment]
@etiennelyaet 

Hmmm, the link works for me - but I understand that doesn't help you.

Can you try the following link:
- https://experience.adobe.com/#/downloads/content/software-distribution/en/aem.html?package=/content/software-distribution/en/details.html/content/dam/aem/public/adobe/packages/cq650/featurepack/com.adobe.cq.mcm.salesforce.content

If you can confirm whether that works I'll update the page further.

Thanks.

**Comment by etiennelyaet** [comment]
No, this link also sends me a 404.

**Comment by aheim0** [comment]
@etiennelyaet 
Can I assume that you are successfully logged in to Software Distribution?

**Comment by etiennelyaet** [comment]
Yes, I have access/can download the other resources in the Software Distribution.
Are some resources with restricted access ?

**Comment by aheim0** [comment]
@etiennelyaet 
The link for that resource is "public". I will need to investigate further.

**Comment by aheim0** [comment]
@etiennelyaet 

Several of us have now tried this and none of us have had 404 issues.

Therefore we will have to recommend that you contact Support to investigate the settings with your account.

Thanks.

**Comment by etiennelyaet** [comment]
@aheim0 
Ok, I'll check my account.
Thanks.
