### ISSUE TITLE
ToughDay 2 doc missing links

### ISSUE THREAD

**Issue by pollenshukla** [AdobeDocs/experience-manager-65.en#289]
Links are missing in ./help/sites-developing/tough-day.md

Example Usage
Known Issues

**Comment by anujkapo** [comment]
Thanks, @pollenshukla. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for highlighting this. The two items were not links, but redundant section headers. They have been removed and the page republished.
Closing issue.
