### ISSUE TITLE
Export to target without clientlibs references should be documented

### ISSUE THREAD

**Issue by himanshu-pathak** [AdobeDocs/experience-manager-65.en#29]
Issue in help/sites-administering/experience-fragments-target.md

Export of experience fragment to Target OOTB publishes the fragment with all the CSS/JS references. If the XF is used on the same site in the target activity, it often causes issues as the CSS/JS gets included twice. The tribal knowledge to handle this is to overlay the following HTL scripts to remove the clientlib references.

/libs/cq/experience-fragments/components/xfpage/head.nocloudconfigs.html
/ibs/cq/experience-fragments/components/xfpage/body.nocloudconfigs.html

 It will be helpful if this is documented officially.

**Comment by aheim0** [comment]
Hello,

Thank you for raising this issue. 

I have checked the details with the relevant department and I must confirm that this method is not currently supported, and has apparently caused several customer issues on the basis of "tribal knowledge".

However, they're very interested in improving this aspect of the product, so would be grateful if you could open a customer-related request for an improvement to the implementation.

With thanks in advance. On that basis I will close this issue.
