### ISSUE TITLE
content alignment is messed up

### ISSUE THREAD

**Issue by clstia** [AdobeDocs/experience-manager-65.en#290]
The contents of the [page](https://experienceleague.adobe.com/docs/experience-manager-65/administering/integration/adobeanalytics-mapping.html?lang=en) are currently messed up.

![Screen Shot 2022-01-05 at 10 06 20 PM](https://user-images.githubusercontent.com/10739209/148230580-e542bc25-876b-4753-8bc1-a4c7aeb89702.png)

**Comment by anujkapo** [comment]
Thanks, @clstia. We will fix it.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for highlighting this. We have checked the page and republished. It is displaying properly now (but do not hesitate to contact us if you see more issues).
Closing this issue now.
