### ISSUE TITLE
error while installing AEM plugin on eclipse 2021-12

### ISSUE THREAD

**Issue by rosemart** [AdobeDocs/experience-manager-65.en#295]
Hi, it is not possible to install teh AEM eclipse plugin in the last eclipse version, 2021-12, i always get this error. 
![error-plugin-aem-en-eclipse-2021-12](https://user-images.githubusercontent.com/52749783/152311850-97970a56-bccf-41eb-a3d4-9ce2015e6b5e.png)

it seems there is something related with the sign of the plugin, it is not signed, it seems, i have this warning when I try to install the plugin in eclipse 2021-09
![warning-plugin-aem-en-eclipse-2021-09](https://user-images.githubusercontent.com/52749783/152312393-e7354682-9855-4d62-ab1f-4016a240b728.jpg)

**Comment by anujkapo** [comment]
Hi @rosemart, is this related to AEM documentation? We receive AEM documentation bugs using this platform. Please let us know. Thanks!

**Comment by rosemart** [comment]
This is related with AEM and eclipse, last AEM plugin does not work on last eclipse version.

**Comment by aheim0** [comment]
Hello,
Apologies for the delay, but this is not directly related to the documentation, so we will have to ask you to contact Support and ask for technical assistance on this.
Thanks.
Closing ticket.
