### ISSUE TITLE
Outdated IntelliJ reference

### ISSUE THREAD

**Issue by kevin-dutra** [AdobeDocs/experience-manager-65.en#297]
Issue in ./help/sites-developing/dev-tools.md

There is an "AEM IntelliJ Extension" reference on the "Development Tools" page that is not viable. That project ceased development in January of 2021 and there is not a version that is compatible with the versions of IntelliJ currently available.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for highlighting this - the reference has been removed and the update will be published soon.
Closing issue.
