### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by jbaix** [AdobeDocs/experience-manager-65.en#298]
Issue in ./help/sites-developing/querybuilder-api.md
The link in this paragraph does not work:

See the AEM Gem session [Search forms made easy with the AEM querybuilder](https://helpx.adobe.com/experience-manager/kt/eseminars/gems/aem-search-forms-using-querybuilder.html) for a detailed overview of the query builder

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for raising this - the link has been updated.
Closing this issue.
