### ISSUE TITLE
Incorrect images

### ISSUE THREAD

**Issue by bstopp** [AdobeDocs/experience-manager-65.en#3]
Issue in help/sites-administering/curl.md

None of the images on this page appear to be correct for this page.

**Comment by bohnertchris** [comment]
Thanks for reporting this, @bstopp. This appears to be an issue resulting from our content migration to the new platform. We will address this shortly.

SSECD-632

**Comment by bohnertchris** [comment]
This has been fixed and the updated pages are now published.
