### ISSUE TITLE
Clarify 'latin characters'

### ISSUE THREAD

**Issue by techandsoftware** [AdobeDocs/experience-manager-65.en#300]
Issue in ./help/assets/content-fragments/content-fragments-models.md

> When manually updating this property for a data type, note that names must contain only Latin characters, numerical digits and underscore “_” as special character.

Is 'Latin characters' referring to Latin characters in the ASCII code range?   Presumambly not characters like é

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for raising this - the specification has been clarified.
Closing issue now.
