### ISSUE TITLE
Recommendation for Bulk Editing Content in 6.5 

### ISSUE THREAD

**Issue by kalva2290** [AdobeDocs/experience-manager-65.en#303]
Issue in ./help/sites-administering/bulk-editor.md

> With the [deprecation of the Classic UI](https://experienceleague.adobe.com/docs/experience-manager-65/release-notes/deprecated-removed-features.html?lang=en) in AEM 6.4, the Bulk Editor has also been deprecated and thus Adobe does not plan to further enhance the Bulk Editor.

Is there a recommended approach to bulk editing content or is this just not support functionality and will require custom development? Is there anything coming soon? This statement in the docs feels like a dead end.

**Comment by aheim0** [comment]
Thank you for raising this. 

However, most of your questions are not directly related to the documentation, so we would recommend that you contact Customer Care.

Closing this issue.
