### ISSUE TITLE
CF model inside sub sites are not available while allowing CF on asset folder properties

### ISSUE THREAD

**Issue by chandeshj** [AdobeDocs/experience-manager-65.en#304]
CF models inside sub sites are not available to apply on asset folder properties : we faced issue with client fragment model where we have configured subsites(Sub1 and sub2) inside site(training) and in each of the site and subsite we created content fragment models (cf1,cf2,cf3 inside training and cf4 inside sub1 and cf5 inside sub2).

but while creating cf inside sub1 or sub2......we cant get the CF model inside them..... we can only see cf model from parent conf not able to see and cf model from children ..... any thoughts/suggestion?

**Comment by bohnertchris** [comment]
Hello @chandeshj and thank you for the issue. This is the repository For AEM 6.5 documentation. If you have a suggestion on how to improve the docs or would like to report an error, we encourage it. If you are looking for support on how to use the product, please contact our Customer Care team. https://experienceleague.adobe.com/?support-solution=Experience+Manager#home

**Comment by bohnertchris** [comment]
Closing this issue since there has been no response in three weeks. If there is still a documentation problem, we will welcome a new issue.
