### ISSUE TITLE
Change SDL to RWS on page

### ISSUE THREAD

**Issue by nwatson-cloud** [AdobeDocs/experience-manager-65.en#307]
Hi
Please change on this page, https://experienceleague.adobe.com/docs/experience-manager-65/administering/introduction/tc-tic.html?lang=en#connecting-to-a-translation-service-provider
SDL to RWS and use the link below to the App Marketplace is here: https://partners.adobe.com/exchangeprogram/experiencecloud/exchange.details.108277.html
SDL were acquired by RWS
thanks
Nige
![Screenshot 2022-03-22 093813](https://user-images.githubusercontent.com/92025380/159961279-7707e4a6-fc7c-419f-8e93-ebf1e693fcec.jpg)
l

**Comment by bohnertchris** [comment]
Thank you for the issue, @nwatson-cloud. We will review.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC
