### ISSUE TITLE
Some of the links are not valid and some have old JSP codes

### ISSUE THREAD

**Issue by veenavikraman** [AdobeDocs/experience-manager-65.en#308]
Issue in ./help/sites-developing/code-samples.md 

e.g https://blogs.adobe.com/aemtutorials/ - This is not available anymore 
https://www.hsufengko.com/home/cq5-code-samples - This takes you to an old 2013 blog which is written in JSPs

**Comment by bohnertchris** [comment]
Thank you for reporting this, @veenavikraman. We will review.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This was corrected with commit d7871ab.
