### ISSUE TITLE
Broken SAML Example Link

### ISSUE THREAD

**Issue by bryanledford** [AdobeDocs/experience-manager-65.en#309]
Issue in ./help/sites-administering/saml-2-0-authenticationhandler.md

Please fix link to https://helpx.adobe.com/experience-manager/kb/simple-saml-demo.html - currently goes to 404 page and having a working example would be extremely valuable. Thank you.

**Comment by bohnertchris** [comment]
Thanks for reporting this problem, @bryanledford. We will fix it.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
Fixed with CQDOC-19150.
