### ISSUE TITLE
Update Technical Requirement page to add more details about windows server

### ISSUE THREAD

**Issue by jbrarAdobe** [AdobeDocs/experience-manager-65.en#31]
Issue in help/sites-deploying/technical-requirements.md

Under the "Server Operating Systems", Details about windows operating system is not very clear.  We had a support case(205243) where AEM was not working intermittently on Windows 2019. 

In my opinion, we need to add a note(After confirming with Engineering team):

Running AEM on windows is not fully tested and might not work properly.

**Comment by bohnertchris** [comment]
Thanks @jbrarAdobe for reporting this issue. However I think that the current state of the documentation is very clear on the restrictions around using Windows servers.

If you feel that additional information is needed, please create a new issue.
