### ISSUE TITLE
Link redirects back to referring page

### ISSUE THREAD

**Issue by vcohen-irvinecompany** [AdobeDocs/experience-manager-65.en#310]
Issue in ./help/sites-developing/querybuilder-api.md

The link in the first Note redirects back to this very page:

> The QueryBuilder API is built using the JCR API. You can also query the Adobe Experience Manager JCR by using the JCR API from within an OSGi bundle. For information, see [Querying Adobe Experience Manager Data using the JCR API](https://helpx.adobe.com/experience-manager/using/querying-experience-manager-data-using1.html).

**Comment by anujkapo** [comment]
Thanks, @vcohen-irvinecompany. We will fix it.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
Fixed in CQDOC-19178.
