### ISSUE TITLE
Link redirects to a generic home page

### ISSUE THREAD

**Issue by vcohen-irvinecompany** [AdobeDocs/experience-manager-65.en#311]
Issue in ./help/sites-developing/querybuilder-api.md

The 2nd Note on the page contains a link that gets redirected to https://experienceleague.adobe.com/#home

> NOTE
> See the AEM Gem session [Search forms made easy with the AEM querybuilder](https://helpx.adobe.com/experience-manager/kt/eseminars/gems/aem-search-forms-using-querybuilder.html) for a detailed overview of the query builder.

**Comment by anujkapo** [comment]
Thanks, @vcohen-irvinecompany. We will fix it.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for raising this - the link has been updated.
Closing this issue.
