### ISSUE TITLE
 Broken link on Best Practices for Queries and Indexing

### ISSUE THREAD

**Issue by nhirrle** [AdobeDocs/experience-manager-65.en#312]
There is a broken link on https://experienceleague.adobe.com/docs/experience-manager-65/deploying/practices/best-practices-for-queries-and-indexing.html?lang=en

`While taking the integrated Solr search approach would allow for offloading of indexing to a Solr server. If the more advanced features of the Solr server are used through a crawler based approach, additional configuration work will be required. Headwire has created an [open source connector](https://www.aemsolrsearch.com/#/) to accelerate these types of implementations.`

https://www.aemsolrsearch.com/#/ is dead and I guess this anyhow outdated.

**Comment by anujkapo** [comment]
Thanks, @nhirrle. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
This was fixed in CQDOC-19181.
