### ISSUE TITLE
Issue with link https://repo.adobe.com/nexus/content/groups/public/com/adobe/granite/crx2oak/

### ISSUE THREAD

**Issue by Lexieyw** [AdobeDocs/experience-manager-65.en#315]
Issue in ./help/sites-deploying/using-crx2oak.md

Hi Team, 

Can you fix the link for https://repo.adobe.com/nexus/content/groups/public/com/adobe/granite/crx2oak/ please? 
A customer has noticed this link doesn't work. 

Regards,

Yuyu Wang

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
This is fixed.
