### ISSUE TITLE
outdated information

### ISSUE THREAD

**Issue by vinukm** [AdobeDocs/experience-manager-65.en#316]
Issue in ./help/sites-administering/target-configuring.md
Section: Creating a Target Cloud Configuration
on 6.5.12.0, the new config dialog looks like 
![image](https://user-images.githubusercontent.com/25636684/162209373-db8b96c5-3c81-497c-9080-2694ff09b099.png)
the documentation needs an update accordingly

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thank you for raising this - but the documentation is correct. The dialog is dependent on the Authentication selected and as your screenshot uses User Credentials - which are deprecated. We document the current configuration, which is IMS.
However, when checking this we have seen that the option is now in a different location in the Tools menu. We have updated this and the changes will be published soon.
Closing this issue.
