### ISSUE TITLE
Wrong Dialog Screenshots attached

### ISSUE THREAD

**Issue by rahuldhingra** [AdobeDocs/experience-manager-65.en#317]
Issue in ./help/sites-administering/target-configuring.md

Attached screenshot of dialog in 6.5.12 
![image](https://user-images.githubusercontent.com/35455692/162382619-0ad260cc-b81c-40b8-9652-05a222d56fdc.png)

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
Will be live shortly.
