### ISSUE TITLE
ImageMagick environment variable name is wrong

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-65.en#319]
Issue in ./help/assets/performance-tuning-guidelines.md

The ImageMagick environment variable is "MAGICK_TEMPORARY_PATH", not "MAGIC_TEMPORARY_PATH".
Everything related to "ImageMagick" spells the word MAGICK with a C and a K.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This was fixed with commit 35639a8.
