### ISSUE TITLE
Publishing Tags details should be updated

### ISSUE THREAD

**Issue by lha-adobe** [AdobeDocs/experience-manager-65.en#32]
Issue in help/sites-administering/tags.md

Document does not mention that Asset Publishing will also publish Tag reference changes
e.g. Asset has a new tag, publishing this asset will publish the new tag as well
Author has deleted a tag, Asset (with reference to deleted tag) should also trigger Publish to delete the referenced tag

See Adobe internal JIRAs : CQ-4269305,NPR-31180 -- the title is not exactly what is expected, however, I have tested on 6.5.3.0 vanilla author and publish and could confirm the Tag reference was updated --  see Daycare ticket https://daycare.day.com/home/microsoftcorporation/microsoftcorporation_us/managedservicessites/206768.html
{{Logged by Support}}

**Comment by guillaumecarlino** [comment]
I think this is already covered in the assets specific documentation.
