### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by gregcox-adobe** [AdobeDocs/experience-manager-65.en#320]
Issue in ./help/sites-deploying/data-store-config.md

The "Adobe Repository" Link under "Upgrading to a new version of the 1.10.x S3 Connector" Step 4 is broken. Please fix.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Thank you for reporting this, @gregcox-adobe. Indeed that server was decommissioned and we are working to restore such links.

**Comment by bohnertchris** [comment]
This has been fixed with commit 43b22e0.
