### ISSUE TITLE
Page is not readable

### ISSUE THREAD

**Issue by karthikreddii** [AdobeDocs/experience-manager-65.en#321]
Issue in ./help/sites-classic-ui-authoring/classic-personalization-campaigns-setting-up-your.md

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Thank you for reporting this, @karthikreddii. We will fix it.

**Comment by guillaumecarlino** [comment]
Fixed.
