### ISSUE TITLE
Page styling issue

### ISSUE THREAD

**Issue by chintan97** [AdobeDocs/experience-manager-65.en#322]
Issue in ./help/sites-developing/developing-forms.md

The page styles are messed up: https://experienceleague.adobe.com/docs/experience-manager-65/developing/components/classic-ui-components/developing-forms.html?lang=en

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Thanks for reporting this, @chintan97. We will fix it.

**Comment by bohnertchris** [comment]
This was corrected with commit 8200b91.
