### ISSUE TITLE
Unclear recommendation

### ISSUE THREAD

**Issue by vcohen-irvinecompany** [AdobeDocs/experience-manager-65.en#323]
Issue in ./help/sites-administering/security.md

In the administrators group row in the Built-in Users and Groups table, 
> If you set a 'deny-everyone' on a node, the administrators will only have access if it is enabled again for that group.

What does "it" refer to here? What needs to be re-enabled? Is it's 'deny-everyone' on the node, that's already set. Do you mean 'deny-everyone' needs to be unset? Please clarify.

**Comment by anujkapo** [comment]
Thanks, @vcohen-irvinecompany. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thank you for raising this. The page has been updated and the issue no longer exists.
Closing this issue.
