### ISSUE TITLE
Incorrect information in "Upgrading to a new version of the 1.10.x S3 Connector" section

### ISSUE THREAD

**Issue by thedoc31** [AdobeDocs/experience-manager-65.en#325]
Issue in ./help/sites-deploying/data-store-config.md

AEM 6.5 uses S3 connector 1.10.x, not 1.8.x so the text here is incorrect. 

Also, the Software Distribution link sends you to an old location with an outdated download that will break AEM. This needs to be updated to the same link as above "Adobe Repository" which points to maven.org instead.

Created PR #324 to resolve. Please merge.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This was corrected with commit 9d8387.
