### ISSUE TITLE
Revision Cleanup is not responsive / optimized for mobile

### ISSUE THREAD

**Issue by nhirrle** [AdobeDocs/experience-manager-65.en#326]
Revision Cleanup Page is not responsive / optimized for mobile. https://experienceleague.adobe.com/docs/experience-manager-65/deploying/deploying/revision-cleanup.html?lang=en
Especially the table at the bottom is almost impossible to read on a smaller device. See also screenshot 
![Screenshot_20220508-150539](https://user-images.githubusercontent.com/46745410/167297574-5b9598bf-acda-46a0-9afb-36c0781ecef3.jpg)

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by raimanS** [comment]
See Jira issue comment.
