### ISSUE TITLE
HMAC key replication

### ISSUE THREAD

**Issue by sarthak-kakkar** [AdobeDocs/experience-manager-65.en#327]
Issue in ./help/sites-developing/csrf-protection.md

Considering the HMAC key has been moved from [JCR to the file system](https://experienceleague.adobe.com/docs/experience-manager-65/administering/security/encapsulated-token.html?lang=en), the content under the heading `Replicating the Crypto Key` needs to be [updated](https://user-images.githubusercontent.com/68348076/167379866-b6510565-14c9-4db6-b40b-ac1ba23190bc.png) on `./help/sites-developing/csrf-protection.md` page.

As an addition, please correct me if I'm wrong, think the content under `Replicating the HMAC key` on [page](https://experienceleague.adobe.com/docs/experience-manager-65/administering/security/encapsulated-token.html?lang=en) possibly also needs to be [updated](https://user-images.githubusercontent.com/68348076/167383178-6dcfff99-deb2-4346-94e4-c6dad8e60307.png).

Screenshots added for reference.

<img width="839" alt="image" src="https://user-images.githubusercontent.com/68348076/167379866-b6510565-14c9-4db6-b40b-ac1ba23190bc.png">

<img width="848" alt="image" src="https://user-images.githubusercontent.com/68348076/167383178-6dcfff99-deb2-4346-94e4-c6dad8e60307.png">

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for highlighting this. Updates have been made and will be published soon.
Closing this issue.
