### ISSUE TITLE
This SameSite=None setting only works if protocol is secure (HTTPS)

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-65.en#328]
Issue in ./help/sites-administering/same-site-cookie-support.md

Please add a note that the "SameSite=None" setting is applied only if the protocol is secure (HTTPS). If the protocol is not secure (HTTP), then the setting is ignored and the server will show this WARN message:

`*WARN* com.day.crx.security.token.TokenCookie Skip 'SameSite=None' since the connection is not secure`

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
The note has been added - thanks for your contribution.
Closing this issue.
