### ISSUE TITLE
Image component link gives a 404

### ISSUE THREAD

**Issue by swaroop61** [AdobeDocs/experience-manager-65.en#330]
Issue in ./help/assets/use-assets-across-connected-assets-instances.md

The link below throws a 404 error

Image formats: The formats that the [Image component](https://www.aemcomponents.dev/content/core-components-examples/library/page-authoring/image.html) supports.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This was fixed with commit e486e53.
