### ISSUE TITLE
sling:internalRedirect type is multi-value, no single-value

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-65.en#331]
Issue in ./help/sites-deploying/resource-mapping.md

"sling:internalRedirect" type is a multi-value String, not a single-value String
Type should be shown as "String[]" not "String".

See examples at https://sling.apache.org/documentation/the-sling-engine/mappings-for-resource-resolution.html

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for highlighting this - the change has been applied.
Closing this issue.
