### ISSUE TITLE
Unclear format for mapping submitted data

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-65.en#332]
Issue in ./help/forms/using/configuring-submit-actions.md
I find the section on "Post submitted data to a resource or external rest end point" a little unclear. I'm not clear what format the parameters should be configured. When you say textbox=param1, is textbox the name of the field on the form and param1 the name of the parameter which is going to be submitted to REST? Or is it the other way around?  It would be helpful if you included maybe an example of the URL equivalent of what someone is trying to submit, and then specifically state which one is the name of the item on the form.

**Comment by aheim0** [comment]
Thanks for raising this - we will review.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
Closing. See  CQDOC-19347  for details.
