### ISSUE TITLE
Spring4Shell hotfix not included in the SP13 release notes

### ISSUE THREAD

**Issue by dcreaadobe** [AdobeDocs/experience-manager-65.en#337]
Hi team,
we are receiving many questions about Spring4Shell security patch included in SP13 but this is not listed in the release notes.

As per 
https://jira.corp.adobe.com/browse/ASSETS-9031
it should be. Is it possible to add this information for transparency towards our customers?

Thank you.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Security related issues are not documented as part of our standard release notes, but rather assigned CVE numbers as necessary by the PSIRT team and published in the quarterly security bulletins.

https://helpx.adobe.com/security.html
