### ISSUE TITLE
Broken recording link pointing to helpx.adobe.com

### ISSUE THREAD

**Issue by iaramsay** [AdobeDocs/experience-manager-65.en#338]
Issue in ./help/sites-developing/tough-day.md

Hi there, 
On this page there is a reference to You can watch [this recording](https://helpx.adobe.com/experience-manager/kt/eseminars/gems/aem-toughday2-stress-testing-benchmarking-tool.html) for a presentation of the application. However, this page 

https://helpx.adobe.com/experience-manager/kt/eseminars/gems/aem-toughday2-stress-testing-benchmarking-tool.html

reroutes to this

https://experienceleague.adobe.com/#home

The correct link I believe, thank you google, is this

https://experienceleague.adobe.com/docs/experience-manager-gems-events/gems/gems2017/aem-toughday2-stress-testing-benchmarking-tool.html?lang=en

cc
@bcsott

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by raimanS** [comment]
Reference updated.
