### ISSUE TITLE
Unnecessary Repository migration

### ISSUE THREAD

**Issue by svenux** [AdobeDocs/experience-manager-65.en#346]
Issue in ./help/sites-deploying/app-server-upgrade.md
The documentation describes a repository migration when upgrading from AEM 6.4 to AEM 6.5.
For me it looks like this procedure is not necessary because nothing has changed in Segment Tar that requires a migration.

**Comment by anujkapo** [comment]
Thanks, @svenux. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by sarchiz** [comment]
@svenux, this documentation has been provided by our ENG and QE teams at the time. I'd reckon venturing a guess that it's needed for some changes at a level higher than persistence, but there is definitely a reason why it should still be there. Please contact the ENG team for more info - I am closing this issue in the meantime. If there are any updates to this, please open a new one. Thanks!
