### ISSUE TITLE
Broken Link "a demonstration of AEM and SAML integration."

### ISSUE THREAD

**Issue by picturedesk** [AdobeDocs/experience-manager-65.en#348]
Issue in ./help/sites-administering/saml-2-0-authenticationhandler.md

The link "a demonstration of AEM and SAML integration" in the first NOTE box is broken.

Somehow the second link in the first box "Integrating SAML with Adobe Experience Manager" is redericting to it self.

**Comment by jon34420** [comment]
@picturedesk, thank you for your feedback. This is being reviewed and tracked in G11N-10063

**Comment by aheim0** [comment]
Tracked in G11N-10063,, which is outside our scope, so closing issue.
