### ISSUE TITLE
Missing explanation for "translate component strings"

### ISSUE THREAD

**Issue by RyanADBE** [AdobeDocs/experience-manager-65.en#349]
Issue in ./help/sites-administering/tc-tic.md 

The screenshot under the section "Creating a Translation Integration Configuration" shows a checkbox for "translate component strings" but there's no explanation as to what this does when toggled on/off.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC
