### ISSUE TITLE
Details regarding required permissions/group missing

### ISSUE THREAD

**Issue by lha-adobe** [AdobeDocs/experience-manager-65.en#35]
Issue in help/sites-authoring/editing-page-properties.md

Regarding this section
> Personalization
> ...........
> Targeting Configuration
> Select a Brand to specify a scope for Targeting .

Targeting Configuration requires the user to be in Target-Administrators group, or else there would be JavaScript error and the UI will not work as intended.

Reference https://daycare.day.com/home/healthpartnerscom/healthpartnerscom_us/customer_services/206923.html

{{Logged by Support}}

**Comment by aheim0** [comment]
Thank you for raising this to our attention. A note has been added to this effect on applicable documentation sets. The updates are now published.
