### ISSUE TITLE
The Identity Provider POST URL.

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-65.en#350]
Issue in ./help/sites-administering/saml-2-0-authenticationhandler.md

In the section:
The SAML 2.0 Authentication Handler is disabled by default. You must set at least one of the following properties in order to enable the handler:

The Identity Provider POST URL.
The Service Provider Entity ID.

"The Identity Provider POST URL" parameter does not exist. There is one for "IDP URL", but these names should match up if that is the parameter you are talking about to eliminate any ambiguity.

**Comment by bohnertchris** [comment]
Thanks for the suggestion, @alisonasanchez. We will review.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This was resolved via commit d8f79ae.
