### ISSUE TITLE
there are two links not migriated correctly in the Note section, need author to fix them

### ISSUE THREAD

**Issue by yanlicao** [AdobeDocs/experience-manager-65.en#352]
Issue in ./help/sites-administering/saml-2-0-authenticationhandler.md

[!NOTE]

    See [a demonstration of AEM and SAML integration](https://helpx.adobe.com/experience-manager/kb/simple-saml-demo.html).

    To read an end to end community article, click: [Integrating SAML with Adobe Experience Manager](https://helpx.adobe.com/experience-manager/using/aem63_saml.html).

first link is broken
second link goes back to this page itself, so not correct either, can you fix both links?

**Comment by aheim0** [comment]
Thanks for highlighting this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by yanlicao** [comment]
first link is now working fine , waiting for fixing for 2nd link

**Comment by bohnertchris** [comment]
The second link was removed due to it being out of date.
