### ISSUE TITLE
Missing a space

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-65.en#353]
Issue in ./help/forms/using/document-security-offerings.md
Missing a space in the below sentence:
Adobe Acrobat: You can use Adobe Acrobat to apply security policy to PDF documents **createdusing** popular desktop applications, such as Microsoft Office, web browsers, or any application that supports printing in PDF format.

**Comment by aheim0** [comment]
Thanks for highlighting this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
Thanks for reporting, I fixed it.
