### ISSUE TITLE
Contributor Group definition needs to be updated

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-65.en#356]
Issue in ./help/sites-administering/security.md

This text doesn't really make sense:
"Basic privileges which allow the user to write content (as in functionality only).Does not allocate any privileges to the /content tree - these must be specifically allocated for the individual groups or users."

I'm not really sure how you have access to write content but not have any privileges to the /content tree. And I'm not sure what (as in functionality only) means. This could be more clear but I'm not sure how to make it more clear since I was trying to use the doc to get a better understanding, and didn't really succeed.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
The documentation is accurate, but have added a few words for extra clarification. Hope that helps.
Will be published soon.
Closing issue.
