### ISSUE TITLE
Inconsistent statement for metadata writeback

### ISSUE THREAD

**Issue by bartoszWesolowski** [AdobeDocs/experience-manager-65.en#359]
Issue in ./help/assets/xmp-writeback.md

Sentence `The feature writes back only those metadata properties that use jcr namespace, that is, a property named dc:title is written back but a property named mytitle is not.` is a bit confusing.

I am not sure whether only properties from `jcr` namespace is written back and there is a typo in `dc:title` (it should be `jcr:title` instead) or maybe both `jcr` and `dc` namespaces are supported. Could you please clarify?

**Comment by aheim0** [comment]
Thanks for highlighting this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by AmyJZhao** [comment]
@adobe export issue to Jira project CQDOC

**Comment by AmyJZhao** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
https://github.com/adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
https://github.com/adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by AmyJZhao** [comment]
@adobe export issue to Jira project CQDOC

**Comment by AmyJZhao** [comment]
@adobe export issue to Jira project CQDOC

**Comment by AmyJZhao** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Apologies for all of the noise on this issue, @bartoszWesolowski. We were having trouble with our issue tracking system. This issue is now tracked and we will review.

**Comment by bartoszWesolowski** [comment]
@bohnertchris no problem - thanks for your help here ;)

**Comment by kkour06** [comment]
The [issue](https://jira.corp.adobe.com/browse/CQDOC-19626) is closed and is pushed live at
https://experienceleague.adobe.com/docs/experience-manager-65/assets/administer/xmp-writeback.html
