### ISSUE TITLE
Missing tag

### ISSUE THREAD

**Issue by manbeneat** [AdobeDocs/experience-manager-65.en#36]
Issue in help/sites-administering/campaignstandard.md, it seems like there is a missing !UICONTROL or bold tag here: From the authoring instance, select AEM logo > **Tools **icon > Deployment > Replication > Agents on author , then click Default Agent .

**Comment by aheim0** [comment]
Thanks for highlighting this. We have corrected the formatting and published the updates.
Will now close this issue.
