### ISSUE TITLE
grammer

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-65.en#360]
Issue in ./help/sites-administering/external-link-checker.md

This sentence:
The Link Checker runs automatically assist content authors with their links including:

has grammatical errors. I think they might mean this:
The Link Checker runs automatically to assist content authors with their links including:

Note: Covers 1 issue and 1 PR
* https://github.com/AdobeDocs/experience-manager-65.en/issues/360 
* https://github.com/AdobeDocs/experience-manager-65.en/pull/361

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
Thanks, I fixed it.
