### ISSUE TITLE
Example POST and PUT body for CFM creation

### ISSUE THREAD

**Issue by pat-lego** [AdobeDocs/experience-manager-65.en#362]
Issue in ./help/assets/assets-api-content-fragments.md

Can we have an example POST body and PUT body for a content fragment model Assets API post in order to know how to create them using the REST protocol

**Comment by aheim0** [comment]
The reference materials:
- https://developer.adobe.com/experience-manager/reference-materials/cloud-service/javadoc/assets-api-content-fragments/index.html#/ 
Has sections for POST and PUT, which can be expanded to show the body.
Hope that helps - if you need more information, please open a new issue.
