### ISSUE TITLE
Refers to classic UI which is now essentially hidden

### ISSUE THREAD

**Issue by mattlaun** [AdobeDocs/experience-manager-65.en#366]
Issue in ./help/sites-deploying/monitoring-and-maintaining.md
This page for 6.5 still refers to accessing the purge tool through classic UI. Users won't find the tool following the instruction to go to Tools > Versioning.

**Comment by anujkapo** [comment]
Thanks, @mattlaun for pointing this out. We will fix it.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for highlighting this - we have made updates and published the page.
Closing issue now.
