### ISSUE TITLE
Bulk Editing Multi-Value Properties (like tags) is incorrectly described

### ISSUE THREAD

**Issue by dtbayer** [AdobeDocs/experience-manager-65.en#367]
Issue in ./help/sites-authoring/editing-page-properties.md

At the bottom of the section "From the Sites Console - Multiple Pages", there is text that suggests that <Mixed Entries> are able to be bulk-edited(though care should be taken)

> Fields that are common, but have different values across the various pages will be indicated with a special value such as the text <Mixed Entries>. Care should be taken when editing such fields to prevent data loss.

I spoke with AEM Support Engineer Bhaven Mehta, and it turns out that Bulk Editing for multi-value "<Mixed Entries>" is actually not available yet, and the documentation needs to be revised

**Comment by anujkapo** [comment]
Thanks @dtbayer. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for raising this - after confirmation the documentation has been updated.
Closing this issue.
