### ISSUE TITLE
broken link - Adobe IMS Authentication and Admin Console Support for AEM Managed Services

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-65.en#372]
Issue in ./help/sites-administering/ims-config-and-admin-console.md
The link to [https://github.com/adobe-apiplatform/user-sync.py/blob/v2/docs/en/user-manual/advanced_configuration](https://github.com/adobe-apiplatform/user-sync.py/blob/v2/docs/en/user-manual/advanced_configuration.md#additional-group-options) is broken.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for raising this - the link has been replaced and will be published soon.
Closing issue.
