### ISSUE TITLE
Document max number of assets per node

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-65.en#373]
Issue in ./help/assets/performance-tuning-guidelines.md
We need to document the recommended maximum number of assets per node. Obviously, a million assets in a node/folder is not going to be good for performance. Need a best practice definition here.

**Comment by aheim0** [comment]
Thanks for asking this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by anujkapo** [comment]
The updates are already available here:
https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/assets/manage/add-assets.html?lang=en#tips-limitations
