### ISSUE TITLE
404 link for Data Store documentation 

### ISSUE THREAD

**Issue by bartoszWesolowski** [AdobeDocs/experience-manager-65.en#374]
Issue in ./help/sites-deploying/data-store-config.md

In `File Data Store` section link to https://jackrabbit.apache.org/api/2.8/org/apache/jackrabbit/core/data/FileDataStore.html points to 404 page.

**Comment by anujkapo** [comment]
Thanks @bartoszWesolowski. We will fix it.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bartoszWesolowski** [comment]
thanks @bohnertchris :)
