### ISSUE TITLE
Documentation extension for startup / init parameters available for AEM

### ISSUE THREAD

**Issue by bartoszWesolowski** [AdobeDocs/experience-manager-65.en#377]
Issue in ./help/sites-administering/security-checklist.md

Hello, 

I am reading documentation on crypto support and I found out that there is a parameter that can be used to change how keys are stored in AEM: `-Dcom.adobe.granite.crypto.file.disable=true`

This option is mention only in security-checklist (or I can not find it anywhere else). Maybe it would be worth to mention this in page that is covering crypto support (https://experienceleague.adobe.com/docs/experience-manager-65/administering/security/encryption-support-for-configuration-properties.html?lang=en)?

Additionally it would be useful to have a page that lists all parameters that can change how AEM works upon first installation (I could not find that kind of documentation either).

**Comment by anujkapo** [comment]
Thanks, @bartoszWesolowski. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by sarchiz** [comment]
Thanks for raising this @bartoszWesolowski . We've removed the note from the Security Checklist altogether, since Adobe does not encourage storing keys in the repository.
