### ISSUE TITLE
Revision Cleanup page needs updating

### ISSUE THREAD

**Issue by thedoc31** [AdobeDocs/experience-manager-65.en#379]
I submitted PR #378 to address a few spots where the page description still refers to AEM 6.3 instead of 6.5, and clarifying later in the docs that these items apply to 6.3 **and higher** versions.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for highlighting this - the changes have been applied and will be published soon.
Closing this now.
