### ISSUE TITLE
Template Types

### ISSUE THREAD

**Issue by girishadobe** [AdobeDocs/experience-manager-65.en#380]
Issue in ./help/sites-developing/page-templates-editable.md

In the section creating template types, point 4 is not clear
In the copy of the template that is under the template-types node, delete all cq:template and cq:templateType jcr:content properties.
Can someone please clarify what needs to be deleted here

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for highlighting this. Changes have been made and will be published soon.
Closing this issue.
