### ISSUE TITLE
Unclear documentation around CSRF configuration for dispatcher

### ISSUE THREAD

**Issue by bartoszWesolowski** [AdobeDocs/experience-manager-65.en#381]
Issue in ./help/sites-developing/csrf-protection.md

Hello,

I can see, in the docs that in order to use CSRF tokens dispatcher configuration needs to be adjusted but unfortunately in the linked documentation page there CSRF is not mention. I imagine that it mostly requires whitelisting CSRF token endpoint and disable caching for it but it would be great to either:
- updated linked documentation with CSRF token section here: https://experienceleague.adobe.com/docs/experience-manager-dispatcher/using/dispatcher.html?lang=en or
- update this page and include necessary config changes

**Comment by TylerRush** [comment]
@adobe export issue to Jira project CDQDOC.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CDQDOC

**Comment by bohnertchris** [comment]
https://github.com/adobe export issue to Jira project CQDOC.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Apologies for the delay, and thanks for raising this. Updates have been made and will be published soon.
Closing issue now.
