### ISSUE TITLE
JAVA LTS version support

### ISSUE THREAD

**Issue by tnetake** [AdobeDocs/experience-manager-65.en#382]
Issue in ./help/sites-deploying/technical-requirements.md

Hi Team, 

The JAVA version mentioned in the documentation is Oracle Java SE 11 JDK - 64-bit, but as per oracle documentation[1], the current LTS version is JAVA 17 . Could you please update the documentation to add JAVA 17 in supported list ? 

[1] https://www.oracle.com/java/technologies/java-se-support-roadmap.html

Thanks,
Tushar

**Comment by TylerRush** [comment]
@tnetake thanks for raising this issue. We will investigate and let you know when we have an update.

**Comment by TylerRush** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
@tnetake 
Please see the comments on CQDOC-19987. Thank you.
Closing this issue now.
