### ISSUE TITLE
variation options

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-65.en#388]
Issue in ./help/sites-authoring/experience-fragments.md

this needs more details on what the different options mean:
Create allows you to create:

Variation
Variation as live-copy.

What does each option give you, what do you gain by selecting one over the other.

**Comment by bohnertchris** [comment]
Thanks for reporting the issue, @alisonasanchez. We will review.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for the feedback. A cross-reference to the Live Copy documentation has been added. Will be published soon.
Closing this issue.
