### ISSUE TITLE
9. Unique Sling ID -  browse to https://

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-65.en#39]
Issue in help/sites-administering/sync.md

In point 9. Unique Sling ID, the browse to **https://** should be something like this:
**http://<host>:<port>/system/console/status-slingsettings**

[Logged by AEM Support]

**Comment by sukohli** [comment]
Sorry.. instead of **https://** 
it should be
**http://<host>:<port>/system/console/status-slingsettings**

**Comment by sukohli** [comment]
Sorry.. instead of _https://_ 
it should be
_http://host:port/system/console/status-slingsettings_

**Comment by bohnertchris** [comment]
Thank you for reporting this, @sukohli . Looks like this link was malformed during our content migration to the new platform. We will fix it. CQDOC-15589

**Comment by bohnertchris** [comment]
This has been fixed via commit e513fe0 in this repo as well as via commit 6758a93 in the experience-manager-64.en repo.
