### ISSUE TITLE
Incoming Links Updates

### ISSUE THREAD

**Issue by tnetake** [AdobeDocs/experience-manager-65.en#391]
Issue in ./help/sites-authoring/author-environment-tools.md

Hi Team, 

Below is documented for "Incoming Links" in "References" section, Incoming links also showing references of pages where this specific page is referred in URL in hierarchy. E.g.  for http://localhost:4502/sites.html/content/we-retail/us/en/community page, it's showing 3 incoming links but one of incoming link page e.g. http://localhost:4502/editor.html/content/we-retail/us/en/community/members.html  community page is referred on URL hierarchy and community.html page is not referred directly on the members.html. 

Could you please add details in the Incoming Links for this implementation. 

`Incoming Links, provides a list of pages that reference the page, together with direct access to Edit one of those pages when you select a specific link`

**Comment by anujkapo** [comment]
Thanks, @tnetake. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
This has been fixed.
Closing issue.
