### ISSUE TITLE
Metadata and Last Modified Date

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-65.en#392]
Issue in ./help/assets/metadata.md
Can you add a section here about editing metadata and it's affect on last modified date? I see that the cloud assets doc (https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/assets/manage/manage-metadata.html?lang=en#last-modification) has a section, but I don't see something similar for non-cloud, and I'm not sure if it's the same.
Thanks,
Alison

**Comment by anujkapo** [comment]
Thanks, @alisonasanchez. We will fix it.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by kkour06** [comment]
Hey @alisonasanchez,
The Edit Metadata section already exists in 65 metadata doc. Here is the link https://experienceleague.adobe.com/docs/experience-manager-65/assets/using/metadata.html?lang=en#add-edit-metadata.
If there is anything else that you want to add in the doc, please let me know. 
cc: @anujkapo

**Comment by kkour06** [comment]
No feedback received, since closing this issue.
