### ISSUE TITLE
example links

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-65.en#394]
Issue in ./help/sites-administering/troubleshoot-msm.md

When you give this link and other links: http://<host>:<port>/content/path/to/bluprint/page.blueprint.json?&maxSize=500&advancedStatus=true&returnRelationships=true&msm%3Atrigger=ROLLOUT
Can you provide an example of what the path would look like on the wknd site?

**Comment by anujkapo** [comment]
Thanks, @alisonasanchez. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Example links have been added, also for the AEMaaCS doc set. The updates will be published soon.
Closing this issue.
