### ISSUE TITLE
Please improve the documantation regarding the oak index product issues

### ISSUE THREAD

**Issue by yanlicao** [AdobeDocs/experience-manager-65.en#395]
Issue in ./help/release-notes/previous/6.5.14.md
Dear team,
We received user comments on DE page that seems to be a bug about English source file.
Could you kindly check this comment and verify and fix if possible?
----------------------------------------------------
We are missing the latest updates regarding the deprecated /oak:index/lucene index and the known issues regarding infinity reindexing loops ("-Doak.indexTracker.autoRefresh=3153600000000").

Based on issues described in the following support ticket:
https://adminconsole.adobe.com/10834B9C5E790BF70A495E96@AdobeOrg/support/support-cases/E-000788108

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
https://github.com/adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC
