### ISSUE TITLE
Creating a new rollout config

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-65.en#396]
Issue in ./help/sites-developing/extending-msm.md
Your instructions on creating a new rollout config could be better.
1. You first say:
Navigate to :
/apps/msm/<your-project>/rolloutconfigs
How do we know what <your-project> should be? Do you really mean project, or do you mean site?
2. In this section:
NOTE
This is your project’s customized version of:
/libs/msm/wcm/rolloutconfigs
Must be created if this is your first configuration.

Again, what if the wcm folder does not exist? Then you need to create it with the <your-project>  which may also be the site name? Does the name matter? How does this map back to a blueprint configuration, or does it?

**Comment by aheim0** [comment]
Thanks for raising this - we will review.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Some updates applied, will be published soon.
Closing issue.
