### ISSUE TITLE
Day CQ Link Checker Task then executes on a regular basis to validate the links by making a GET call

### ISSUE THREAD

**Issue by DasAnk** [AdobeDocs/experience-manager-65.en#399]
Issue in ./help/sites-administering/external-link-checker.md

Last time I checked, Day CQ Link Checker Task validated the link using a HEAD call. Was this updated to the GET call?
Reference ticket: https://jira.corp.adobe.com/browse/CQ-4346979

**Comment by anujkapo** [comment]
Thanks, @DasAnk. We'll confirm and update the docs, if required.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
We have been informed that the feature is working as designed, so this is outside our scope. If you have further requirements we can only suggest that you contact your Sales or Support representative. Thank you.
Closing this issue.
