### ISSUE TITLE
Screen Shot shows Salesforce instead of DavEx servlet

### ISSUE THREAD

**Issue by godanny86** [AdobeDocs/experience-manager-65.en#4]
Issue in help/sites-administering/enabling-crxde-lite.md

It looks like the screenshot is incorrect under the instructions for enabling CRXDE Lite. The screenshot appears to be a Salesforce configuration. I think it should probably be like below: 

![image](https://user-images.githubusercontent.com/8974514/71559826-9f70fb80-2a30-11ea-8061-24de9c558877.png)

**Comment by bohnertchris** [comment]
Thanks for reporting this, @godanny86. This appears to be an issue resulting from our content migration to the new platform. We will address this shortly.

SSECD-632

**Comment by bohnertchris** [comment]
This has been fixed and the updated pages are now published.
