### ISSUE TITLE
Metadata import requires explicit format of datetimestamp

### ISSUE THREAD

**Issue by lha-adobe** [AdobeDocs/experience-manager-65.en#40]
Issue in help/assets/metadata-import-export.md

Metadata import requires explicit format of datetimestamp

customers should use the format 
`YYYY-MM-DDThh:mm:ss.fff-00:00`

YYYY is year
MM is month in 2 digit format
DD is day in 2 digit format
T is seperating date and time
hh is hour in 24hour military format
mm is minute
ss is seconds
fff is nanoseconds
-00:00 is timezone offset

EXAMPLE: 
2020-03-26T11:26:00.000-07:00 
* This is PST datetime for March 26 2020 at 11:26:00.000 AM PST

{{Logged by Support}}

**Comment by ashishguptaiitb** [comment]
Thanks Lisa for sharing this issue. I shall look at it soon.

**Comment by bohnertchris** [comment]
CQDOC-15586

**Comment by ashishguptaiitb** [comment]
The docs are updated. Closing this ticket. Thanks for sharing the nuanced details.
