### ISSUE TITLE
Add Internationalizing i18n to AEMaaCS documentation

### ISSUE THREAD

**Issue by adobe-biegner** [AdobeDocs/experience-manager-65.en#400]
Issue in ./help/sites-developing/i18n-dev.md

The whole documentation of Internationalizing (i18n) does not seem to be part of the AEMaaCS documentation. But I believe most of it is still valid except that dictionaries now have to be deployed or imported and cannot be directly edited in CS?

So I believe all the Internationalizing documentation should be adjusted and added to the CS documentation.

**Comment by aheim0** [comment]
Thanks for raising this, we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC
