### ISSUE TITLE
default configuration container

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-65.en#405]
Issue in ./help/sites-developing/ch-configuring.md
The step that says this:

Click or tap the default Configuration Container.

It is not clear what "default" means here

**Comment by aheim0** [comment]
Thanks for raising this, we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for highlighting this. Changes have been made and will be published soon.
Closing issue.
