### ISSUE TITLE
Defining custom run-mode

### ISSUE THREAD

**Issue by jamesmcmon** [AdobeDocs/experience-manager-65.en#408]
Issue in ./help/sites-deploying/configure-runmodes.md

The section "Starting CQ with a specific run mode" define the different options to specify custom run-mode and describe the order of priorities applied. Now the given order is wrong (as experimented after a customer report) and should be corrected with: system properties (-D), sling.properties, -r option, filename detection

**Label: DocBugBlitz2023**

**Comment by anujkapo** [comment]
Thanks, @jamesmcmon. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by raimanS** [comment]
The section has been updated. Thanks.
