### ISSUE TITLE
Please fix the following link in the "Caution" section of the document

### ISSUE THREAD

**Issue by dcampbell23** [AdobeDocs/experience-manager-65.en#409]
URL: https://experienceleague.adobe.com/docs/experience-manager-65/administering/integration/salesforce.html?lang=en#:~:text=You%20can%20configure%20AEM%20to,to%20enhance%20the%20customer%20experience.

Please Fix The Following Link: 
You need to install the [Salesforce Force API](https://experience.adobe.com/#/downloads/content/software-distribution/en/aem.html?fulltext=salesforce*&orderby=%40jcr%3Acontent%2Fjcr%3AlastModified&orderby.sort=desc&layout=list&p.offset=0&p.limit=2&package=%2Fcontent%2Fsoftware-distribution%2Fen%2Fdetails.html%2Fcontent%2Fdam%2Faem%2Fpublic%2Fadobe%2Fpackages%2Fcq650%2Ffeaturepack%2Fcom.adobe.cq.mcm.salesforce.content-1.0.4.zip) integration package before you continue with the procedure.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
I have just tried the link and was able to successfully download the package.

Can we ask you to try again, and if you are still having issues, please contact Support.

This is no longer a documentation issue, so closing this.
