### ISSUE TITLE
Uber-jar version wrong?!

### ISSUE THREAD

**Issue by muenkti** [AdobeDocs/experience-manager-65.en#41]
Issue in help/release-notes/sp-release-notes.md
Page: https://docs.adobe.com/content/help/en/experience-manager-65/release-notes/service-pack/sp-release-notes.html
Section: UberJar

The pom dependency for the uber-jar needed to have following version to run the build successful:
`<version>6.5.4</version>`
instead of
`<version>6.5.4.0</version>`

**Comment by anujkapo** [comment]
Thanks for the feedback. I'll follow-up and get the Release Notes updated. Thanks!

**Comment by anujkapo** [comment]
The updated version of the Release Notes is now available at:
https://docs.adobe.com/content/help/en/experience-manager-65/release-notes/service-pack/sp-release-notes.html#install
