### ISSUE TITLE
In AEM 6.5 service pack release notes, the modification guide of damAssetLucene is insufficient

### ISSUE THREAD

**Issue by ysawada-a** [AdobeDocs/experience-manager-65.en#411]
Issue in ./help/release-notes/release-notes.md

Issue Description:
In the Known Issue section, the modification guide of /oak:index/damAssetLucene is not enough clear. Please add a screenshot of CRX/DE with the modified damAssetLucene node after the following paragraph.

--
When trying to move/delete/publish either Content Fragments or Sites/Pages, there is an issue when Content Fragment references are fetched, as the background query fails; i.e. the functionality does not work.
To ensure correct operation, you must add the following properties to the index definition node /oak:index/damAssetLucene (no reindexing is required):

```
"tags": [
    "visualSimilaritySearch"
  ]
"refresh": true
```
--

Label: DocBugBlitz2023

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
See CQDOC-20254.
Closing this issue.
