### ISSUE TITLE
View in Admin feature not explained

### ISSUE THREAD

**Issue by rnituadobe** [AdobeDocs/experience-manager-65.en#415]
Issue in ./help/sites-authoring/author-environment-tools.md

The document also doesn't mention about the "View in Admin" OOTB behavior and functionality
Although "View in Admin" is specified in [1] when clicking the link it redirects to a different page and this feature is not explained.

[1] https://experienceleague.adobe.com/docs/experience-manager-65/authoring/authoring/author-environment-tools.html?lang=en#page-information

**Label: DocBugBlitz2023**

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This was addressed in commit 5b29fb7.
