### ISSUE TITLE
Update the content for AEM 6.5

### ISSUE THREAD

**Issue by nobhashim** [AdobeDocs/experience-manager-65.en#416]
Issue in ./help/sites-deploying/performance-guidelines.md

Issue Description:
The page contents is for AEM 6.2. Need to update for AEM 6.5.

Label: DocBugBlitz2023

**Comment by bohnertchris** [comment]
Thank you for calling this to our attention. While the particulars may have changed for 6.5, the steps laid out are generally still applicable. As this issue is entered, there is not enough information for us to take action.
