### ISSUE TITLE
gmail mentioned in outlook oauth setup

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-65.en#417]
Issue in ./help/sites-administering/notification.md

This section is in the outlook oauth setup instructions:
Open a new tab in the browser and go to http://serveraddress:serverport/services/mailer/oauth2/authorize. This will redirect you to the page of your SMTP provider, in this case Gmail.

I think that in this case the smtp provider is outlook and not gmail, please confirm and correct.

Label: DocBugBlitz2023

**Comment by bohnertchris** [comment]
Thanks for pointing this out, @alisonasanchez. We'll have a look.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This was corrected with commit 1d5903e.
