### ISSUE TITLE
There is no description of Smart Tags in Solutions Integration

### ISSUE THREAD

**Issue by ysawada-a** [AdobeDocs/experience-manager-65.en#419]
Issue in ./help/sites-administering/integration.md

Issue Description:
Solutions Integration[1] does not include the Smart Tags feature.
Add link[2] to the end of the list below bold point at the top of the page of [1].

・Integrating with the Adobe Marketing Cloud
・Integrating with Third-Party Services
・Analytics with External Providers
・Catalog Producer
・SharePoint Connector
・**Understand, apply, and curate Smart Tags  <-- Add link[2]**

[1] Solutions Integration
https://experienceleague.adobe.com/docs/experience-manager-65/administering/integration/integration.html?lang=en

[2] Understand, apply, and curate Smart Tags
https://experienceleague.adobe.com/docs/experience-manager-65/assets/using/enhanced-smart-tags.html?lang=en
![image](https://user-images.githubusercontent.com/77133313/233968941-3b53b113-1a61-4423-afee-4955384b6b98.png)
Label: DocBugBlitz2023

**Comment by anujkapo** [comment]
Thanks, @ysawada-a . We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC
