### ISSUE TITLE
Installing VLT Tool - Step 1 - Can't download FileVault Archive

### ISSUE THREAD

**Issue by rmcdouga** [AdobeDocs/experience-manager-65.en#42]
Issue in help/sites-developing/ht-vlttool.md

Step 1 says "Download the FileVault archive file from the Apache Jackrabbit web site.".  Unfortunately, the FileVault archive file is not available on the linked Apache Jackrabbit downloads page.  Only the source code .zip is currently available.

It looks like Step 3 assumes an archive that is not the source code but rather a binary release.  It does not appear to be available on the linked page.

Unfortunately, this makes the vlt tool unavailable to anyone who can't compile the source.  I've tried, but there are errors in the unit tests and even skipping the unit tests, the project does not seen to create an executable jar file.

**Comment by bohnertchris** [comment]
Thanks for this, @rmcdouga . Seems like the executable for the Maven plug in is still available so I will try to track down what we need to do about the VLT tool itself. CQDOC-15585

**Comment by bohnertchris** [comment]
This has been fixed via commit e513fe0 in this repo as well as via commit 6758a93 in the experience-manager-64.en repo.

**Comment by rmcdouga** [comment]
Thanks for updating the docs.  I love that the docs are in Github so that we can log issues and make PRs.  Great idea!!!

**Comment by bohnertchris** [comment]
Glad that you like it! Not to sound too much like a viral marketing ploy, but don't forget to tell your friends :) We are hoping that by making it easy for everyone to participate that we can welcome more and more contributions from our expert community.

**Comment by bohnertchris** [comment]
The links have been updated to point to the bins in the Maven repo in both 6.4 and 6.5 documentation sets. Apologies for not updating this issue immediately when we fixed this content.
