### ISSUE TITLE
Unable to add parent or child pages of source path to Launch

### ISSUE THREAD

**Issue by nobhashim** [AdobeDocs/experience-manager-65.en#421]
Issue in ./help/sites-authoring/launches.md

Issue Description:
Please consider to add one line below to the NOTE.
A launch with a parent or child page of the source path fails with the error “Destination already exists at :path to the page.” upon creation.

NOTE
To add pages and/or branches to a launch they must be within a site; i.e. below a common top-level root.
If a site contains language roots below the top level, the pages and branches for a launch must be below a common language root.

Label: DocBugBlitz2023

**Comment by anujkapo** [comment]
Thanks, @nobhashim. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by TylerRush** [comment]
Thanks for your feedback. We have updated the note to describe the error condition. The changes are in the pipeline and will appear on Experience League shortly.
