### ISSUE TITLE
Search Workflow Instances is not available in AEM 6.5

### ISSUE THREAD

**Issue by nobhashim** [AdobeDocs/experience-manager-65.en#422]
Issue in ./help/sites-administering/workflows-administering.md

Issue Description:
The  document shows how to use the workflow Instances filtering feature, but there is no corresponding filtering feature in AEM 6.5. It is only available in AEM as a Cloud Service, currently. Please delete the entire section of "Search Workflow Instances."

Label: DocBugBlitz2023

**Comment by anujkapo** [comment]
Thanks, @nobhashim. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for raising this. The section has been removed and the changes will be published soon.
Closing issue now.
