### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by hoff9000** [AdobeDocs/experience-manager-65.en#43]
Issue in help/assets/assets-api-content-fragments.md

Broken link (returns 404):

Under the API Reference heading, it is 
Adobe Experience Manager Assets API - Content Fragments

![image](https://user-images.githubusercontent.com/45748437/76790652-797c0d00-677c-11ea-8c12-86c86db61d5c.png)

**Comment by guillaumecarlino** [comment]
The link is fixed.
Thanks for reporting.
