### ISSUE TITLE
Deprecated method ManagedPollConfigImpl (AEMaaCS)

### ISSUE THREAD

**Issue by dnozumi** [AdobeDocs/experience-manager-65.en#433]
Issue in ./help/sites-administering/adobeanalytics-connect.md
Under the "Configuring the Import interval" the com.day.cq.polling.importer.impl.ManagedPollConfigImpl is the recommended service to use "To configure this OSGi service, you can either use the Web Console or an osgiConfig node in the repository (the service PID is com.day.cq.polling.importer.impl.ManagedPollConfigImpl)."

However according to CQ-4219520, it has been deprecated. That instruction needs to be removed and the correct method implemented.

 

See documentation requirements in comment on:

- https://jira.corp.adobe.com/browse/CQ-4343606

**Comment by guillaumecarlino** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
Thanks for reporting @dnozumi , we will take a look.

**Comment by aheim0** [comment]
The documentation has been updated. The changes will be published when the updates are made public in the product.
Closing issue.
