### ISSUE TITLE
Live Copy for AEM Assets is missing documentation

### ISSUE THREAD

**Issue by lmaughan921** [AdobeDocs/experience-manager-65.en#434]
Issue in ./help/sites-administering/msm-livecopy-overview.md

AEM Assets Live Copy is not documented that we could find.   Please document.   This is a valuable feature for DAM Librarians who need a golden master of certain assets with the ability to populate changes out.    Those types of users are not well suited to review Sites documentation and understand how to apply that to their assets and it's UI.

**Comment by guillaumecarlino** [comment]
Hi @lmaughan921,
I think you're looking for https://experienceleague.adobe.com/docs/experience-manager-65/assets/using/reuse-assets-using-msm.html

**Comment by guillaumecarlino** [comment]
@adobe export issue to Jira project CQDOC

**Comment by lmaughan921** [comment]
> Hi @lmaughan921, I think you're looking for https://experienceleague.adobe.com/docs/experience-manager-65/assets/using/reuse-assets-using-msm.html Let us know if that helps.

Yes, that is correct.   Thank you.  Tags/SEO needs to be optimized.   If you Google "AEM Assets Live Copy' this is not found.  Various other phrases searched about the functionality desired do not produce results.  Using MSM is not a term a DAM Librarian is likely to use to find help.

**Comment by guillaumecarlino** [comment]
Yes, you're correct. As you may have seen, I created an internal ticket and communicated this to the dediacted team. Thanks again for your feedback.
