### ISSUE TITLE
Link to download Salesforce Force API is broken

### ISSUE THREAD

**Issue by rjarin15** [AdobeDocs/experience-manager-65.en#435]
Issue in ./help/sites-administering/salesforce.md

**Comment by rjarin15** [comment]
https://experience.adobe.com/#/downloads/content/software-distribution/en/aem.html?fulltext=salesforce*&orderby=%40jcr%3Acontent%2Fjcr%3AlastModified&orderby.sort=desc&layout=list&p.offset=0&p.limit=2&package=%2Fcontent%2Fsoftware-distribution%2Fen%2Fdetails.html%2Fcontent%2Fdam%2Faem%2Fpublic%2Fadobe%2Fpackages%2Fcq650%2Ffeaturepack%2Fcom.adobe.cq.mcm.salesforce.content-1.0.4.zip

**Comment by raimanS** [comment]
@rjarin15 Thank you for opening this issue. We will look into it.

**Comment by raimanS** [comment]
@adobe export issue to Jira project CQDOC

**Comment by raimanS** [comment]
@adobe export issue to Jira project CQDOC

**Comment by raimanS** [comment]
Setting this issue as complete. Please open a new issue if the problem persists.
