### ISSUE TITLE
Dynamic media config states minutes vs seconds.

### ISSUE THREAD

**Issue by jkerger** [AdobeDocs/experience-manager-65.en#436]
The doc states the units are in minutes instead of seconds for the timeout config.

https://github.com/AdobeDocs/experience-manager-65.en/blob/e0db0f85e22929eb6f306a3f3f8d4a7093501a99/help/assets/config-dms7.md?plain=1#L309

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by rickbrough** [comment]
Fixed in https://experienceleague.adobe.com/docs/experience-manager-65/assets/dynamic/config-dms7.html?lang=en#optional-setup-and-configuration-of-dynamic-media-scene7-mode-settings, dated July 28, 2023 or later.

Thank you for logging the issue.
