### ISSUE TITLE
link doesn't work

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-65.en#438]
Issue in ./help/sites-administering/ssl-by-default.md
On my OOTB instance, http://localhost:4502/libs/granite/security/content/userEditor.html/home/users/system/security/ssl-service does not work.
http://localhost/libs/granite/security/content/v2/usereditor.html/home/users/system/security/ssl-service works instead.
Can you update the link?
Also, please indicate what you need to look for to make sure the certificates exist and are valid.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
The replacement link provided doesn't work either. Looks like it should be:

    [http://localhost:4502/libs/granite/security/content/v2/usereditor.html/home/users/system/security/ssl-service](http://localhost:4502/libs/granite/security/content/v2/usereditor.html/home/users/system/security/ssl-service+)

Have updated the link and the text. Changes will be published soon.

Closing this issue.
