### ISSUE TITLE
Incoming links should indicate that it works only for static links

### ISSUE THREAD

**Issue by swaroop61** [AdobeDocs/experience-manager-65.en#443]
Issue in ./help/sites-authoring/author-environment-tools.md

Issue description:
When using a List component & configuring dynamic links such as child pages, the incoming links do not show up, the documentation needs to update that this feature only supports fixed/static links that are stored in JCR.

If the Incoming Link references functionality relies on page content indexing then it won't find the dynamically generated links as they aren't store in the page's content.

Label: DocBugBlitz2023

**Comment by guillaumecarlino** [comment]
Thank you for your issue. We will investigate.

**Comment by guillaumecarlino** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Updates have been made and will be published soon.
Closing this issue.
