### ISSUE TITLE
Metadata Schema and Content Fragment editors not displaying new fields correctly

### ISSUE THREAD

**Issue by alexisGlzRdz** [AdobeDocs/experience-manager-65.en#444]
**Steps to reproduce:**

1. Service Pack 6.5.17.0 or 6.5.18.0 should be installed.
2. Go to either the Metadata Schema editor or Content Fragment Model editor.
3. Create a new one or open an existing one.
4. Add a new element to the layout.

New element should display like this:

![Screen Shot 2023-08-24 at 12 45 30](https://github.com/AdobeDocs/experience-manager-65.en/assets/11239853/b630e52c-d77f-435c-ab0e-e59abefecac4)

As you can see the new element does not take the complete column width.

After the new changes are saved and page is refreshed, then the new field is displayed normally.

**Comment by aheim0** [comment]
@alexisGlzRdz 
Thank you for contacting us. 

However, from what I can see this is an issue with the behavior of the product, not with the documentation.

Therefore we can only suggest that you contact your Support representative.

Closing this issue.
