### ISSUE TITLE
Known Issues / damAssetLucene changes are not clear enough

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-65.en#445]
Issue in ./help/release-notes/release-notes.md

Since SP16 release notes, there has been this note in the Known Issues section about the "damAssetLucene" index:

> A GraphQL query may use the damAssetLucene index instead of the fragments index. This action might result in GraphQL queries that fail, or take a long time to run.
> 
> To correct the problem, damAssetLucene has to be configured to include the following two properties:
> 
> contentFragment
> model
> After the index definition is changed, a reindexing is required (reindex = true).
> 
> After these steps, the GraphQL queries should perform faster.

The correction instructions are not clear. Customers need to know exactly what nodes and properties must be changed for this index to be fixed for GraphQL queries. I assume you are referring to the index properties node at "/oak:index/damAssetLucene/indexRules/dam:Asset/properties". If "contentFragment" and "model" need to be added under this node, then we need to know exactly what the new nodes should be and exactly what properties go into those nodes. There should be no ambiguity here.  What is the path of the "contentFragment" property? Is it "jcr:content/contentFragment" or just "contentFragment"? Same for "model". What other properties need to be set for the new properties to be properly indexed? 
Leaving the customer asking more questions leads to them opening support tickets, which we don't need. Is there a KB article which provides details for this? If so, can a link to that article be added to the release notes?

Thanks,
John

**Comment by johnb4** [comment]
Maybe this whole section needs to be removed if this issue is resolved by installing the "cfm-graphql-index-def-1.1.1.zip" package. See comments at "https://wiki.corp.adobe.com/display/MSTeam/AEM+6.5.18+Regressions", where it's noted that these changes can be ignored.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC
