### ISSUE TITLE
Unwanted link in features column

### ISSUE THREAD

**Issue by vdhaliwa** [AdobeDocs/experience-manager-65.en#45]
Issue in help/sites-developing/workflows-program-interaction.md

Go to the section "Using the Workflow Java API", there is a table of features and objects.

In the features column, there is a text "WorkflowStatus.html" which has link to workflow status. I think someone added this text by mistake.

Even if it is intentional, it should be without .html. 

Same issue in 6.4 doc as well.

[logged by support]

**Comment by bohnertchris** [comment]
Thank you for reporting this, @vdhaliwa. Looks like an error in our content migration to the new platform. We will fix it.

**Comment by bohnertchris** [comment]
CQDOC-15619

**Comment by bohnertchris** [comment]
This has been fixed in commit d2ec96c in this repo as well as in commit 02cc3e1 in the experience-manager-64.en repo.
