### ISSUE TITLE
Deprecated features is almost identical

### ISSUE THREAD

**Issue by jasmeet2dhiman** [AdobeDocs/experience-manager-65.en#450]
Upon reviewing the release notes for the SP17 upgrade, we noticed that the list of deprecated features is almost identical to that of previous service packs. It is unclear whether this is a documentation error.

https://experienceleague.adobe.com/docs/experience-manager-65/release-notes/service-pack/6.5.17.html?lang=en#removed-deprecated-features
https://experienceleague.adobe.com/docs/experience-manager-65/release-notes/service-pack/6.5.16.html?lang=en#removed-deprecated-features
https://experienceleague.adobe.com/docs/experience-manager-65/release-notes/service-pack/6.5.15.html?lang=en#removed-deprecated-features
https://experienceleague.adobe.com/docs/experience-manager-65/release-notes/service-pack/6.5.14.html?lang=en#removed-deprecated-features

**Comment by anujkapo** [comment]
@jasmeet2dhiman, the known issues are usually carried over from the previous Service Pack and evaluated for any modifications. @rickbrough, can you take a look if we need to create a CQDOC and update docs? Thanks!

**Comment by rickbrough** [comment]
Thank you jasmeet2dhiman for your feedback. The documentation in the links that you provided is now updated to better reflect the organization and location of deprecated (and removed) features in AEM 6.5.
