### ISSUE TITLE
Custom Live Action sample does not work

### ISSUE THREAD

**Issue by jlanssie** [AdobeDocs/experience-manager-65.en#455]
The instructions at [Implement LiveActionFactory](https://github.com/AdobeDocs/experience-manager-65.en/blob/main/help/sites-developing/extending-msm.md#implement-liveactionfactory-implement-liveactionfactory) to create a custom Live Action via the LiveActionFactory do not work. 

The Live Action (e.g. exampleLiveAction ) never registers, causing any Rollout Configs to reference this Live Action to be unavailable. Also the annotations @Property and @Service are never used. Developers stick to @Component. e.g. 

````java
@Component(
        service = { LiveActionFactory.class },
        property = {LiveActionFactory.LIVE_ACTION_NAME + "=exampleLiveAction" },
        immediate = true)
````

**Comment by guillaumecarlino** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Your PR has been manually ported and will be published soon.

Thanks for your input.

Closing this issue now.
