### ISSUE TITLE
Feedback form doesn't work in Firefox

### ISSUE THREAD

**Issue by fsanitas** [AdobeDocs/experience-manager-65.en#456]
Issue in ./help/assets/download-assets-from-aem.md

Repro:
1.  Open page with Firefox (115.3.1esr (64-bit), Windows)
2. Click thumbs-up or thumbs-down button

Expected:
Feedback form pops up, with input textbox enabled to receive feedback.

Actual:
Nothing happens. The dialog doesn't open.

**Comment by guillaumecarlino** [comment]
Hi,

Thanks for reporting. This is a known issue, the platform team works on it via ticket UGP-8590.

**Comment by fsanitas** [comment]
Any update? It still doesn't work. I don't have access to this ticket, so I can't track it.

**Comment by guillaumecarlino** [comment]
@fsanitas , what version of firefox are you using? It should work from Firefox 118.0.2 onwards. It works on the latest 119.0.1.

**Comment by fsanitas** [comment]
115.4.0esr .. I'm in a corporate setting, that's why we use the ESR version.

**Comment by guillaumecarlino** [comment]
I'm sorry, but since it works on the latest versions of Firefox as well as on Chrome, the platform team considers it fixed.
