### ISSUE TITLE
Insufficient database information provided in Step 1: Set up the database

### ISSUE THREAD

**Issue by tonyatmendina** [AdobeDocs/experience-manager-65.en#46]
Issue in help/forms/using/create-form-data-model0.md

I'm attempting to work through the tutorial "Tutorial: Create your First Interactive Communication," and I've already become stymied in "Tutorial: Create form data model." While I'm told to set up a mysql schema (database) and fill it with sample data, very little information is given about the database to be set up. 

Ideally, a setup script should be provided that can be run against a local MySQL server as root, but as a temporary measure, users should at least see a database diagram where none of the column names are truncated and information about the type of data that must be hand-created for each column is provided. 

Perhaps there's a master collection of sample database setup instructions for all these AEM forms tutorials somewhere, and a link just needs to be provided to it?

Thank you.

**Comment by Khushwantsehgal** [comment]
@anujkapo, Please look into it.

**Comment by anujkapo** [comment]
Thanks for the feedback. We are looking into the issue and will come up with a fix soon.

**Comment by anujkapo** [comment]
Hi @tonyatmendina ,

I have added DDL statements to create tables in the MYSQL database. The article is available live at:
https://docs.adobe.com/content/help/en/experience-manager-65/forms/getting-started/create-first-interactive-communication/create-form-data-model0.html

Please let me know in case of any issues.
