### ISSUE TITLE
Obtaining one heap dump is not enough

### ISSUE THREAD

**Issue by frotto4000** [AdobeDocs/experience-manager-65.en#460]
Issue in ./help/sites-deploying/troubleshooting.mdIssue in ./help/sites-deploying/troubleshooting.md

Please change the following page to the correct content.

https://experienceleague.adobe.com/docs/experience-manager-65/deploying/deploying/troubleshooting.html?lang=en#my-application-running-on-crx-throws-out-of-memory-errors

Before change:
Usually, one heap dump file is enough to analyze the problem.

After change:
Usually, three heap dump files, separated by time, are required to analyze the problem.

------------

In that heap dump

- Before failure occurs
- During failure 1
- During failure 2

to see changes in which objects are becoming more occupied.
In addition, if possible, it would be nice to have information after the event is resolved.

**Comment by guillaumecarlino** [comment]
Thank you @frotto4000 , we will review.

**Comment by guillaumecarlino** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for raising this - the page has been updated and will be published soon.
Closing this issue now.
