### ISSUE TITLE
AEM Link checker will make only Head requests. This documentation still says Link checker makes GET requests

### ISSUE THREAD

**Issue by sarathraju** [AdobeDocs/experience-manager-65.en#463]
Until the AEM 6.4 release, the Link Checker would make both a HEAD and GET request when validating links.
This behavior was changed in AEM 6.5 to address a critical security vulnerability (CQ-4259662 | SSRF in the Link Checker).
Hence from AEM 6.5 onwards, the Link Checker will only submit HEAD requests.

Refer to this documentation [1]. 

Please update the product documentation accordingly.

[1]: https://experienceleague.adobe.com/docs/experience-cloud-kcs/kbarticles/KA-15607.html?lang=en

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
The link you have provided is not part of this repo. It belongs to another repo that belongs to another team. I have forwarded the ticket to that team.
As we can no longer track this I am closing this issue now.
