### ISSUE TITLE
Authentication details to be updated

### ISSUE THREAD

**Issue by sayabannatole** [AdobeDocs/experience-manager-65.en#467]
Issue in ./help/assets/config-smart-tagging.md
The steps mentioned in the document for authentication needs to be udpated

"Select Upload your public key. Provide the certificate file downloaded from Experience Manager. A message Public key(s) uploaded successfully is displayed. Click Next.

Create a new Service Account (JWT) credential page displays the public key for the service account."

As this step is not present in Adobe I/O and JWT authentication is deprectaed now.
Needs the updated information to be updated here

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by anujkapo** [comment]
The updated documentation is now available at:
https://experienceleague.adobe.com/en/docs/experience-manager-65/content/assets/administer/config-smart-tagging#create-adobe-i-o-integration

Please let us know in case of any issues.
