### ISSUE TITLE
AEM 6.5 3D file handling

### ISSUE THREAD

**Issue by jmlg10** [AdobeDocs/experience-manager-65.en#47]
I can't find any details how to set up my AEM 6.5 instance in order to handle 3D files.

I find informations on file managed (OBJ, STL, GLB, GLTF) but nothing on how to configure DAM update Asset workflow or any other sub-system in AEM.

Many Thanks

If this place is not the right one thanks to forward my message

**Comment by bohnertchris** [comment]
Thank you for creating an issue, @jmlg10 . Issues on the documentation repository are for corrections or improvements to the docs. How-to and implementation questions are best handled via support and I encourage you to pose your question there.
 https://helpx.adobe.com/support/experience-cloud.html
