### ISSUE TITLE
Newer maintenance tasks missing from the 6.5 Maintenance Operations list

### ISSUE THREAD

**Issue by thedoc31** [AdobeDocs/experience-manager-65.en#472]
Since AEM 6.5 is receiving backports of AEM as a Cloud service features, two new maintenance tasks have been backported and need to be added in [2]:
* Project Purge
* ad-hoc Task Purge

Details of these are in [1] and need to be added to the AEM 6.5 page. I'm not sure in which service pack these were introduced but those details should also be added to the page.

[1]
https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/operations/maintenance.html?lang=en

[2]
https://experienceleague.adobe.com/docs/experience-manager-65/content/sites/administering/operations/operations-dashboard.html?lang=en#automated-maintenance-tasks

**Comment by anujkapo** [comment]
Thanks, @thedoc31. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for raising this, updates have been made and will be published soon.
Closing issue now.
