### ISSUE TITLE
Reconsider NRPE recommendation for monitoring AEM

### ISSUE THREAD

**Issue by thedoc31** [AdobeDocs/experience-manager-65.en#473]
NRPE is a tool used for Nagios to remotely execute scripts on a host. In its default configuration, NRPE is insecure and has a number of vulnerabilities that could cause problems [1]. Its last update was in 2020. As such, we should reconsider the recommendations we have on [2] to install it on self-hosted AEM.

[1]
https://community.icinga.com/t/replacing-nrpe-by-icinga-agent-each-agent-requires-own-zone/2620/6

[2]
https://experienceleague.adobe.com/docs/experience-manager-65/content/sites/administering/operations/operations-dashboard.html?lang=en#monitoring-with-nagios

**Comment by anujkapo** [comment]
Thanks, @thedoc31. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for highlighting this. Updates have been made and will be published soon.
Closing issue.
