### ISSUE TITLE
dictionary discrepancies

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-65.en#476]
Issue in ./help/sites-administering/tc-manage.md

In the doc regarding adding dictionaries to a project. 
The screenshot where you select the dictionary is wrong. You must first select a root directory, then you can select a dictionary. These must be defined.

Additionally in Performing Initial Translations and Updating Existing Translations section, it says When you create a translation project for a page and indicate the language copies for which you are translating, AEM detects whether the source page already exists in the targeted language copies. 
Does this apply to dictionaries too? Or is this only for pages. Can you add a section for dictionaries and how it is supposed to work.

**Comment by raimanS** [comment]
Thank you for opening this issue.

**Comment by raimanS** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for raising this - we have made small changes to that specific step. The entire document has been flagged for a refresh so your questions about dictionaries has been transferred to that. 
Closing this issue.
