### ISSUE TITLE
Missing/unclear sentence under "How can I customize the error messages..."

### ISSUE THREAD

**Issue by helms-charity** [AdobeDocs/experience-manager-65.en#478]
Issue in ./help/sites-administering/aem-faqs.md

Under "**How can I customize the error messages while navigating page hierarchy in AEM sites console?**"

The first sentence doesn't make sense to me as a native English speaker (emphasis mine):

> Check the Network panel (of Chrome browser) **_where a personal setup (JS has not been minified)._**

I cannot suggest an edit because I don't know what that part is trying to say.

**Comment by bohnertchris** [comment]
Thank you for reporting this.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
The errant text was removed with commit a407238.
