### ISSUE TITLE
Clarify how "Inclusion rules" work in package manager, with examples.

### ISSUE THREAD

**Issue by matthew-steven-bcbssc** [AdobeDocs/experience-manager-65.en#480]
Exclusion rules are fairly easy to write, typing a regex that matches against the full content path generally works.

Inclusion rules are a big mystery. How exactly do they work?

Example 1, **nothing** is packaged:

![image](https://github.com/AdobeDocs/experience-manager-65.en/assets/39528681/a33d6ab2-7930-428b-8a65-8760017668d7)

Example 2, **nothing** is packaged:

![image](https://github.com/AdobeDocs/experience-manager-65.en/assets/39528681/cef75c87-1ab6-485f-bcb0-b51dd15bd2b1)

Example 3, **everything** is packaged. Inclusion filter appears to be ignored.

![image](https://github.com/AdobeDocs/experience-manager-65.en/assets/39528681/30ee1db9-4b61-4795-a737-289352192adb)

Example 4, **everything** is packaged. Inclusion filter appears to be ignored.

![image](https://github.com/AdobeDocs/experience-manager-65.en/assets/39528681/2ef14fd6-cd75-46a7-8f50-58b75257c371)

Example 5, **everything** is packaged.

![image](https://github.com/AdobeDocs/experience-manager-65.en/assets/39528681/8077cdc2-7986-4a61-94f0-377fac0f3f6a)

Example 6, only items under the folder "some-folder-name" are packaged. "some-folder-name" is a direct child of "my-website".

![image](https://github.com/AdobeDocs/experience-manager-65.en/assets/39528681/2080335b-1fd1-45dc-bcc2-85d7d9870567)

Example 6 is pointless to do because you can just set the root path to "/content/my-website/some-folder-name".

Example 7,  **nothing** is packaged. "some-other-folder-name" is a folder that is not a direct descendant folder of "my-website", but it is inside of as one of its grandchildren:

![image](https://github.com/AdobeDocs/experience-manager-65.en/assets/39528681/157a4852-a8a4-44ce-b3d7-6d9d66d0a540)

**Comment by raimanS** [comment]
Thank you for opening this issue. We will investigate.

**Comment by raimanS** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for raising this. We have made updates to the documentation - they will be published soon.
Hope this helps, if you have question related to specific regular expressions then you can contact the Community.
Closing this issue.
