### ISSUE TITLE
No instruction to stop

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-65.en#481]
Issue in ./help/sites-deploying/data-store-config.md

In the section "Amazon S3 Datastore" the last step 6 is to Start AEM, but no where before that is there a step to stop it. I assume that we need to stop it, but it doesn't say where.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
https://experienceleague.adobe.com/en/docs/experience-manager-65/content/implementing/deploying/deploying/data-store-config

There is no Stop necessary as the first step in the procedure is "Copy the AEM quickstart JAR file to its installation directory." so AEM would not be running.

Closing issue.
