### ISSUE TITLE
API key?

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-65.en#482]
Issue in ./help/sites-administering/integration-target-ims.md

In the IMS Technical Account Configuration screen in AEM, we have to enter in the API key and Client Secret. From the project screen, we don't have anything called "API Key", though there are fields called Client ID and Client Secret. It is not clear what is supposed to go in the "API Key" slot. It needs to be more clear. All the doc says is to get it from the "Overview" section, but it is not clear what value to use.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Thank you for pointing this out, @alisonasanchez. We will have a look.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
CQDOC-21431

**Comment by aheim0** [comment]
This page is now redundant as the sub-section has been rewritten.

New information is available under: https://experienceleague.adobe.com/en/docs/experience-manager-65/content/security/setting-up-ims-integrations-for-aem
