### ISSUE TITLE
Add a note about live copies of Experience Fragments

### ISSUE THREAD

**Issue by frotto4000** [AdobeDocs/experience-manager-65.en#483]
Issue in ./help/sites-authoring/experience-fragments.md

Please add a note at the end of Creating An Experience Fragment Variation[1] and write the following two points.
*The first point is the contents of the Release Note [2] posted as is.

- Multisite Manager (MSM) now supports Experience Fragment structures including folders and subfolders, for efficient bulk rollout of Experience Fragments to Live Copies.

- Creating an initial Live Copy/Variation will inherit the title by using the Blueprint as the Master Variation

[1]
https://experienceleague.adobe.com/en/docs/experience-manager-65/content/sites/authoring/authoring/experience-fragments#creating-an-experience-fragment-variation

[2]
https://experienceleague.adobe.com/en/docs/experience-manager-65/content/release-notes/release-notes
****
Multisite Manager (MSM) now supports Experience Fragment structures including folders and subfolders, for efficient bulk rollout of Experience Fragments to Live Copies.
****

**Comment by aheim0** [comment]
Thank you for raising this. 

Such changes are already in the pipeline, and will be published with the next release. We will review them to ensure that all your points are covered.

Closing this issue.

**Comment by aheim0** [comment]
A note has been added.
