### ISSUE TITLE
Oak version in AEM 6.5.11-13 Release Notes is not correct

### ISSUE THREAD

**Issue by nobhashim** [AdobeDocs/experience-manager-65.en#486]
Issue in ./help/release-notes/previous/6-5-13.md

The version of Apache Jackrabbit Oak in the service pack 11, 12 13 release notes is not correct.

Current:

Validate the installation
3. The OSGi bundle org.apache.jackrabbit.oak-core is version 1.22.3 or later (Use Web Console: /system/console/bundles).

To Be:

The Oak version should be the followings ,repectively.
AEM 6.5.11: Oak 1.22.9
AEM 6.5.12: Oak 1.22.9
AEM 6.5.13: Oak 1.22.11

**Comment by guillaumecarlino** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
Thanks for reporting @nobhashim, I will take care of it.
