### ISSUE TITLE
Instructions to have better control and safety, never work

### ISSUE THREAD

**Issue by Serendipity253** [AdobeDocs/experience-manager-65.en#488]
Issue in ./help/assets/duplicate-detection.md
When I try to click on markdown is supported; oops contact support
oops contact support appears almost every time I use the website, but that doesnt work either

**Comment by anujkapo** [comment]
@Serendipity253, can you please elaborate on what is required to be fixed in the article you are referring to? Thanks!

**Comment by anujkapo** [comment]
Closing this one as there has been no response for two weeks now. Please create another issue with the information that we have requested as part of this issue. Thanks!
