### ISSUE TITLE
Suggest mentioning the OAK-9481 fixes in the AEM 6.5 SP21 release notes

### ISSUE THREAD

**Issue by klaehyeok** [AdobeDocs/experience-manager-65.en#490]
Many customers are concerned about the performance issues that occurred in AEM 6.5 SP20, and the release notes should clearly state that these issues have been fixed in  AEM 6.5 SP21.

**Comment by rickbrough** [comment]
AEM 6.5 customers were emailed June 6, 2024 announcing the release and availability of AEM 6.5.21.0 Service Pack.  The email included the following information:

OAK
·  Performance Regression Fix - Avoid range queries on like conditions (OAK-9481)
·  New Oak version will be 1.22.20.

These same two bullet points will be added to the release notes.
