### ISSUE TITLE
Missing 6.5.20 Release Notes Link in Left Navigation Menu

### ISSUE THREAD

**Issue by frotto4000** [AdobeDocs/experience-manager-65.en#491]
Issue in ./help/release-notes/release-notes.md

The customer reports that the latest release notes have been updated to SP21, but the previous release notes for SP20 are no longer visible in the product help page's navigation menu. 
This issue affects both the Japanese and English versions of the page. 
The customer can still access the SP20 release notes via a direct link, but it is not listed in the left-hand navigation menu.[1]

The absence of SP20 in the navigation menu makes it less convenient for users to access the release notes for that specific service pack. This could lead to confusion or additional effort in finding the required information, especially for those who rely on the navigation menu for quick access.

Please add **6.5.20** and link to [2] on the **PREVIOUS RELEASE NOTES** - **RELEASE NOTES** in the left navigation menu.

[1]
https://experienceleague.adobe.com/en/docs/experience-manager-65/content/release-notes/service-pack/6-5-20

[2]
https://experienceleague.adobe.com/en/docs/experience-manager-65/content/release-notes/service-pack/6-5-20

**Comment by rickbrough** [comment]
Thank you for reporting this issue. The link to the 6.5.20 release notes will be back in the table of contents within a few hours.
