### ISSUE TITLE
Broken link on the Github documentation

### ISSUE THREAD

**Issue by navjotkler** [AdobeDocs/experience-manager-65.en#492]
Issue in ./help/sites-authoring/responsive-layout.md

the link mentioned here: "Adobe provides [GitHub documentation](https://adobe-marketing-cloud.github.io/aem-responsivegrid/)"  has a broken link on the github page. please fix that.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
The link is working again - thanks for your help.
Closing this issue.
