### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by navjotkler** [AdobeDocs/experience-manager-65.en#494]
Issue in ./help/sites-administering/tc-tic.md

None of the links under the note section "To find the latest list of human and machine translation providers, have a look at these pages:" works. Getting too many redirects.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
Thanks for reporting @navjotkler, I fixed the links. The changes will be live shortly.
