### ISSUE TITLE
Supported platforms section needs update

### ISSUE THREAD

**Issue by rsaraf-adobe** [AdobeDocs/experience-manager-65.en#495]
Issue in ./help/assets/imaging-transcoding-library.md

Imaging Transcoding Library is available only for RHEL 7 and CentOS 7 distributions.

should be updated to 

Imaging Transcoding Library is available only for RHEL8, RHEL 7 and CentOS 7 distributions.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
CQDOC-21960 was fixed so resolving this issue.
