### ISSUE TITLE
If the user changes any of the values in the "CQ Mailer SMTP OAuth2 Provider" they need to reauthorize

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-65.en#496]
Issue in ./help/sites-administering/notification.md

The documentation could be clearer for customers who change "CQ Mailer SMTP OAuth2 Provider" values, stating (in a WARNING note), something like:

        If you ever change any of the values in the OSGi config "CQ Mailer SMTP OAuth2 Provider", you must reauthorize following the steps at the bottom of this document. If this is not performed, the access token stored at "/conf/global/settings/mailer/oauth" will be invalid and the OAuth2 connection to the SMTP server will fail.

**Comment by guillaumecarlino** [comment]
Thanks for reporting @johnb4, we will investigate.

**Comment by guillaumecarlino** [comment]
@adobe export issue to Jira project CQDOC
