### ISSUE TITLE
Creating a Language Root - Hyphen in the name 

### ISSUE THREAD

**Issue by archanaraghavan** [AdobeDocs/experience-manager-65.en#497]
Issue in ./help/sites-administering/tc-prep.md

For creating language root, <language-code>_<country-code> and <language-code>-<country-code> formats are suggested, with the country code following the ISO 3166 two-letter standard (e.g., en_US, en_us, en_GB, en-gb). However, testing shows that using a hyphen in the language root (e.g., en-gb) is not recommended. Doc needs to be updated to remove **en-gb**

Also, example given underneath that section only mentions underscore, which is correct. 
> In the Name field type the country code in the format of <language-code> or <language-code>_<country-code>, for example, en, en_US, en_us, en_GB, en_gb._

https://experienceleague.adobe.com/en/docs/experience-manager-65/content/sites/administering/introduction/tc-prep#creating-a-language-root

**Comment by guillaumecarlino** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
@archanaraghavan , I double checked with engineering and they confirmed that en-gb was supported and that documentation  hould not be changed. If you are facing issues with en-gb, please contact support.
