### ISSUE TITLE
Preview button does not work properly

### ISSUE THREAD

**Issue by katherinearroyo** [AdobeDocs/experience-manager-65.en#499]
Issue in ./help/assets/content-fragments/content-fragments-json-preview.md

maybe info about preview does not work properly if some endpoint configuration is missing.

**Comment by raimanS** [comment]
@katherinearroyo Thank you for reporting this issue. We will look into it.

**Comment by raimanS** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thank you for contacting us. It is difficult to analyze the situation remotely, but yes full configuration is required for Content Fragment functionality to work properly. If you have any concrete questions we suggest that you ask your Support contact.
Closing this issue.
