### ISSUE TITLE
Images are wrong in asset templates page

### ISSUE THREAD

**Issue by abhishekarora12** [AdobeDocs/experience-manager-65.en#5]
Issue in help/assets/asset-templates.md

**Comment by ashishguptaiitb** [comment]
Thanks @abhishekarora12 for reporting this issue. We are aware of this issue and are working to fix it. I shall update when the updates are published shortly.

**Comment by ashishguptaiitb** [comment]
Hi @abhishekarora12 , the updated article is available at https://docs.adobe.com/content/help/en/experience-manager-65/assets/administer/asset-templates.html  

Thanks again for raising this bug. I shall close this issue and look forward to more contributions from you.
