### ISSUE TITLE
Section 'Customizing Email Templates for Page Notification' outdated.

### ISSUE THREAD

**Issue by muenkti** [AdobeDocs/experience-manager-65.en#500]
Issue in ./help/sites-administering/notification.md

In here it is described, that the email templates need to be adjusted directly within /libs.

That is not correct anymore. At least in AEM 6.5.20 you can create custom email templates by overlaying '/libs/settings/workflow/notification/email/default' to '/etc/workflow/notification/email/default' and adjust the templates there.

**Comment by aheim0** [comment]
Thank you for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thank you for highlighting this - updates have been made.
Closing issue now.

**Comment by muenkti** [comment]
@aheim0 
Thanks for adjusting the documentation.
But based on my testing the location /conf/global/settings/workflow/notification is not working. 
With enable debug log it only shows /etc/ or /libs/ being used. Moving folders/files from /etc/ to /conf/global/settings shows, that they are not used, when restarting the service. 
Checking the code of com.day.cq.workflow.impl.email.EMailNotificationService looks like, it uses only /etc/ or /libs/.

If /conf/ would be expected, maybe recheck in the implementation.

**Comment by aheim0** [comment]
@muenkti Thanks for the extra feedback. 

I'll need to pursue this with another team - so can't guarantee the turnaround. I'll create a new ticket to make sure it doesn't get forgotten.
