### ISSUE TITLE
How can existing renditions be modified?

### ISSUE THREAD

**Issue by RobertoPrimo** [AdobeDocs/experience-manager-65.en#51]
Issue in help/assets/extending-assets.md

**Comment by ashishguptaiitb** [comment]
Hi @RobertoPrimo , can you please elaborate on what modifications do you want to do?

**Comment by ashishguptaiitb** [comment]
Hi @RobertoPrimo , I'd appreciate any info you can share about your needs so I can go back and ask the experts about it.

**Comment by ashishguptaiitb** [comment]
Hi @RobertoPrimo , I'm closing this ticket for now for lack of info. If there's a use-case you have, please reopen.
