### ISSUE TITLE
ToughDay2 - A run mode with type "normal" does not exist

### ISSUE THREAD

**Issue by vidhyabhushanbahl** [AdobeDocs/experience-manager-65.en#54]
Issue in help/sites-developing/tough-day.md

Trying to use ToughDay2 using
java -jar toughday2-0.9.2.jar --host=localhost

but fails with "ERROR: Error encountered: A run mode with type "normal" does not exist"

**Comment by bohnertchris** [comment]
Hello @vidhyabhushanbahl. Sorry to hear you are having troubles. This seems like a technical error and not a documentation issue. Please reach out to AEM Customer Care via our Enterprise Support portal for further help. https://helpx.adobe.com/contact/enterprise-support.ec.html

**Comment by SudhirRojanala** [comment]
Hi Team,

Is there any update for the above issue mentioned for the run mode problem using this Tough Day 2 jar file with version oughday2-0.9.2.jar using this command java -jar toughday2-0.9.2.jar --host=localhost

Please suggest on how to proceed further to use this jar file for aem author instance performance testing using this tool. This would really help us in a great way.

Thanks,
Sudhir

**Comment by ronnyfm** [comment]
@SudhirRojanala @vidhyabhushanbahl were you able to find a workaround for this? 2025 and the same message appears and now new versions of the JAR are available.
