### ISSUE TITLE
Expected bahaviour of standby instance

### ISSUE THREAD

**Issue by BharathValse** [AdobeDocs/experience-manager-65.en#55]
Issue in help/sites-deploying/tarmk-cold-standby.md
It would be great if we can add the expected behavior of standby instance where none of the authoring console/screens would be accessible except web console and CRXDE lite. We can add this as a note.

Additionally, we could add this note on KB [1] as well

[Logged By Support]

[1]
https://helpx.adobe.com/experience-manager/kb/how-to-setup-cold-standby-instance-in-AEM.html#VerifyingtheStandbyinstance

**Comment by bohnertchris** [comment]
Thank you for creating this issue, @BharathValse . However I am unclear what it is that you would like us to add. What exactly is the expected behavior of the standby instance in the situation that you describe?

**Comment by BharathValse** [comment]
Thanks for looking into this @bohnertchris.

When the standby instance is setup or derived from Primary node, admins try to access the welcome screen of AEM and other consoles which results in an Authentication service missing error like [0] on the browser. It is expected that the standby instance doesn't open up these general AEM consoles and only opens up the CRXDE lite and OSGI web console for admin related activities.

Since this behavior is not documented, it leads to confusion that the standby instance is not set up right and corrupted.

[0]
HTTP ERROR 503
Problem accessing /aem/start.html. Reason:

AuthenticationSupport service missing. Cannot authenticate request.

**Comment by bohnertchris** [comment]
Thank you for the further information, @BharathValse . It makes the problem clearer and we will have a look.

**Comment by bohnertchris** [comment]
CQDOC-15720

**Comment by aheim0** [comment]
Thanks for highlighting this - a note has been added.
Closing this issue.
