### ISSUE TITLE
Duplicated text

### ISSUE THREAD

**Issue by lha-adobe** [AdobeDocs/experience-manager-65.en#56]
Minor Issue in help/assets/metadata-schemas.md

Search for **The following are the valid values for this property:** , this is repeated twice

{{Logged by Support}}

**Comment by lha-adobe** [comment]
Also, the section in [1] has no more line breaks between all the possible options that are bolded ...

https://docs.adobe.com/content/help/en/experience-manager-65/assets/administer/metadata-schemas.html#components-within-the-build-form-tab

**Comment by bohnertchris** [comment]
Thank you for reporting this, @lha-adobe . We will address it.

**Comment by bohnertchris** [comment]
CQDOC-15710

**Comment by bohnertchris** [comment]
This was fixed with commit c71b55c.
