### ISSUE TITLE
Package Share deprecation and translation partner list change

### ISSUE THREAD

**Issue by jedediahmadsen** [AdobeDocs/experience-manager-65.en#57]
Issue in help/sites-administering/tc-tic.md

My understanding is that package share is being deprecated so it seems like references to package share should be replaced references to the partner exchange. I also have a partner that reached out to ask if they could be added to the list of translation partners. I let them know that they can't be added to package share but they were wondering if they could be added to the list on this page. Can we either add them to the list or remove the list entirely and ask AEM customers to search for translation partners on the exchange? (You can reach out to me on our internal Adobe Slack—@jmadsen—or via email for partner details). Thanks!

**Comment by guillaumecarlino** [comment]
References to Package share are removed and list is updated.
