### ISSUE TITLE
Add a note that provided sample package only works Adaptive Forms Submit Action.

### ISSUE THREAD

**Issue by samdhawa** [AdobeDocs/experience-manager-65.en#58]
Issue in help/forms/using/integrate-draft-submission-database.md

The Sample provided for customized data and metadata services to integrate drafts and submissions component with a database works only Adaptive Form Submission. (refer below Documentation)
https://docs.adobe.com/content/help/en/experience-manager-65/forms/publish-process-aem-forms/integrate-draft-submission-database.html

**Comment by bohnertchris** [comment]
Thank you for the issue, @samdhawa . Can you please clarify what is unclear/incorrect in the document you referred to? What are you expecting to read?

**Comment by singhkh** [comment]
@samdhawa, are you looking to use PDF and XDP forms also.

**Comment by bohnertchris** [comment]
Closing this as fixed via commit 41f1c0e. If something is still unclear, please create a new issue.
