### ISSUE TITLE
Assets HTTP API - clarification on dc: namespace metadata update

### ISSUE THREAD

**Issue by leoberliant** [AdobeDocs/experience-manager-65.en#6]
Issue in help/assets/mac-api-assets.md
The article needs clarification for "[Update Asset metadata](https://docs.adobe.com/content/help/en/experience-manager-65/assets/extending/mac-api-assets.html#update-asset-metadata)"
The sample request intended to update dc:title but it's actually updating jcr:title. It's expected behavior and we need to explicitly mention, that the API does not sync dc:title and jcr:title properties. The same behavior is for any properties under dc: namespace. It's possible to sync dc: and jcr: properties by employing a workflow with an ECMA script.

Logged by Support

**Comment by ashishguptaiitb** [comment]
Thanks @leoberliant  for reporting this issue. We mention that some properties in jcr: and dc: namespaces are handled differently. Can you confirm if this is true for all properties or just the ones that are called out in the note:

*Some properties of folder or asset are mapped to a different prefix. The jcr prefix of jcr:title , jcr:description , and jcr:language are replaced with dc prefix. Hence in the returned JSON, dc:title and dc:description contain the values of jcr:title and jcr:description , respectively.*

**Comment by leoberliant** [comment]
@ashishguptaiitb this is true for all properties from the **dc:** namespace.
When attempting to update _dc:title_, it updates _jcr:title_, when updating _dc:description_, it updates _jcr:description_ and so on.

**Comment by ashishguptaiitb** [comment]
Thanks @leoberliant  for the confirmation. I have made the changes. The article should get updated in a few hours. When it happens, I shall close this issue. 

Appreciate you taking the time to get this updated.

**Comment by ashishguptaiitb** [comment]
Updated at https://docs.adobe.com/content/help/en/experience-manager-65/assets/extending/mac-api-assets.html#update-asset-metadata
