### ISSUE TITLE
Screenshots Wrong

### ISSUE THREAD

**Issue by bryanledford** [AdobeDocs/experience-manager-65.en#60]
Issue in help/communities/functions.md

A lot of the screenshots seem to be from MySQL Workbench and don't relate to the documentation.

**Comment by mgulati1** [comment]
Thanks for informing us @bryanledford. @vishabhguptaadobe will look into the same.

**Comment by bohnertchris** [comment]
CQDOC-15830

**Comment by vishabhguptaadobe** [comment]
@bohnertchris 
Thanks for creating the ticket, I have assigned it to myself: https://jira.corp.adobe.com/browse/CQDOC-15830 
There are other instances as well that are identified in communities repo after migration.
All the migration issues will be fixed soon.

**Comment by bohnertchris** [comment]
I appreciate the update. Thank you!

**Comment by vishabhguptaadobe** [comment]
Updated all the correct images. 
Also, in-progress with other instances in the repo.
