### ISSUE TITLE
6.5 Doc says about 6.4 in some places

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-65.en#62]
Issue in help/sites-deploying/backward-compatibility.md

The document starts with 6.5, but it keeps mentioning about 6.4, instead of 6.5 in some places.
_For exceptions where features could not be kept backward compatible, backward incompatibility issues for bundles and content can be mitigated by installing a Compatibility Package for **6.4** (please see how to setup below for details on where to download). This compat package will help restore compatibility in most cases for applications compliant with **AEM 6.4**._

6.4 should be changed to 6.5.

[Logged by AEM Support]

**Comment by aheim0** [comment]
Thanks for highlighting this - the text, image and link have been updated.
Closing issue.
