### ISSUE TITLE
Interactive Editing for PDF/AI is not available on AEM instance which is conflicting what our document states as supported

### ISSUE THREAD

**Issue by lha-adobe** [AdobeDocs/experience-manager-65.en#63]
Issue in help/assets/assets-formats.md

Refer to https://docs.adobe.com/content/help/en/experience-manager-65/assets/administer/assets-formats.html#supported-document-formats

The document states there is Interactive editing available for PDF and AI , however, the UI does not have any edit options as expected.  There may be issue with our documentation being outdated.

Please correct the documentation if PDF/AI interactive editing is no longer supported.

DL-Tech email subject : "Interactive editing for PDF / AI AEM 6.5.4.0 (212666)"
Daycare ticket # 212666
{{Logged by Support}}

**Comment by ashishguptaiitb** [comment]
I acknowledge this one Lisa. I'm addressing it. I hope to update the published in a day or two.

**Comment by ashishguptaiitb** [comment]
Updated article is live at https://docs.adobe.com/content/help/en/experience-manager-65/assets/administer/assets-formats.html

Thanks Lisa for bringing this to our attention.
