### ISSUE TITLE
Incomplete document

### ISSUE THREAD

**Issue by himanshu-pathak** [AdobeDocs/experience-manager-65.en#65]
Issue in help/sites-administering/adobeanalytics-classifications.md

Couple of issues in the docs.
1. "Navigate via Tools, Cloudservices to the Adobe Analytics section." The Adobe analytics cloud service has moved to "Legacy Cloud Services". Should be corrected.

2. I don't see the "**Adobe Analytics Classifications** Configuration template" OOTB. If there are any prerequisites to enable it, they must be documented. The default screen looks like the attched screen.

![Screen Shot 2020-04-29 at 10 31 37 AM](https://user-images.githubusercontent.com/20474906/80562196-9f93fe80-8a04-11ea-999a-3aa37818c86d.png)

**Comment by aheim0** [comment]
Thank you for raising this issue. We have investigated and published updates to the page.
