### ISSUE TITLE
geometrixx doesn't exist on both AEM 6.5

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-65.en#66]
Issue in help/sites-administering/security.md

On the following section: https://docs.adobe.com/content/help/en/experience-manager-65/administering/security/security.html#access-control-lists-and-how-they-are-evaluated

geometrixx doesn't exist on AEM 6.5. It should be changed to we-retail instead in the documents for 6.5.

Regarding below:

1) /etc/cloudservices/facebookconnect/geometrixx-outdoorsfacebookapp

2) /etc/cloudservices/twitterconnect/geometrixx-outdoors-twitter-app

3) /content/geometrixx-outdoors/en/community/hiking

4) /content/geometrixx-outdoors/en/community/winter-sports

5) /home/users/geometrixx-outdoors

1) & 2) don't exist on 6.5. You can replace those paths with just one /etc/cloudservices
You can replace 3) & 4) with /content/we-retail/us/en/community
You can replace 5) with /home/users/we-retail

[Logged by AEM Support]

**Comment by aheim0** [comment]
Thanks for highlighting this - the updates have been applied and will be published soon.
Closing issue.
