### ISSUE TITLE
Add note on display of expiration date field on users timezone

### ISSUE THREAD

**Issue by ycastane** [AdobeDocs/experience-manager-65.en#69]
Issue in help/assets/drm.md

Add a note to explain that asset expiration date field appears differently depending on each users timezone 

[Logged by Support]

**Comment by ashishguptaiitb** [comment]
Thanks @ycastane . Good point. I shall update it in our docs.

**Comment by ashishguptaiitb** [comment]
The updates are published at https://docs.adobe.com/content/help/en/experience-manager-65/assets/administer/drm.html. I'm closing the ticket.

Thanks for sharing this @ycastane .
