### ISSUE TITLE
Improper format of URL

### ISSUE THREAD

**Issue by lmha** [AdobeDocs/experience-manager-65.en#7]
Issue in help/sites-deploying/tarmk-cold-standby.md

See the URL in step #3 for 'Cold Standby Repository Maintenance' (https://docs.adobe.com/content/help/en/experience-manager-65/deploying/deploying/tarmk-cold-standby.html#cold-standby-repository-maintenance)
`Run the oak compaction tool on the primary instance. For more details, see #(/help/sites-deploying/storage-elements-in-aem-6.md#maintaining the repository).`

It should be an actual URL for users to click and navigate to.

{Logged by Support}

**Comment by aheim0** [comment]
Thank you for highlighting this issue and suggesting a solution. This has been addressed in commit 29328ff, and the changes are now live.
