### ISSUE TITLE
Replace all occurrences of geometrixx with we-retail

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-65.en#71]
Issue in help/sites-classic-ui-authoring/classic-page-author-manage-pages.md

In AEM 6.5, We-Retail is used instead of Geometrixx. We need to replace all occurrences of geometrixx with we-retail.
All of the text occurrences exist here: https://docs.adobe.com/content/help/en/experience-manager-65/classic-ui/authoring/classic-page-author-manage-pages.html#organizing-your-website

a) Replace:
Author environment
_http://localhost:4502/cf#/content/geometrixx/en/products/triangle.html_
Publish environment
_http://localhost:4503/content/geometrixx/en/products/triangle.html_

With:
Author environment
_http://localhost:4502/siteadmin#/content/we-retail/us/en/products/men.html_
Publish environment
_http://localhost:4503/content/we-retail/us/en/products/men.html_

b) Replace:
/content
    /geometrixx
      /en
        /toolbar...
        /products
          /triangle
            /overview 
            /features
          /square...
          /circle...
          /...
        /...
      /fr...
      /de...
      /es...
      /...
    /...

With:

/content
    /we-retail
         /us
		/en
			/products
				/men
				/women
				/equipment
			    /...
			/...
		/es
		/...
	  /...
    /...

c) Replace:
Image with source to: /content/dam/help/experience-manager-65.en/help/sites-classic-ui-authoring/assets/chlimage_1-151.png

With:
Image with source to: WeRetail-OpenPage.jpg
![WeRetail-OpenPage](https://user-images.githubusercontent.com/59624839/81090702-2563ee00-8ecc-11ea-968b-f3fbaa4ba371.jpg)

d) Location: https://docs.adobe.com/content/help/en/experience-manager-65/classic-ui/authoring/classic-page-author-manage-pages.html#managing-pages
Replace:
Image with source to: /content/dam/help/experience-manager-65.en/help/sites-classic-ui-authoring/assets/screen_shot_2012-02-15at114413am.png

With:
Image with source to: WeRetail-US-EN-Products-NewPage.jpg
![WeRetail-US-EN-Products-NewPage](https://user-images.githubusercontent.com/59624839/81090735-2dbc2900-8ecc-11ea-9254-42e211503f15.jpg)

e) Replace:
Image with source to: /content/dam/help/experience-manager-65.en/help/sites-classic-ui-authoring/assets/screen_shot_2012-02-15at114845am.png

With:
Image with source to: WeRetail-Products-CreateNewPage.jpg
![WeRetail-Products-CreateNewPage](https://user-images.githubusercontent.com/59624839/81090748-3280dd00-8ecc-11ea-945c-aea5f179fdb4.JPG)

f) Location: https://docs.adobe.com/content/help/en/experience-manager-65/classic-ui/authoring/classic-page-author-manage-pages.html#moving-or-renaming-page

Replace: 
Image with source to: /content/dam/help/experience-manager-65.en/help/sites-classic-ui-authoring/assets/screen_shot_2012-02-15at121336pm.png

With:
Image with source to: We-Retail-Move_and_Republish.jpg
![We-Retail-Move_and_Republish](https://user-images.githubusercontent.com/59624839/81090763-36acfa80-8ecc-11ea-8155-9858d2d401e4.JPG)

[Logged by AEM Support]

**Comment by bohnertchris** [comment]
CQDOC-16170

**Comment by bohnertchris** [comment]
Apologies for taking so long to respond, @sukohli, but I seemed to have overlooked this in my queue.

I appreciate the effort and detail you put into the issue, but We.Retail does not support the classic UI [1]. Therefore such an update is not possible.


[1] https://docs.adobe.com/content/help/en/experience-manager-64/developing/bestpractices/we-retail/we-retail.html#getting-started
