### ISSUE TITLE
CUGs and permissions on Blueprints not inherited by Live Copies

### ISSUE THREAD

**Issue by aaksinghAdobe** [AdobeDocs/experience-manager-65.en#72]
Issue in help/sites-administering/msm-best-practices.md

As a FYI to customer and to avoid any confusion, please look to add the comment to the page around CUGs or permissions when added to Blueprint, does not mean the live copies will have the same permissions when Blueprint is rolled out.. 

I did some testing on my end and confirmed it is as per design.
CUGs or any related permission applied to Language Masters will not be inherited by referenced Live copies when a blueprint is rolled out.

In order to set up a section of the website to be only accessed by members of CUGs.
CUGs will need to be set on the live copies as well.

Add a note to the documentation :
**[NOTE!]
Note that CUGs in the Permissions tab cannot be rolled back from Blueprints to Live Copies. Please plan around this when configuring Live Copy.**

The same note is on [1] and [2]

[1] https://github.com/AdobeDocs/experience-manager-64.en/blob/master/help/sites-administering/cug.md
[2] https://github.com/AdobeDocs/experience-manager-64.en/blob/master/help/sites-administering/closed-user-groups.md#aem-livecopy

**Comment by bohnertchris** [comment]
We have added the note to the MSM best practices page in the 6.4 (a8d3add), 6.5 (7bbab10), and AEMaaCS (5f955e7) repositories.
