### ISSUE TITLE
Steps to configure CUG seems out of date

### ISSUE THREAD

**Issue by aaksinghAdobe** [AdobeDocs/experience-manager-65.en#73]
Issue in help/sites-administering/cug.md

Under section: **Applying Your Closed User Group To Content Pages**

Instructions are correct until Step 7.
Before Step 8,9 needs to be referencing back to Advanced Tab {as in step 3}.
When the Authentication requirement is being set up with CUG. 

Step 10 (Admitted Group) and step 11 (Realm) are not relevant to AEM 6.5

**Comment by aheim0** [comment]
Thanks for highlighting this - the procedure has been updated.
Closing this issue.
