### ISSUE TITLE
Guidebridge link on bottom of page links to 404.

### ISSUE THREAD

**Issue by lesutton** [AdobeDocs/experience-manager-65.en#74]
Issue in help/forms/using/using-som-expressions-adaptive-forms.md

**Comment by anujkapo** [comment]
Thanks, Lee (@lesutton)  for reporting the issue. It is fixed with the following git commit:
https://git.corp.adobe.com/AdobeDocs/experience-manager-65.en/pull/588/commits/6b4bc58efd72900c54cb245878239e345d72ae3e

**Comment by anujkapo** [comment]
Closing the issue.
