### ISSUE TITLE
Company-internal area of package share - Add Private Sharing doesn't work. Domain: dev.day.com is gone. Thus, customers are unable to upload & share packages via Package Share.

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-65.en#77]
Issue in help/sites-administering/package-manager.md

Company-internal area of package share - Add Private Sharing doesn't work. Domain: dev.day.com is gone. Thus, customers are unable to upload & share packages via Package Share anymore.

Please remove or mark deprecated the @*Uploading a package*@ section of the document.
https://docs.adobe.com/content/help/en/experience-manager-65/administering/contentmanagement/package-manager.html#uploading-a-package

[Logged by AEM Support]

**Comment by bohnertchris** [comment]
Thank you for reporting this, @sukohli. This was already fixed as detailed in https://github.com/AdobeDocs/experience-manager-64.en/issues/90
