### ISSUE TITLE
Globs should be refactored

### ISSUE THREAD

**Issue by thedoc31** [AdobeDocs/experience-manager-65.en#78]
Issue in help/communities/dispatcher.md

The recommended dispatcher filters to be added use `/glob` patterns which are inherently insecure and can be interpreted in unexpected ways. These should be refactored to support the newer dispatcher syntax; without that, it could allow vulnerabilities through that a proper configuration would not.

**Comment by mgulati1** [comment]
Thanks for the inputs. @vishabhguptaadobe will look into this.

**Comment by vishabhguptaadobe** [comment]
Tracked by CQDOC-16081.
The code and content is updated.
