### ISSUE TITLE
List limitation of Cold Standby wrt UI accessible

### ISSUE THREAD

**Issue by lmha** [AdobeDocs/experience-manager-65.en#8]
Issue in help/sites-deploying/tarmk-cold-standby.md

There should be a specific mention regarding all the pages that you can access when logging into the Coldstandby instance -- e.g. OSGi consoles are accessible

Customers attempt to access other UIs and are confused as to why they are 'not working'.

{Logged by Support}

**Comment by bohnertchris** [comment]
@sarchiz could you have a look at this, please?

**Comment by aheim0** [comment]
Thanks for highlighting this - a note has been added.
Closing this issue.
