### ISSUE TITLE
Update the Obsolete Bundles docs

### ISSUE THREAD

**Issue by jbrarAdobe** [AdobeDocs/experience-manager-65.en#80]
Issue in help/sites-deploying/obsolete-bundles.md

We need to provide more details and mention that this only applies when upgrading from an AEM version 6.1 & below.

Example: It applies when moving from 6.1 to 6.5 but does not apply when moving from 6.2 to 6.5

**Comment by aheim0** [comment]
Tracked with CQDOC-16082

**Comment by aheim0** [comment]
Thanks for highlighting this. It looks as if the issue has been fixed in the meantime.
- https://experienceleague.adobe.com/docs/experience-manager-65/deploying/upgrading/obsolete-bundles.html?lang=en 

Closing this issue.
