### ISSUE TITLE
Update of template paths required 

### ISSUE THREAD

**Issue by ycastane** [AdobeDocs/experience-manager-65.en#82]
Issue in help/sites-administering/notification.md

Many paths mentioned point to /etc/notification/email/default/ which are no longer valid.  All paths should be updated for 6.4/6.5 documentation 

[Logged by Support]

**Comment by bohnertchris** [comment]
Thanks for the issue, @ycastane . We will have a look.

CQDOC-16112

**Comment by aheim0** [comment]
See also CQDOC-16252 and CQDOC-18505.

**Comment by aheim0** [comment]
The majority of paths have been updated. Those for collaboration are outside our scope, but a specific issue has been opened for the appropriate team.
Closing this issue now.
