### ISSUE TITLE
Explain Query -> Replace images at https://docs.adobe.com/content/help/en/experience-manager-65/administering/operations/operations-dashboard.html#explain-query

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-65.en#83]
Issue in help/sites-administering/operations-dashboard.md

Replace the below image located at https://docs.adobe.com/content/help/en/experience-manager-64/administering/operations/operations-dashboard.html#explain-query :
![image](https://user-images.githubusercontent.com/59624839/82911901-6d5dba00-9f3a-11ea-8365-cc0d6fec85b1.png)

It shows just: _Include Execution Time_ option.

With:
![image](https://user-images.githubusercontent.com/59624839/82911920-73539b00-9f3a-11ea-9466-0aa99532c25c.png)

It includes both: _Include Execution Time & Include Node Count_ options.

[Logged by AEM Support]

**Comment by bohnertchris** [comment]
Thanks for the suggestion, @sukohli. We will take care of this.

**Comment by bohnertchris** [comment]
CQDOC-16123

**Comment by aheim0** [comment]
Thank you for highlighting this - the image has been replaced and a short text added.
Closing issue.
