### ISSUE TITLE
Issue with Index Manager section in AEM 6.5 doc -> Need to replace the image with the correct one.

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-65.en#84]
Issue in help/sites-administering/operations-dashboard.md

Section of document: https://docs.adobe.com/content/help/en/experience-manager-65/administering/operations/operations-dashboard.html#the-index-manager

The original image:
![image](https://user-images.githubusercontent.com/59624839/82922384-86209c80-9f47-11ea-9c43-d251b64a278c.png)

must be replaced with:
![image](https://user-images.githubusercontent.com/59624839/82922397-8caf1400-9f47-11ea-9b2d-a5ca97531f0e.png)

AEM 6.5 doesn't have any option to **Reindex** via Index Manager.

[Logged by AEM Support]

**Comment by bohnertchris** [comment]
Thanks for the suggestion, @sukohli. We will take care of this.

**Comment by bohnertchris** [comment]
CQDOC-16120

**Comment by bohnertchris** [comment]
This was corrected with commit dd8f24c.
