### ISSUE TITLE
Mispelling of clientlibs

### ISSUE THREAD

**Issue by justinedelson** [AdobeDocs/experience-manager-65.en#85]
Issue in help/sites-developing/clientlibs.md

Mispelling:

Here is an example: https://localhost:4503/etc.clientlibs/geometrixx/components/clinetlibs/resources/example.gif

should be

Here is an example: https://localhost:4503/etc.clientlibs/geometrixx/components/clientlibs/resources/example.gif

**Comment by bohnertchris** [comment]
Thanks for pointing this out, @justinedelson. We will correct.

**Comment by bohnertchris** [comment]
CQDOC-16134

**Comment by bohnertchris** [comment]
This was corrected in commit d1222b7 to the 6.4 repository and commit 104fa70 to the 6.5 repository (this repo).
