### ISSUE TITLE
Update the screenshot for configuration for 6.5

### ISSUE THREAD

**Issue by aaksinghAdobe** [AdobeDocs/experience-manager-65.en#86]
Issue in help/sites-administering/sync.md

The screenshot under the following title on page is outdated:
1. Apache Sling Distribution Agent - Sync Agents Factory

The new configuration for Sling Distribution Agent - Sync Agents Factory includes  Priority Queue, Retry strategy and other new configurations that are not explained or part of the documentation.

The screenshot for new configurations as in 6.5 is below:
![image](https://user-images.githubusercontent.com/62261083/83167845-a171e000-a0de-11ea-87e1-59ed9bb8c0d4.png)

**Comment by bohnertchris** [comment]
Thank you for pointing this out, @aaksinghAdobe. We will correct it.

CQDOC-16146

**Comment by aheim0** [comment]
Thanks for highlighting this. We have updated the screenshot, but not the text as this location is limited to enabling the option - and the OSGi list is self-documenting.
Closing this issue.
