### ISSUE TITLE
"To configure AEM" section not mandatory

### ISSUE THREAD

**Issue by ycastane** [AdobeDocs/experience-manager-65.en#87]
Issue in help/sites-administering/config-video.md

Section "To configure AEM :" is only required if further customization of codecs is required.  

[Logged by Support]

**Comment by bohnertchris** [comment]
Thank you for the information, @ycastane. We will look into this.

CQDOC-16144

**Comment by aheim0** [comment]
Thank you for raising this - a note has been added to highlight the matter. 
Will now close this issue.
