### ISSUE TITLE
6.5 documentation clearly just a copy paste from 6.3

### ISSUE THREAD

**Issue by EdHarris1983** [AdobeDocs/experience-manager-65.en#89]
Issue in help/sites-developing/querybuilder-predicate-reference.md

This documentation is clearly jut a copy/paste of the 6.3 version that never got looked at to verify it was correct.  At the very least, the property predicate section does not accurately describe what someone would encounter when implementing that use case.  I'm sure there are others.  The whole page likely needs to be re-done from scratch, since the UI has changed significantly from 6.3 to 6.5

**Comment by bohnertchris** [comment]
Thank you for the issue, @EdHarris1983. We will investigate.

CQDOC-16163

**Comment by aheim0** [comment]
Thank you for raising this issue. Due to resource constraints we have added links to up-to-date information and indicated that the list isn't exhaustive. Hope this helps. The changes will be published soon.
Closing this issue.
