### ISSUE TITLE
Jmockit framework link redirected to different webpage than mockito framework page

### ISSUE THREAD

**Issue by surya057** [AdobeDocs/experience-manager-65.en#9]
Issue in help/sites-developing/ht-projects-maven.md

Hi, 

Step: 1  Search for keyword "Jmockit" hyperlink 
Step 2: Click on it
The expected page is mockito framework page but I see some medical page. 

![image](https://user-images.githubusercontent.com/12661298/72341640-a0598c80-36c2-11ea-82b6-ad4d73ac3d94.png)

please check this.

**Comment by bohnertchris** [comment]
Thank you for reporting this @surya057. We apologize for any will correct this tragically bizarre error.

**Comment by bohnertchris** [comment]
Also need to correct in the 6.4 docs.

**Comment by bohnertchris** [comment]
Fixed in commits:

2c907e9 in experience-manager-65.en
6483ef1 in experience-manager-64.en
