### ISSUE TITLE
Create Adobe I/O integration section - Integrations are now Projects 

### ISSUE THREAD

**Issue by ycastane** [AdobeDocs/experience-manager-65.en#90]
Issue in help/assets/configure-aem-assets-with-brand-portal.md

With respect to "Create Adobe I/O integration section" - Integrations are now Projects.  Please update steps and images accordingly. 

[Logged by Support]

**Comment by bohnertchris** [comment]
Thank you for the issue, @ycastane. We will investigate.

CQDOC-16164

**Comment by vishabhguptaadobe** [comment]
@bohnertchris @ycastane 
Adobe I/O is now changed to Adobe Developer Console, there are branding, workflow, and UI changes including the one you said "now it is done under projects", and so on.
I am working on updating the docs and it is in-progress. 
We already have updated AEM Assets Cloud Service docs and working on AEM 6.5 docs following on with AEM 6.4 and AEM 6.3 docs.

**Comment by vishabhguptaadobe** [comment]
This has been implemented for AEM Assets Cloud Service and AEM 6.5.
https://docs.adobe.com/content/help/en/experience-manager-cloud-service/assets/brand-portal/configure-aem-assets-with-brand-portal.html
https://docs.adobe.com/content/help/en/experience-manager-65/assets/brandportal/configure-aem-assets-with-brand-portal.html 
We have internal tasks for updating it for AEM 6.4 and 6.3 targeted soon.
