### ISSUE TITLE
Create Adobe I/O integration section - Integrations are now Projects 

### ISSUE THREAD

**Issue by ycastane** [AdobeDocs/experience-manager-65.en#91]
Issue in help/assets/config-smart-tagging.md

With respect to "Create Adobe I/O integration section" - Integrations are now Projects.  Please update steps and images accordingly. 

[Logged by Support]

**Comment by ashishguptaiitb** [comment]
Thanks @ycastane . It is tracked via CQDOC-16155.

**Comment by ashishguptaiitb** [comment]
The docs were updated for new IO integration via cqdoc-16155. Closing this GitHub issue as well.
