### ISSUE TITLE
Asset expiry notification not sending to administrator as documented

### ISSUE THREAD

**Issue by ycastane** [AdobeDocs/experience-manager-65.en#92]
Issue in help/assets/drm.md

As per #5 in section for configuring Adobe CQ DAM Expiry Notification.  The admin is never sent an email.  In reviewing internally code only notifies createdBy user.  

Please update documentation.  

[Logged by Support]

**Comment by bohnertchris** [comment]
Thank you for the issue, @ycastane. We will have a look.

CQDOC-16166

**Comment by ashishguptaiitb** [comment]
Thanks @ycastane . The article is updated now.
https://docs.adobe.com/content/help/en/experience-manager-65/assets/administer/drm.html
