### ISSUE TITLE
Correct the path of temp version created in AEM 6.5

### ISSUE THREAD

**Issue by manish112** [AdobeDocs/experience-manager-65.en#93]
Issue in help/sites-authoring/page-diff.md

In AEM 6.5, when we do a version comparison of pages, the location where a temporary page gets created is /tmp/versionhistory while the documentation mentions this as  /content/versionhistory

Please update the document accordingly.

[Logged By Support]

**Comment by bohnertchris** [comment]
Thanks for reporting, @manish112. We will look into it.

CQDOC-16190

**Comment by bohnertchris** [comment]
This was corrected in merge dc8b400 to 6.4 and in merge 13010f7 to 6.5.
