### ISSUE TITLE
Include information around nesting of experience fragments in best practices

### ISSUE THREAD

**Issue by aaksinghAdobe** [AdobeDocs/experience-manager-65.en#95]
Issue in help/sites-developing/dev-guidelines-bestpractices.md

Request to include information around Nesting of experience fragments in responsive grid.

It looks like the render time of the page is impacted when nested Experience Fragments are included.

This issue has been reported in the past for AEM 6.4 and 6.5 and would be good to document as a best practice.

**Comment by bohnertchris** [comment]
Thank you for the suggestion, @aaksinghAdobe. We will review.

CQDOC-16207

**Comment by bohnertchris** [comment]
Closed see CQDOC-16207 for details.
