### ISSUE TITLE
Minor Typo

### ISSUE THREAD

**Issue by lha-adobe** [AdobeDocs/experience-manager-65.en#97]
Issue in help/sites-developing/page-templates-editable.md

Minor typo on page https://docs.adobe.com/content/help/en/experience-manager-65/developing/platform/templates/page-templates-editable.html

Existing text:
`Editing templates is very powerful and if not done properly exiting templates can be broken. Therefore this role should be focused and only include qualified users.`

The fixed text should be:
`Editing templates is a powerful function and if not done properly, existing templates can be broken. Therefore, this role should be focused and only include qualified users.`

** NOTE minor changes and fixed grammar

**Comment by bohnertchris** [comment]
Thank you for reporting this, @lha-adobe. We will correct.

CQDOC-16220

**Comment by bohnertchris** [comment]
This was corrected in commit 67c1951 to the 6.4 repository and commit d436777 to 6.5.
