### ISSUE TITLE
Add more details about the "Incoming Links " functionality

### ISSUE THREAD

**Issue by jbrarAdobe** [AdobeDocs/experience-manager-65.en#98]
Issue in help/sites-authoring/author-environment-tools.md

For the "Incoming Links" feature we need to provide some examples of the links AEM will show, such as the following:

Templates
Launches
Live Copies
Language Copies
Rollout Configs

**Comment by bohnertchris** [comment]
Thank you for the suggestion, @jbrarAdobe. We will review.

**Comment by bohnertchris** [comment]
CQDOC-16228

**Comment by bohnertchris** [comment]
Closed. See CQDOC-16228 for details.
