### ISSUE TITLE
Include Note for customers that may have /apps/system/config/org.apache.sling.jcr.davex.impl.servlets.SlingDavExServlet.config within their custom code

### ISSUE THREAD

**Issue by lha-adobe** [AdobeDocs/experience-manager-65.en#99]
Issue in help/sites-administering/enabling-crxde-lite.md

Page in question: https://docs.adobe.com/content/help/en/experience-manager-65/administering/security/enabling-crxde-lite.html

This document should have a mention that the cURL command will create a sling:OsgiConfig node at /apps/system/config/org.apache.sling.jcr.davex.impl.servlets.SlingDavExServlet

Customers who have included a /apps/system/config/org.apache.sling.jcr.davex.impl.servlets.SlingDavExServlet.config (NOTE the .config extension) may not see the cURL command take effect dependent on which config is INSTALLED state in /system/console/osgi-installer UI
e.g. if the /apps/system/config/org.apache.sling.jcr.davex.impl.servlets.SlingDavExServlet.config is in INSTALLED state, the cURL command will not take effect to enable/disable the crx/de console.  The cURL command will only have effect if the /apps/system/config/org.apache.sling.jcr.davex.impl.servlets.SlingDavExServlet is in INSTALLED state
*** NOTE that changes in /system/console/configMgr will result in creation of .config files in /apps/system/config as detailed in document [1] which states:
Configuration changes made using the Web Console are persisted in the repository as configuration files ( .config ) under:
/apps

C14E ticket # E-000153206
{{Logged by Support}}

[1] https://docs.adobe.com/content/help/en/experience-manager-65/deploying/configuring/configuring-osgi.html#osgi-configuration-with-configuration-files

**Comment by bohnertchris** [comment]
Thank you for the suggestion, @lha-adobe. We will review.

CQDOC-16241

**Comment by lha-adobe** [comment]
In case customer does have the nt:file .config , the cURL command to update that to enable CRXDE would be : 
`curl -u admin:admin -X POST -d "apply=true" -d "propertylist=alias,dav.protectedhandlers,dav.create-absolute-uri" -d "alias=/crx/server" -d "dav.protectedhandlers=org.apache.jackrabbit.server.remoting.davex.AclRemoveHandler" -d "dav.create-absolute-uri=true" "factoryPid=org.apache.sling.jcr.davex.impl.servlets.SlingDavExServlet.config" http://localhost:4502/system/console/configMgr/org.apache.sling.jcr.davex.impl.servlets.SlingDavExServlet`

Reference at http://felix.apache.org/documentation/subprojects/apache-felix-web-console/web-console-restful-api.html#apply

**Comment by aheim0** [comment]
Apologies for the delay. This page has been updated (>1) since this issue was registered, so should be fixed. 
Will close this issue now, if further changes are required please open a new issue.
